### ISSUE TITLE
Node.js 6.11 support

### ISSUE THREAD

**Issue by koistya** [patrickjuchli/basic-ftp#10]
Doesn't work with Google Cloud Functions

```
Detailed stack trace: /user_code/node_modules/basic-ftp/lib/ftp.js:107
    async useTLS(options = {}, command = "AUTH TLS") {
```

**Comment by patrickjuchli** [comment]
As documented this library requires version 7.6.

Google Cloud Functions doesn’t support the latest LTS version 8. This seems to cause a bit of a stir in the [corresponding ticket](https://issuetracker.google.com/issues/66770141). After more than half a year, the status of the ticket doesn't seem to be clear. Not so reassuring.

Async-await has been introduced with 7.6 and simplifies the implementation of this library considerably, especially directory-level operations. I’m not convinced I should rewrite these parts for Google Cloud Functions, sorry. There are two other options which might help your use-case: [node-ftp](https://github.com/mscdex/node-ftp) and [jsftp](https://github.com/sergi/jsftp).

**Comment by ds82** [comment]
Just wanna add my opinion that it is bad practice for libs to not support at least all lts versions that are in active maintenance. Today that's node 6.x (until april 2019).

**Comment by ds82** [comment]
Don't take this so personally .. it's just my opinion. I'm thankful for everyone who contributes to opensource/the ecosystem, but that doesn't mean that I'm not allowed to say my opinion. Beyond that I never said that no code that does not follow this should be shared, I just said that it is a bad practice. 

And I didn't mean to be harsh at all, sorry if it sounded like that.

Thing is it would probably quite easy to follow this proposal if you just transpile your lib with babel before you publish it ..
