### ISSUE TITLE
TLS/SSL Implicit Encryption

### ISSUE THREAD

**Issue by sk3xn3t** [patrickjuchli/basic-ftp#100]
I'm trying to connect to an FTP Server and list the files in a folder but I'm not able to do so:

The Server is configured with: TLS/SSL Implicit Encryption

Here's my code:

```
const ftp = require('basic-ftp');

async function listFilesInFtpFolder() {
  const client = new ftp.Client()
  client.ftp.verbose = true;
  try {
      await client.access({
          host: ftpConfig.host,
          user: ftpConfig.user,
          password: ftpConfig.password,
          port: ftpConfig.port,
          secure: false
      });

      // ********************** NOTE **********************
      // The execution never reaches here, it gets stuck in the 
      // ... previous statement until it times out
      // ********************** NOTE **********************

      console.log('connected');
      console.log(await client.list())

  }
  catch(err) {
      console.log(err)
  }
  client.close()
}
```

Getting this error:

Connected to 155.66.22.88:6610

Error: Timeout (control socket)
    at Socket.<anonymous> (C:\Dev\my-app\node_modules\basic-ftp\dist\FtpContext.js:296:58)
    at Object.onceWrapper (events.js:298:28)
    at Socket.emit (events.js:209:13)
    at Socket._onTimeout (net.js:468:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by sk3xn3t** [comment]
@patrickjuchli

**Comment by patrickjuchli** [comment]
Please post the console log output when using `client.ftp.verbose = true`.

This library only support "explicit FTP over TLS", not implicit.

**Comment by sk3xn3t** [comment]
> Please post the console log output when using `client.ftp.verbose = true`.
> 
> This library only support "explicit FTP over TLS", not implicit.

I did miss that part, apologies, if you can please do close this issue.
Do you know of any Node.js librareis that suport Implicit FTP over TLS ?
