### ISSUE TITLE
DownloadTo a writable stream

### ISSUE THREAD

**Issue by Roman991** [patrickjuchli/basic-ftp#102]
I'm trying to realize how to put the writable stream into a string,
can you pls add this example in doc?

```
    await client.downloadTo(stream, `OUT/${nomeFile}`);

    let stringa = "";
    stream.on("data", (data) => {
      stringa += data.toString();
    });

    stream.on("end", () => {
      console.log(stringa);
    });
```

**Comment by patrickjuchli** [comment]
Sorry but this is a general question about Node.js, please have a look at Stackoverflow. 

Here, we only track issues specific to this library, like bug reports or feature request.

**Comment by Roman991** [comment]
oh, srr about that :)

**Comment by patrickjuchli** [comment]
For future reference: Google "nodejs writable buffer" to get something like https://www.npmjs.com/package/stream-buffers.
