### ISSUE TITLE
EBADF: bad file descriptor, write

### ISSUE THREAD

**Issue by hnakao** [patrickjuchli/basic-ftp#103]
**Describe the bug**
I run once the script to download the content (images) of an entire folder, there was no problem, but the second shows this error and in different files.

**Example code**
`getDataFromFtp = () => {
    return new Promise((resolve, reject) => {
        const client = new ftp.Client()
        client.ftp.verbose = true

        client.access({
            host: process.env.FTP_HOST,
            user: process.env.FTP_USER,
            password: process.env.FTP_PASSWORD,
            port: process.env.FTP_PORT,
            secure: false
        }).then(async () => {
            try {
                console.log(await client.list());
    
                client.trackProgress(info => {
                    console.log("File", info.name);
                    console.log("Type", info.type);
                    console.log("Transferred", info.bytes);
                    console.log("Transferred Overall", info.bytesOverall);
                })
            } catch (error) {
                reject(error);
            }
        }).then(() => {
            client.downloadDir(resourcesDir).then(() => {
                // Stop logging
                client.trackProgress()
                client.close()
                resolve();
            })
        }).catch((error) => {
            reject(error);
        })
    });`

**Console output**
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, write
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:732:7)
    at WriteStream.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at lazyFs.write (internal/fs/streams.js:305:14)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:509:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!`

**Which version of Node.js are you using?**
Node 10.16.0

**Additional context**
I'm running this from Windos Server 2012

**Comment by patrickjuchli** [comment]
Don't mix async/await with `.then()`, it makes your code extremely difficult to understand. Do you really understand what your code is doing? After reading it once, I sure don't.

For example, I see you nesting `downloadDir` in yet another `then()` without returning its Promise. That's not going to work. Seeing this and reading that it "works the first time" really looks like a programming mistake in your function.

Try rewriting your function only with async/await, you don't need any `then` or `return new Promise`. Please use Stackoverflow if you have questions regarding this. I need the issues here to stay focused on library issues.

You are very welcome to reopen if it turns out to be a bug in the library, though.

**Comment by hnakao** [comment]
Your documentation is not very explanatory. I modified the code leaving it like this and with the same result. If you think it's not a problem with the library ... ok for me it's fine, I'll find another solution. Thank you

`exports.getDataFromFtp = async () => {
    const client = new ftp.Client()
    client.ftp.verbose = true
    const resourcesDir = __dirname + '/../resources/';
    try {
        await client.access({
            host: process.env.FTP_HOST,
            user: process.env.FTP_USER,
            password: process.env.FTP_PASSWORD,
            port: process.env.FTP_PORT,
            secure: false
        });
        await client.downloadDir(resourcesDir);
    }
    catch(err) {
        console.log(err)
    }
    client.close()
}`

**Comment by patrickjuchli** [comment]
Can you post the logging ouput in the console?

**Comment by hnakao** [comment]
`< 226 Successfully transferred "/12246-4.jpg"
> EPSV
< 229 Entering Extended Passive Mode (|||59634|)
> RETR 12246-5.jpg
< 150 Opening data channel for file download from server of "/12246-5.jpg"
Downloading from 200.111.94.35:59634 (No encryption)
< 226 Successfully transferred "/12246-5.jpg"
> EPSV
< 229 Entering Extended Passive Mode (|||64708|)
> RETR 12246-6.jpg
< 150 Opening data channel for file download from server of "/12246-6.jpg"
Downloading from 200.111.94.35:64708 (No encryption)
< 226 Successfully transferred "/12246-6.jpg"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, write
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:717:7)
    at WriteStream.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at lazyFs.write (internal/fs/streams.js:305:14)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:509:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! colliers@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by patrickjuchli** [comment]
Can you try running this script on another system/computer/etc.?

**Comment by patrickjuchli** [comment]
Some more questions: How many files are you downloading? You said it works the first time and fails the second. How about the third time? Is it always failing at the same file?

**Comment by patrickjuchli** [comment]
What version of basic-ftp are you using?

**Comment by patrickjuchli** [comment]
Okay, I've found a way to reproduce. Thanks for reporting!

**Comment by patrickjuchli** [comment]
This is a regression that can happen since 4.3.0

**Comment by patrickjuchli** [comment]
@hnakao This should be fixed in 4.3.2. Let me know if it works for you now.

**Comment by hnakao** [comment]
@patrickjuchli Thank you very much, I will try and let you know.

**Comment by hnakao** [comment]
@patrickjuchli Thanks again for your time, apparently it is already solved.
