### ISSUE TITLE
ECONNRESET while using on Travis CI

### ISSUE THREAD

**Issue by mknet** [patrickjuchli/basic-ftp#104]
**Describe the bug**
I'm using basic-ftp to upload some assets. Using it locally works like a charm.
While getting executed on Travis CI it causes an `ECONNRESET` error

**Example code**
See https://github.com/mknet/marcelkoch.net/blob/2019/src/js/deploy.js

**Console output**
See https://travis-ci.com/mknet/marcelkoch.net/builds/134115444

**Which version of Node.js are you using?**
Node 12.4.0

**Additional context**
FTP Server at all-inkl.com. I don't know which FTP server runs there
If you do need further details, let me know and I do my very best.

**Comment by mknet** [comment]
Buy the way: Thx for all the work you did here! I'm very pleased to find this npm package in such good quality.

**Comment by patrickjuchli** [comment]
So it has to do something with the context of Travis CI. I don't know enough about it to have an idea what's going on here. 

The only thing that comes to mind is that Travis CI might have some kind of restriction on outbound connections due to security reasons? Otherwise you could run attacks using the platform. That's all I've got, sorry.

**Comment by patrickjuchli** [comment]
Looking at the logs I can see everything going up until directory listing data is about to be requested. Then the connection fails.

This matches with what Travis CI describes here: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci. This means that FTP can't be used on their runners, they recommend SFTP which is something entirely different.

I will close this ticket as this doesn't seem to be a problem with this library per se.

**Comment by mknet** [comment]
Hey @patrickjuchli,

thanks so much for you help. I appreciate it.
You're absolutely right to close the issue.
I'm gonna try it with other CI solutions like CircleCI or Codeship and come back to document the result here. Alright?

Thx again and greeting to Berlin
