### ISSUE TITLE
Not able to fetch files and folders recursively 

### ISSUE THREAD

**Issue by psr1410** [patrickjuchli/basic-ftp#107]
Not able to fetch the directory listing recursively from the FTP. After few iterations In the console I am seeing that connected server is undefined:undefined and the fetching is stopping.

I am attaching my code file

Console output
fetching ftpListing from  /home/tcapp/git-2.14.1/.github
> EPSV
< 229 Entering Extended Passive Mode (|||12001|).
> LIST -a /home/git-2.14.1/.github
< 150 Here comes the directory listing.
Downloading from undefined:undefined (No encryption)
< 226 Directory send OK.

I am using Node 10.16.3

How can I solve this issue?

[app.txt](https://github.com/patrickjuchli/basic-ftp/files/3855440/app.txt)

**Comment by patrickjuchli** [comment]
There seems to be something special about your context. First, you could try to use the latest version of Node. Next, please don't send whole scripts for me to read. Reduce the problem to the simplest version, like the example in the README:

```js
const ftp = require("basic-ftp")

example()

async function example() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        await client.access({
            host: "myftpserver.com",
            user: "very",
            password: "password",
            secure: true
        })
        await client.downloadToDir("localDir", "remoteDir")
    }
    catch(err) {
        console.log(err)
    }
    client.close()
}
```

**Comment by psr1410** [comment]
@patrickjuchli I will update the Node version. I will let you know once I updated the Node version

I don't want to download the whole directory. I just want to get the names of the files and folders recursively. Only the entire folder structure.

**Comment by patrickjuchli** [comment]
Something like this?

```js
await enumerate() {
  for (const file of await client.list()) {
    if (file.isDirectory) {
      await client.cd(file.name)
      await enumerate()
      await client.cdup()
    }
    else if (file.isFile) {
      console.log(file.name)
    }
  }
}
```

Could you also copy-paste the exact exception that was raised later?

**Comment by psr1410** [comment]
Yes Exactly, While getting the files and folders recursively I am getting below error after few iterations.

`EPSV
< 229 Entering Extended Passive Mode (|||12001|).
LIST -a /home/git-2.14.1/.github
< 150 Here comes the directory listing.
Downloading from undefined:undefined (No encryption)
< 226 Directory send OK.`

But after I updated the Node version. It was working fine. Thanks patrickjuchli

**Comment by patrickjuchli** [comment]
Okay, I'll close this for now.
