### ISSUE TITLE
No response when calling client.access on production server

### ISSUE THREAD

**Issue by Grumme** [patrickjuchli/basic-ftp#109]
**Describe the bug**
I'm trying to upload files using normal FTP. Everything seems to work fine when running on localhost. But when the code is on the production server, it freezes, and do never get out of the await client.access({ }) call.

**Example code**
`const client = new ftp.Client()
    
    client.ftp.verbose = true
    try {
        await client.access({
            host: process.env.FTP_HOST,
            user: process.env.FTP_USER,
            password: process.env.FTP_PASSWORD,
            secure: false
        })
        // console.log(await client.list())
        console.log('Uploading file to FTP')
        await client.uploadFrom(path, "images/bd/" + fileName)
        console.log('Did succesfully upload file')
    } catch (err) {
        console.log(err)
    }
    client.close()`

**Console output**
This is the output from the production server. But I do never get any response after this. When running on localhost files are uploaded correctly to the addressed FTP server.

Connected to server_ip_address:21
< 220 server ready - login please
Login security: No encryption
> USER username
< 331 password required
> PASS ###

**Which version of Node.js are you using?**
v12.13.0

**Additional context**
Production server is Nginx hosted on Digital Ocean. I'm not able to use SFTP to the FTP server I'm trying to access and upload the files to.

**Comment by patrickjuchli** [comment]
Why do you call `client.access` twice?

**Comment by Grumme** [comment]
Sorry, it's a mistake.
I added it to try some few steps for debugging before opening this issue. I have updated my issue, with the correct information.

**Comment by patrickjuchli** [comment]
`PASS ###` is the last thing you see? No timeout exception after some time?

**Comment by patrickjuchli** [comment]
You could also check your firewall settings. Look for a guide online which ports need to be open.

The only thing relevant to this library and this issue board right now is the freeze-up – you should at least get a timeout exception. But you don't, right?

**Comment by Grumme** [comment]
PASS ### is the last thing I see, yes.

After a certain amount of time my request is returned with a 502 Gateway (Due to timeout on the request)

I'm just wondering, why I don't get any feedback at all, which I guess might be a bug? 😊

I just tried to disable the firewall on the droplet (Digital Ocean, Ubuntu 18.04.3). But the same issue persist. I'm just wondering how this would have any effect, since I get the 'PASS ###' as a respond, I guess I have a open connection to the FTP?

**Comment by patrickjuchli** [comment]
If PASS is the last thing you see, then you are not receiving an answer to the password you're sending. I have no idea why this is happening. I don't think I can help you with that.

But you should at least get a timeout by the client. Are you using the default timeout or setting one yourself in the constructor, e.g. `new Client(12345)`?

**Comment by patrickjuchli** [comment]
I tried simulating the situation where no answer arrives after PASS – in my test I get a timeout exception as expected. This is very strange. Have you tried running your script in other environments?

**Comment by patrickjuchli** [comment]
I need you to investigate this a bit more, maybe try another FTP client. There is not much I can do from here since I can't reproduce it.

**Comment by patrickjuchli** [comment]
@Grumme, I will have to close this issue if there is no new information.

**Comment by Grumme** [comment]
I'm going to close it. I will get back to you, if I find the reason. 😊
