### ISSUE TITLE
Download and Copy it into the Azure Blob/Amazon S3 directly

### ISSUE THREAD

**Issue by psr1410** [patrickjuchli/basic-ftp#110]
Can you provide a small example of how to write the stream into Amazon S3/Azure Blob storage without storing it into the local system?

**Comment by patrickjuchli** [comment]
I'm sorry but this tracker is for issues specific to the library, for example bugs. Sites like Stackoverflow are better suited to this kind of question. Without this kind of focus, I'll be answering issues non-stop, I hope you understand.

**Comment by psr1410** [comment]
Sorry @patrickjuchli I can understand. Just asking is this possible with this library. I want to use this library for my entire migration. If it is possible just let me give any references.
