### ISSUE TITLE
Cannot track progress on “ReadableStream”

### ISSUE THREAD

**Issue by VrTech** [patrickjuchli/basic-ftp#111]
When I use readableStream instead of a file, I cannot use transferred bytes. It shows 0 byte at first and then change to the full size of the file till the end. 

`uploadFrom(readableStream | localPath, remotePath): Promise<FTPResponse> `

By the way I’m using Base64 string convert to ReadableStream and upload to the server.

Any help would be grateful !
Please help :(

**Comment by patrickjuchli** [comment]
The only difference between uploading a file and uploading from a stream is that with a file the library sets up the stream for you using `fs.createReadStream`. It's all streams in the end. The progress measured is what really goes through the socket using `socket.bytesWritten` and `socket.bytesRead`.

How large is the data you're uploading? It's possible that you don't get fine-grained progress reports, that's normal.

**Comment by patrickjuchli** [comment]
It's also possible that the data is uploaded quite quickly while the confirmation from the server is taking time. You'd see progress report of "the full size of the file till the end" repeatedly until confirmation arrives.

**Comment by patrickjuchli** [comment]
Any update on this? So far this doesn't sound like a bug if you don't provide more details and I will close this issue.

**Comment by VrTech** [comment]
This is exactly what happened, for example the file is around 5 mb and it shows the following 
- uploading 0%
- uploading 100%
- uploading 100%
- uploading 100%
- uploading 100%
- done upload
 As normally for a file, it’s should be like 0% to 20%,45% 95% and 100%
 Any ideas ?

**Comment by VrTech** [comment]
> It's also possible that the data is uploaded quite quickly while the confirmation from the server is taking time. You'd see progress report of "the full size of the file till the end" repeatedly until confirmation arrives.

This is exactly what happened, for example the file is around 5 mb and it shows the following
- uploading 0%
- uploading 100%
- uploading 100%
- uploading 100%
- uploading 100%
- done upload
 As normally for a file, it’s should be like 0% to 20%,45% 95% and 100%
 Any ideas ?

**Comment by patrickjuchli** [comment]
And if you use `fs.createReadStream(someFile)` it works as expected as well?

Then the issue lies with your readable stream, no? Can you provide more details? How does your readable stream work exactly?

What version of Node are you using?

**Comment by VrTech** [comment]
> And if you use `fs.createReadStream(someFile)` it works as expected as well?
> 
> Then the issue lies with your readable stream, no? Can you provide more details? How does your readable stream work exactly?
> 
> What version of Node are you using?

This is how I work with my readable stream
`
async function base64StringToReadableStream(base64string) {
  try {
    const imgBuffer = Buffer.from(base64string, "base64");
    var s = new Readable();
    s.push(imgBuffer);
    s.push(null);

    return s;
  } catch (err) {
    console.log(err);
  }
}
`

**NODE v8.12.0**

Let me try the fs.createReadStream and I will update back here too 😄

**Comment by patrickjuchli** [comment]
Ok great. Could you maybe also try a newer version of Node? Just to exclude anything on that front.

**Comment by VrTech** [comment]
Oh, It’s actually V12.13.0

**Comment by VrTech** [comment]
> Ok great. Could you maybe also try a newer version of Node? Just to exclude anything on that front.

Oh, It’s actually V12.13.0

and here is the logs from
```
client.trackProgress(info => {console.log("Transferred Overall", info.bytesOverall);});
```

```
2019-11-20T18:15:02.066927+00:00 app[web.1]: upload received
2019-11-20T18:15:02.525114+00:00 app[web.1]: Transferred Overall 0
2019-11-20T18:15:03.025629+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:03.526496+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:04.027373+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:04.528241+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:05.029102+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:05.533041+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:06.036350+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:06.537149+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:07.037877+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:07.538581+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:08.039001+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:08.539973+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:09.041068+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:09.547207+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:10.057192+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:10.308466+00:00 app[web.1]: Transferred Overall 5425421
2019-11-20T18:15:20.690165+00:00 app[web.1]: Done Uploaded
```

**Comment by patrickjuchli** [comment]
I think because you push everything at once, the socket actually does accept everything at once even though it hasn't sent it yet. I then suspect that [socket.bytesWritten](https://nodejs.org/api/net.html#net_socket_byteswritten) that I use for measuring progress doesn't actually reflect what has really been uploaded. Also see [socket.bufferSize](https://nodejs.org/api/net.html#net_socket_buffersize) supporting that idea. `fs.createReadStream` doesn't `push` everything at once which makes sense – streams are here exactly for this reason that we don't need to allocate as much memory as the size of a file.

I'll have a look if I can improve things on this side. Playing around with using `bufferSize` as well doesn't suggest a simple solution though.

**Comment by patrickjuchli** [comment]
See https://github.com/nodejs/node/blob/master/lib/internal/fs/streams.js for the implementation of `fs.createReadStream`

**Comment by patrickjuchli** [comment]
I'm not sure if there is actually a way to measure how many bytes really have been uploaded.

**Comment by VrTech** [comment]
> See https://github.com/nodejs/node/blob/master/lib/internal/fs/streams.js for the implementation of `fs.createReadStream`

Thank you for your suggestion.
I ended up creating a temporary file for size checking and upload through the normal method. After the upload is finished, I just delete the temporary file.
