### ISSUE TITLE
Download Stream not downloading whole content stream

### ISSUE THREAD

**Issue by psr1410** [patrickjuchli/basic-ftp#112]
I am trying to download 5 MB files from FTP using `downloadTo` method into a writable stream. But I am able to download 14kb content only. Why this was happening?

Why I am not able to download all the content at one Go? What is the download stream limit?

How to handle large files download?

**Example code**
var echoStream = new stream.Writable();
echoStream._write = async function (fileChunk, encoding, done) {
    console.log(fileChunk);
    //Writing this content into local file
}
await client.downloadTo(echoStream,fileName);

Node version is 12.13.0

**Comment by patrickjuchli** [comment]
Why is `_write` async? Are you calling `done` when done with a chunk?

Please document why you think this is an issue with the library. Providing a writable stream using e.g. `fs.createWriteStream` or `process.stdout` works? Then the error is more likely connected to your custom writable stream, is it not?

**Comment by psr1410** [comment]
No, I am not calling `done`.

Actually I don't want to save it in my local file system. I want to copy this stream into Azure blob storage directly.

**Comment by patrickjuchli** [comment]
Does this help https://stackoverflow.com/questions/21491567/how-to-implement-a-writable-stream.

**Comment by psr1410** [comment]
I did that example after I saw those posts. But the content downloaded from FTP was just 14kb. Sorry for my ignorance, if I am doing any wrong understanding. I am new to this Node.js.

Please guide me on this front.

**Comment by patrickjuchli** [comment]
@psr1410, this is not a forum. You are doing the same thing again as in #110.

The code you posted above doesn't look anything like the answer in the stackoverflow post that I've searched for you on Google. Again, you're not calling `done` and the function is marked `async`, both of which are wrong.

I will now close this issue. Please stop opening issues as soon as you hit a problem with your program. Open an issue when you can prove that there is a bug in this library.

**Comment by psr1410** [comment]
Sorry @patrickjuchli . I will check from my end and get back to you.
