### ISSUE TITLE
'close' event is not handled when using streams

### ISSUE THREAD

**Issue by ct0r** [patrickjuchli/basic-ftp#115]
Hi, thanks for the great lib!

When I use `downloadTo(writableStream, ...)`I am not able to signal back that I don't need more data as 'close' stream event is ignored. Is it intentional? Is there a correct way to stop a download?

Thanks.

**Comment by patrickjuchli** [comment]
The way to stop anything right now is to just `client.close()`, and then access the server again if necessary. This situation can be improved of course.

In your case, what exactly is happening after you close the stream? An exception should be thrown by the client, is this true?

**Comment by hepking** [comment]
nodejs 10+,  dataSocket.readyState == 'closed' , sometime,  no catch!

**Comment by hepking** [comment]
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 10:12. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
Login security: No encryption
> USER hcms
< 331 User hcms OK. Password required
> PASS ###
< 230 OK. Current directory is /
> TYPE I
< 200 TYPE is now 8-bit binary
> STRU F
< 200 F OK
> OPTS UTF8 ON
< 200 OK, UTF-8 enabled
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
Trying to find optimal transfer strategy...
> EPSV
< 229 Extended Passive mode OK (|||24003|)
Optimal transfer strategy found.
> MLSD /wd/app
< 150 Accepted data connection
226-Options: -a -l 
226 4 matches total
list e:{}  《---  this error，no more infomation

**Comment by hepking** [comment]
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 10:18. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
Login security: No encryption
> USER hcms
< 331 User hcms OK. Password required
> PASS ###
< 230 OK. Current directory is /
> TYPE I
< 200 TYPE is now 8-bit binary
> STRU F
< 200 F OK
> OPTS UTF8 ON
< 200 OK, UTF-8 enabled
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
Trying to find optimal transfer strategy...
> EPSV
< 229 Extended Passive mode OK (|||25819|)
Optimal transfer strategy found.
> RETR /wd/defines.php
< 150 Accepted data connection
226-File successfully transferred
226 0.000 seconds (measured here), 21.54 Mbytes per second
----- stopped ------

**Comment by ct0r** [comment]
Nothing happen when I close given stream because 'close' event is ignored. I have to close client and handle the error (client closed during operation) or wait for time-out. This can be really annoying when you want to access multiple files and read only first line etc..

I believe the right way is to handle 'close' event emitted by given stream and let people use client for other operations..

**Comment by patrickjuchli** [comment]
This is not easy to add to the library right now and your use-case is rather specific. I'd urge you to find another transfer protocol – FTP is not made for this. 

That being said, it would be good to support something like that. Will keep this open.

**Comment by patrickjuchli** [comment]
Picking this up from way back: Do you experience the same issues with version >= 5.0.0?

**Comment by patrickjuchli** [comment]
Should be addressed in >= 5.0.0, see unit test here https://github.com/patrickjuchli/basic-ftp/blob/8845f46f342372b7119bc54873faa02d336f3c97/test/downloadSpec.js#L86
