### ISSUE TITLE
How can I handle the error "Error: self signed certificate"?

### ISSUE THREAD

**Issue by ilclaudio** [patrickjuchli/basic-ftp#116]
Hi,
I'm able to connect using an ftp client to an ftp server using the option "tls/ssl encryption explicit".

Basic-ftp gives me the error:
`{"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)`

How can I handle this error?
Am I missing some option?

Thank you

Claudio

**Comment by patrickjuchli** [comment]
Your certificate has been self-signed and thus your endpoint can't be verified. You can disable verification as documented here: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback. Be aware that this disables half of what TLS does and your connection is not really secure anymore.

```
await client.access({
  host: "myftpserver.com",
  user: "very",
  password: "password",
  secure: true,
  secureOptions: { rejectUnauthorized: false }
})
```

This will disable verification of your endpoint

**Comment by ilclaudio** [comment]
Yes, thank you I can confirm that in this way works.
Thank you.
