### ISSUE TITLE
MLSD instead of LIST -a causes "402 Command not allowed" error

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#117]
**Describe the bug**
When using `basic-ftp@3.8.7` the `list()` command worked fine.  However when we upgraded to `basic-ftp@4.5.1`, it started failing with `FTPError: 402 Command not allowed` errors.

Based on the console output below, this appears to be because v4 uses `MLSD` instead of `LIST -a`, which the `ftp-srv` module (the server we're connecting to) doesn't support.

Is there a way to force basic-ftp to prefer `list -a`?  Or can it auto-detect that `MLSD` isn't supported and fallback to `list -a`?

**Example code**
Sorry, don't have this at the moment, but hopefully the console output below makes it pretty clear what's going on.  Moreover, I was able to verify that MLSD isn't supported on the `ftp-srv` server by telneting directly to the server and issuing HELP/MLSD commands:
```
$ telnet pi 21
Trying [ip redacted]...
Connected to pi.
Escape character is '^]'.
220-Welcome to the Fanuc proxy
220 Features: a .

HELP
211-Supported commands:
211-ABOR	ALLO	APPE	AUTH	CDUP
211-XCUP	CWD	XCWD	DELE	FEAT
211-HELP	LIST	MDTM	MKD	XMKD
211-MODE	NLST	NOOP	OPTS	PASS
211-PASV	PORT	PWD	XPWD	QUIT
211-REST	RETR	RMD	XRMD	RNFR
211-RNTO	SITE	SIZE	STAT	STOR
211-STOU	STRU	SYST	TYPE	USER
211-PBSZ	PROT	EPRT	EPSV
211 Use "HELP [command]" for syntax help.

MLSD
402 Command not allowed
```

**Console output**
Output when running `list()` for v3:
```
> EPSV
< 229 EPSV OK (|||43211|)
> LIST -a
< 150 File status okay; about to open data connection
Downloading from 10.11.12.111:43211 (No encryption)
< 226 Closing data connection
-r-xr-xr-x 1 1 1            0 Dec 18 03:32 -bcked2-.ls
[... rest of file list clipped...]
```
Outuput when running list() for v4:
```
> EPSV
< 229 EPSV OK (|||43245|)
> MLSD
< 402 Command not allowed
Channel.js:44 [d344b549] ERROR /robots/d829c919-12bf-42ef-98c9-60b19e54335a/raw
Channel.js:45 402 Command not allowed
```

**Which version of Node.js are you using?**
Node 12.10.0

**Comment by broofa** [comment]
Ah, found [availableListCommands](https://github.com/patrickjuchli/basic-ftp/blob/f008b8b5cafb65a312d3733d5f52b1b429bfc9f8/src/Client.ts#L58-L68).  Looks like I overriding it as follows fixes the problem:
```
ftp.availableListCommands = ['LIST -a', 'LIST'];
```

Leaving this open to see if there's a more preferred way of dealing with this issue.

**Comment by patrickjuchli** [comment]
FTP error codes 4xx are usually for transient errors, see [Wiki](https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes): "[...] the user-process is encouraged to try again.". That's why this library thinks the error refers to something else than an unknown command. If a server doesn't support MLSD it typically returns an 5xx erroy code which will be handled correctly here and the next listing command will be attempted.

But this is FTP, what is all this talk about standards.

When attempting to issue different list commands I could regard just any error to refer to unknown command. Will look into it.

**Comment by patrickjuchli** [comment]
@broofa Improving the world one step at a time? Thanks for raising the issue.

**Comment by patrickjuchli** [comment]
In 4.5.2, error codes 4xx won't abort the process of finding a compatible list command anymore. This should fix your issue.

You can also continue using `availableListCommands`. This remains undocumented API for now, but API that is marked public in Typescript won't change.
