### ISSUE TITLE
Resume file transfers after connection issues

### ISSUE THREAD

**Issue by patrickjuchli** [patrickjuchli/basic-ftp#124]
Based on the issue here https://github.com/patrickjuchli/basic-ftp/issues/123#issuecomment-573421466, it might be helpful to offer automatic retries when file transfers fail due to connectivity issues.

This kind of functionality is not within the original scope of this library. `basic-ftp` takes care of the basics of FTP, things like retries have been left to the target audience of this library, developers. Reconsider this.

**Comment by pablocar80** [comment]
+1
Some FTP programs like Filezilla have a built-in mechanism to retry several times operations that fail, and it's really helpful.

**Comment by a-tonchev** [comment]
@patrickjuchli : From my side it is totally ok if I handle the reconnects. But the problem is that I can not continue the job where it stopped. For example if I am uploading 100 files via ftp, I uploaded 76, but the server connection get lost. I want to continue the job only for the 24 left. Is it possible right now to handle this? I think right now we have to restart the whole process?

**Comment by patrickjuchli** [comment]
I understand the need for this. But I ask you to understand this: I'm not aware of a any FTP library anywhere that offers that built-in. There is a reason for that: It's not an FTP _library_ concern. `basic-ftp` is not the equivalent to Filezilla, it's not an  _application_.

This library offers everything you need, to write software that resumes file transfer. Some inspiration: All files to be uploaded are represented by some task object in an array. Your program then uses that array to upload. If something succeeds you mark it as such in the array. If there is an error, you resume work on your task array. This library also lets you continue uploading to a partially uploaded file. So when resuming, query the file size on the server (also provided by this library), and continue uploading at that offset.

**Comment by a-tonchev** [comment]
@patrickjuchli Actually there are some libraries that offer this already:

I am using right now ftp-deploy:

https://www.npmjs.com/package/ftp-deploy

The thing is, I really like simple things like your library, but the only draw-back now is missing "continue" for the job when ftp stops suddenly.

`All files to be uploaded are represented by some task object in an array.`

Do I need to read all files from a directory and pass them in a for-loop to the ftp? Can you give simple example how to send array of files during one connection without the need to create new connection for each file? Sorry, maybe I just did not find a way to reach this.

**Comment by patrickjuchli** [comment]
`ftp-deploy` is not an FTP library. It uses `promise-ftp` which in turn uses `@icetee/ftp` which is a fork of`node-ftp`. `basic-ftp` is a library like `(node-)ftp` or `@icetee/ftp` or `jsftp` and none of these implement the feature described here.

Much like the maintainer of `ftp-deploy`, you could write a package that does the same thing but uses `basic-ftp` underneath. There is a reason why these things are in separate libraries because they address different concerns.

I understand though that many people like you use this library as an application or tool, not as a _library_ to use in their own application. My target audience was people writing something like `ftp-deploy`. But I understand that I might have been mistaken about that.

**Comment by a-tonchev** [comment]
@patrickjuchli thank you very much for this clarification. Well, when I have some free capacity I will make a function with reconnect. 

It should do basically the same like client.uploadFromDir("my/local/directory")

Just with an list of fiels and index and maxReconnectCount.

**Comment by patrickjuchli** [comment]
Will close this because after all the time that passed there are still no plans to implement this in basic-ftp, sorry.
