### ISSUE TITLE
Is possible to abort or force a stop?

### ISSUE THREAD

**Issue by gv-beemining** [patrickjuchli/basic-ftp#127]
Hi:

Im tryng to download a large file from an old FTP, sometimes the connection hangs even if the file is already fully downloaded, so im tryng to force the close of the connection but is not working:

```
  downloadFile: async (filename, writeStream) => {
    const client = new ftp.Client(timeout = 10000);
    client.ftp.verbose = false;
    try {
      await client.access(credentials);
      await client.cd(sourcePath);
      const fileSize = await client.size(filename);
      client.trackProgress(async (info) => {
        console.log("File", info.name)
        console.log("Type", info.type)
        console.log("Transferred", info.bytes)
        console.log("Transferred Overall", info.bytesOverall)
        //fix for large files
        if (info.bytesOverall == fileSize) {
          writeStream.destroy();
        }
      });
      await client.downloadTo(writeStream, filename);
    } catch (e) {
      console.log(e);
    }
  }

```
if gives me this error: Error: Timeout (control socket)

and with client.close() i get: User closed client during task

is there a workaroud to avoid throwing an error?

Thanks!

**Comment by patrickjuchli** [comment]
Closing a client while something is still ongoing will always result in an exception. You can wrap the call to `close()` in a dedicated try-catch-block, though, to ignore any exception as a result from closing the client.

**Comment by gv-beemining** [comment]
Thanks for the fast response,  i tried but the try / catch block is never reached

```
  downloadFile: async (filename, writeStream) => {
    const client = new ftp.Client(timeout = 10000);
    client.ftp.verbose = false;
    try {
      await client.access(credentials);
      await client.cd(sourcePath);
      const fileSize = await client.size(filename);
      client.trackProgress(async (info) => {
        console.log("File", info.name)
        console.log("Type", info.type)
        console.log("Transferred", info.bytes)
        console.log("Transferred Overall", info.bytesOverall)
        //fix for large files
        if (info.bytesOverall == fileSize) {
      try {
            client.close();
          } catch (e) {
            console.log('custom error');
            console.log(e);
          }
        }
      });
      await client.downloadTo(writeStream, filename);
    } catch (e) {
      console.log(e);
    }
  }
```

**Comment by patrickjuchli** [comment]
This issue is about the question if you can stop a transfer. You can do that by closing the client. This will raise an exception, that's just how this library works.

In your last comment you write that the try-catch-block is not being reached. For me this discussion is now more about your specific programming issue. If your try-catch-block is not reached, that means that `info.bytesOverall` never equals `fileSize`? So what are possible values, did you log them to the console?

**Comment by gv-beemining** [comment]
yep i fixed now it reaches the try/catch block but the downloadTo function never completes so the after downloadTo is never executed:

```
  downloadFile: async (filename, writeStream) => {
    const client = new ftp.Client(timeout = 10000);
    client.ftp.verbose = false;
    try {
      await client.access(credentials);
      await client.cd(sourcePath);
      const fileSize = await client.size(filename);
      client.trackProgress(async (info) => {
        console.log("File", info.name)
        console.log("Type", info.type)
        console.log("Transferred", info.bytes)
        console.log("Transferred Overall", info.bytesOverall)
        //fix for large files
        if (info.bytesOverall == fileSize) {
	 console.log('inside if');
          try {
            console.log('inside try');
            client.close();
          } catch (e) {
            console.log('custom error');
            console.log(e);
          }
        }
      });
      await client.downloadTo(writeStream, filename);
      conssole.log('after downloadTo');
    } catch (e) {
      console.log(e);
    }
  }
```

**Comment by patrickjuchli** [comment]
But you do reach the end of your function `downloadFile`, right? Add a log statement on the very last line. You should reach that. The log statement `after downloadTo` is not reached because of the exception.

**Comment by patrickjuchli** [comment]
This ticket can be closed, right? It has been answered and the rest were implementation-specific questions.
