### ISSUE TITLE
Upload hangs using readable streams

### ISSUE THREAD

**Issue by adamsoutar** [patrickjuchli/basic-ftp#128]
Hi,

I've been trying to use the `memory-streams` npm package to upload and download strings from my FTP server, and downloading works fine.

However, when my upload code is:
```js
async uploadFileString (remotePath, str) {
  const stream = new streams.ReadableStream(str)
  await this.client.uploadFrom(stream, remotePath)
}
```
It hangs. The output with verbose set to true is:

```
> PASV
< 227 Entering Passive Mode (91,208,99,4,63,56)
> STOR /public_html/ecom/index.html
< 150 Accepted data connection
Uploading to 91.208.99.4:16184 (No encryption)
Error: Timeout (data socket)
    at Socket.<anonymous> (/Users/adam/Documents/Mac Projects/e-commerce/deploy-site/node_modules/basic-ftp/dist/FtpContext.js:310:58)
    at Object.onceWrapper (events.js:411:28)
    at Socket.emit (events.js:305:20)
    at Socket._onTimeout (net.js:477:8)
    at listOnTimeout (internal/timers.js:537:17)
    at processTimers (internal/timers.js:481:7)
```

If I change it to:
```js
async uploadFileString (remotePath, str) {
  await fs.writeFile('./temp.txt', str)
  await this.client.uploadFrom('./temp.txt', remotePath)
}
```

It uploads just fine in almost no time.

I don't think there's any problem with the stream, because `stream.pipe(process.stdout)` prints the string just fine.

**Comment by patrickjuchli** [comment]
Does your readable stream signal that it has ended? The upload function waits until a readable stream does so. 

Try fs.createReadStream() for an example.

**Comment by patrickjuchli** [comment]
Reading https://github.com/paulja/memory-streams-js/blob/master/lib/ReadableStream.js, memory-streams is quite the thin abstraction over ReadableStream and doesn‘t signal an end. Looks to like you need to call `stream.append(null)`. Null signals the end of a stream.
