### ISSUE TITLE
RangeError: Invalid time value at Date.toISOString ()

### ISSUE THREAD

**Issue by sstonemen** [patrickjuchli/basic-ftp#129]
**Describe the bug**
Read ftp directory throw error:
RangeError: Invalid time value at Date.toISOString ()
from row 18 in /basic-ftp/dist/parseListMLSD.js

**Which version of Node.js are you using?**
node/12.13.1

**Additional context**
Read dir from a linux system (with proftpd service).
Error only occur sometimes even with the same ftp account. I think the directory is to big (100,000+ files) and maybe sometimes a timeout produce wrong data.

The problem of RangeError is a 'undefined' input to the Date.toISOString function.

Short solution to fix:
/basic-ftp/dist/parseListMLSD.js (row 177 in file) in function parseMLSxDate(fact)
Insert code: if (isNaN(fact)) return new Date()

I think it is better to return a wrong date, instead of break the whole ftp-access as a result of some ftp issues. 
The better way is to return a empty value for 'rawModifiedAt' .

**Comment by patrickjuchli** [comment]
Interesting, can you provide more details? Do you have a log output using `client.verbose =true` that maybe shows the entries that cause problems?

Right now it still sounds like "sometimes the FTP server sends the wrong (invalid) date for a file". Not sure yet how to handle something like that.

**Comment by sstonemen** [comment]
I logged the parseMLSxDate() value and found after some runs this value:
20191202065119:size=1627082

The rawModifiedAt value and the size value not delimit the right way?

**Comment by patrickjuchli** [comment]
Yes, looks like it. The `:` should be `;`, very strange that this only happens sometimes. Would be interesting to see the whole line that contains the string you posted. Do you think you can get it?

A typical MLSD line for a file looks like this: `type=dir;modify=20190218120006;size=11;  fileName`

**Comment by patrickjuchli** [comment]
I'm not sure my last post was clear: This looks like malformed data coming in. It should use `;` but uses `:`. If we can get an example of the whole surrounding line describing the file we can go over to the proftpd repository and file bug.

**Comment by sstonemen** [comment]
Example output from:
function parseLine(line) {
    console.log(line) 


**3 lines. The second is with a ':' after 'type=file'**

```
modify=20180109093900;size=12079847;type=file;unique=FD00UE5263C1;UNIX.group=1001;UNIX.mode=0755;UNIX.owner=1001; filename1.mp4

modify=20181115075800;size=5128287;type=file:unique=FD00UE52C8F4;UNIX.group=1001;UNIX.mode=0755;UNIX.owner=1001; filename2.mp4

modify=20190412082300;size=2654;type=file;unique=FD00UE52EF8D;UNIX.group=1001;UNIX.mode=0755;UNIX.owner=1001; filename3.mp4

```

Other example after 'UNIX.group=1001'
`modify=20140320230000;size=1149;type=file;unique=FD00UE523419;UNIX.group=1001:UNIX.mode=0755;UNIX.owner=1001; filename4.mp4`


Because it occur max 1 time per line I fix it with this code:
file: parseListMLSD.js
function parseLine(line) {
   if (line.slice(0, line.lastIndexOf(";")).indexOf(":") != -1) line = line.replace(/:/g, ";");

Work well.

**Comment by patrickjuchli** [comment]
Wow, great work. You should open an issue at https://github.com/proftpd/proftpd. I don't see yet how this is an issue with this library.

**Comment by patrickjuchli** [comment]
Let me know if you need help opening the issue on proftpd. Do you know which version of proftpd you're using?

**Comment by patrickjuchli** [comment]
@sstonemen, what's the status here?

**Comment by sstonemen** [comment]
Hi, thank you for your help.
For me the problem is solved with
https://github.com/patrickjuchli/basic-ftp/issues/129#issuecomment-586584568

Open a issue for proftpd is not mandatory, because my version is from a CentOS System (ProFTPD Version 1.3.5e) and is not the last minor version.
