### ISSUE TITLE
Add functions to move file/directory 

### ISSUE THREAD

**Issue by elpeleq42** [patrickjuchli/basic-ftp#13]
Please add a function to move file/directory, inside the ftp, to another directory

**Comment by patrickjuchli** [comment]
Do you want to give it a try and submit a pull request?

**Comment by elpeleq42** [comment]
You mean try a new function you made to do this and submit or you're saying I didn't test your module/npm ?

**Comment by elpeleq42** [comment]
I suppose since I want to use this free tool in my project, the least I could do is try to help improving it.

But as far as I see, moving files inside ftp must be a complex task, since I couldn't find another npm/module for node that can do that. I will take some time researching before answer.

Would renaming the file path work?I don't know exactly how to do this in javascript, but other languages/libs/programs seems to use that method

**Comment by patrickjuchli** [comment]
Yes, it's renaming. I can imagine that some servers can't rename/move whole paths but most seem to be able to.

**Comment by patrickjuchli** [comment]
@elpeleq42, please let me know if you intend to work on this or not.

**Comment by elpeleq42** [comment]
Sorry for leaving you in the dark.

I can't work on this right know. College takes too much of my time and energy. I'm really sorry.

**Comment by patrickjuchli** [comment]
Added in 662abfde7a3c71f0b1fb7981b99447e83ac015db, will be part of next release.
