### ISSUE TITLE
[QUESTION] Download latest file from folder

### ISSUE THREAD

**Issue by SiliconMachine** [patrickjuchli/basic-ftp#130]
I have a folder in which a file is created every two hours with a random UUID as a name so it's quite difficult to guess what is the file name. 
There is any way to download the latest uploaded file?

**Comment by patrickjuchli** [comment]
The FTP protocol doesn't offer a direct method to do this. Did you try getting the directory listing? If your server provides machine-readable modification timestamps you can find your file that way.

**Comment by SiliconMachine** [comment]
@patrickjuchli Thank you. The list returns an array of objects where I can just take the object in the position **list.length - 1** and as it ordered by date, it just works.

Have a nice day!
