### ISSUE TITLE
No errors when server instantly closes connection

### ISSUE THREAD

**Issue by davidsky** [patrickjuchli/basic-ftp#138]
**Describe the bug**
No errors when server closes connection immediately.
Using linux's **ftp** command:

```
root@server:~# ftp -v -t -d -4 domain.com 21
Connected to domain.com.
421 Service not available, remote server has closed connection
```

Using basic-ftp, verbose prints "Connected to domain.com." and then the program ends. No timeout or other errors.

**Example code**
Copy-paste example code from readme.

**Which version of Node.js are you using?**
Tried 12.8.0, 12.7.0, and 12.16.1 on Mac laptop, and latest Ubuntu server

**Additional context**
Remote server isn't mine. It seems error 421 is due to some sort of account block, or usage abuse.

**Comment by davidsky** [comment]
Adding a global timeout, and not allowing the process to die, and then printing the client object, shows that basic-ftp did catch an internal error (see below), but it did not throw/bubble it up.

await client.access({}) is wrapped in try/catch, but nothing is caught.

`
Client {
  availableListCommands: [ 'MLSD', 'LIST -a', 'LIST' ],
  ftp: FTPContext {
    timeout: 10000,
    verbose: 1,
    ipFamily: 4,
    tlsOptions: {},
    _partialResponse: '',
    _encoding: 'utf8',
    _dataSocket: undefined,
    _closingError: undefined,
    _socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ftp.rakuten.ne.jp',
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 10000,
      _peername: [Object],
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 9,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 178,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 12,
        [Symbol(triggerId)]: 1
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _task: {
      stack: 'Error\n' +
        '    at /var/www/node_modules/basic-ftp/dist/FtpContext.js:201:27\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at FTPContext.handle (/var/www/node_modules/basic-ftp/dist/FtpContext.js:200:16)\n' +
        '    at Client.connect (/var/www/node_modules/basic-ftp/dist/Client.js:78:25)\n' +
        '    at Client.access (/var/www/node_modules/basic-ftp/dist/Client.js:186:36)\n' +
        '    at getClient (/var/www/api.tenki-japan.co.jp/__common/ftp/test.js:45:16)\n' +
        '    at list (/var/www/api.tenki-japan.co.jp/__common/ftp/test.js:90:19)\n' +
        '    at /var/www/api.tenki-japan.co.jp/__common/ftp/test.js:330:22\n' +
        '    at Object.<anonymous> (/var/www/api.tenki-japan.co.jp/__common/ftp/test.js:348:3)\n' +
        '    at Module._compile (internal/modules/cjs/loader.js:1158:30)',
      resolver: [Object],
      responseHandler: [Function]
    }
  },
  prepareTransfer: [AsyncFunction],
  parseList: [Function: parseList],
  _progressTracker: ProgressTracker {
    bytesOverall: 0,
    intervalMs: 500,
    onStop: [Function: noop],
    onHandle: [Function]
  },
}
`

**Comment by patrickjuchli** [comment]
The client doesn't catch any error, you'd see this in ftp._closingError. The stack you see below is just a snapshot of the stack to be used later, if there is an error.

This is very strange, I don't know what exactly is happening. In the console, you don't see anything else after `Connected to domain.com.`?

**Comment by davidsky** [comment]
Yes, absolutely nothing after "**Connected to domain.com**" - program just ends. I temporarily solved this by wrapping client.access() in a timeout+promise. In case anyone needs it:

```
( async () => {

	// ...
	const connectionTimeout = 1000 * 10
	let client = new ftp.Client(connectionTimeout)

	await new Promise(resolve => {
		let resolved = false

		const timeoutId = setTimeout(() => {
			resolved = true
			if (client.close) client.close()
			resolve()
		}, connectionTimeout + 1000)

		return client.access(ftpAcces).then(msg => {
			clearTimeout(timeoutId)
			resolve()
		}).catch(error => {
			if (resolved) return
			console.error('ftp access error', error)
		})
	})

	// ...
	
})()
```

**Comment by patrickjuchli** [comment]
There is a new version 4.5.4, how does this work for you?

**Comment by davidsky** [comment]
New patch solves the issues. I'm now seeing "Error: Server closed connection.".

If you don't need any further tests from my side, issue can be closed :)
