### ISSUE TITLE
stream support

### ISSUE THREAD

**Issue by tugrul** [patrickjuchli/basic-ftp#139]
Return `ReadableStream` instead of take `WritableStream` is better approach on file download because we can transform the data in the download progress. jsftp library's sample https://github.com/sergi/jsftp#ftpgetremotepath-callback

In other case we have to use 3rd party library like https://www.npmjs.com/package/stream-buffers

**Comment by patrickjuchli** [comment]
Streams are supported, the title is a bit misleading.

This is a bit of a duplicate, there have been discussions about this, see #47 or #58. Usability is not a problem, here is an example downloading from one server, applying zlib compression and uploading to another one concurrently: https://github.com/patrickjuchli/basic-ftp/issues/58#issuecomment-46647768

**Comment by tugrul** [comment]
Offered ways are antipattern and also not safe. Traditional piping not handles errors and writable stream can hang on error and this cause leaks.

node.js has a function to solve this issue. https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback
