### ISSUE TITLE
Help: stream .json content > edit > save changed .json content

### ISSUE THREAD

**Issue by menix1337** [patrickjuchli/basic-ftp#141]
Hey!

First of all - **amazing** thing you created here! 
I've been dealing with some issues (maybe due to me being stupid) i have no idea how to solve.

**So thing is;**

Code here: 
https://www.codepile.net/pile/nEDvnKqe

1. I wanna open a .json file through a stream (reading the contents in it)
the steamid bit is found from a input so that may be different

2. I have some data i wanna set in with the file.set ( https://www.npmjs.com/package/edit-json-file ); if possible.

3. once file.save() has occured and data is set (Or in case we need another solution to push in data) 

Then I'd want it to update the original file in (we opened in 1.)
And close the connection

I've tried to look around here on the basic-ftp issues list, as well as doing some different solutions.. However, i couldn't really find a solution to my thing.

I just wanna see if i can avoid first downloading the file to a local drive > change > upload it back .. By using the stream

Best wishes!
Jesper.

**Comment by menix1337** [comment]
I do have the solution of course working with downloading the FTP file to my bot, changing data & send the file back through FTP to remote dir.

I was just wondering if its possible to only stream data without actually downloading the file

**Comment by patrickjuchli** [comment]
I'm sorry but this tracker is for issues specific to the library, for example bugs. Sites like Stackoverflow are better suited to this kind of question.

Without this kind of focus, I'd be answering issues non-stop, I hope you understand.
