### ISSUE TITLE
does it work with `sftp`?

### ISSUE THREAD

**Issue by sibelius** [patrickjuchli/basic-ftp#142]
**Describe the bug**
I'm trying to connect to a `sftp` server

**Example code**
```jsx
const client = new ftp.Client()
client.ftp.verbose = true;
const response = await client.access({
      host,
      port,
      user,
      password,
      secure: true,
    });

console.log(await client.list());
```

**Console output**
```jsx
Connected to ***.***.****.**:**
< SSH-2.0-CerberusFTPServer_8.0
ftp err:  Error: Timeout (control socket)
    at Socket.<anonymous> (app/node_modules/basic-ftp/dist/FtpContext.js:315:58)
```

**Which version of Node.js are you using?**
node v14.2.0

**Additional context**
I've tried other commands, but it didn't worked

**Comment by patrickjuchli** [comment]
No, SFTP is file transfer over SSH. This library does FTPS which the secure version of FTP and is something entirely different. Confusing naming choices, I know.

**Comment by xnerhu** [comment]
@sibelius I recommend you my library [`qusly-core`](https://github.com/qusly/qusly-core), which supports both ftp and sftp seamlessly. It uses basic-ftp under the hood.

**Comment by Pixelime** [comment]
Hi All,
any update on this topic? Do you think basic-ftp will support SFTP in the future? 
Thanks!

**Comment by patrickjuchli** [comment]
The name SFTP seems to imply some similarity to FTP – unfortunately there is no similarity at all. These are completely different protocols, SFTP doesn't have anything to do with FTP. So the answer is still no.
