### ISSUE TITLE
Error: Timeout when calling client.list sometimes

### ISSUE THREAD

**Issue by answord** [patrickjuchli/basic-ftp#143]
**Source code**
* transfer.ts downloadTo function
```
 onConditionOrEvent(destination.destroyed || destination.writableFinished, destination, "finish", () => resolver.onDataDone(task))
```

**Describe the bug**
I can't found stream.Writable.writableFinished in node.js v10.15.3 Documentation, It's added in v12.6.0, so the destination.writableFinished is always been undefined in node.js v10.15.3. if the destination emit finish event before onConditionOrEvent, onDataDone callback will never be called.

**Example code**
let fileList = await client.list('/path');

**Which version of Node.js are you using?**
Node 10.15.3

**Comment by patrickjuchli** [comment]
Do you have an idea how to solve it?

**Comment by answord** [comment]
I think we can add a getWritableFinished function in StringWriter.ts, like this
```javascript
import { Writable } from "stream"

export class StringWriter extends Writable {

    protected buf = Buffer.alloc(0)

    _write(chunk: Buffer | string | any, _: string, callback: (error: Error | null) => void) {
        if (chunk instanceof Buffer) {
            this.buf = Buffer.concat([this.buf, chunk])
            callback(null)
        }
        else {
            callback(new Error("StringWriter expects chunks of type 'Buffer'."))
        }
    }

    getText(encoding: string) {
        return this.buf.toString(encoding)
    }

    getWritableFinished() {
        return this._writableState ? this._writableState.finished : false;
    }
}
```

in transfer.ts, use destination.getWritableFinished() instead of destination.writableFinished
```javascript
onConditionOrEvent(destination.destroyed || destination.getWritableFinished(), destination, "finish", () => resolver.onDataDone(task))
```

**Comment by patrickjuchli** [comment]
Interesting, thanks! But this only addresses directory listings, right? The same transfer function is used for downloading files as well.

Could you maybe tell me more about `_writableState.finished`, did you consult the Node.js source code? Is this already present since Node.js 8?

**Comment by answord** [comment]
Yes, `_writableState.finished` is already present since Node.js 8, I consulted the Node.js source code.

It's smallest change, so I don't think this change will affects downloading files. You can test it after you modify it.

**Comment by patrickjuchli** [comment]
Node v10 would also offer `streams.finished()` but this library should stay compatible with 8.

Found this here, though.

https://github.com/nodejs/node/blob/3e2a3007107b7a100794f4e4adbde19263fc7464/lib/internal/streams/end-of-stream.js#L28-L33

This should be backwards compatible. If we use that function instead of `destination.destroyed || destination.writableFinished` here:

https://github.com/patrickjuchli/basic-ftp/blob/15ac37f8b4432869f1d19517195d6c69eab71447/src/transfer.ts#L271

That would improve things for both downloading listings and files. What do you think?

**Comment by patrickjuchli** [comment]
4.6.0 should improve this, let me know if this works for you.

**Comment by bossi4ek** [comment]
Hello. 
I have some issue with `client.list()` when I try to use basic-ftp with FTP server on Windows (FileFilla Server)
I am using `prepareTransfer = ftp.enterPassiveModeIPv4`

It is my log from FileFilla:
`
> 230 Logged on
> TYPE I
> 200 Type set to I
> STRU F
> 200 Using file structure 'File'
> OPTS UTF8 ON
> 202 UTF8 mode is always enabled. No need to send this command.
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
> 200 MLST OPTS type;size;modify;
> CWD /d_obmen_ssd/app
> 250 CWD successful. "/d_obmen_ssd/app" is current directory.
> PASV
> 227 Entering Passive Mode (192,168,88,150,249,2)
> 421 Connection timed out.
`

Could you have any ideas?

**Comment by patrickjuchli** [comment]
Looks like the connection required for the directory listing can't be established. Can you post the whole log or tell me whether the IP in the beginning is the same as 192.168.88.50?

This looks like another issue than discussed here.

**Comment by answord** [comment]
@patrickjuchli 
It is worked fine in 4.6.1 for me, thanks!
