### ISSUE TITLE
client.list() - connection timed out

### ISSUE THREAD

**Issue by bossi4ek** [patrickjuchli/basic-ftp#145]
**Describe the bug**
Hello.
I have "Connection timed out" issue with client.list() when I try to use basic-ftp with FTP server on Windows (FileFilla Server)
I am using prepareTransfer = ftp.enterPassiveModeIPv4

**Example code**
`await client.list('/path');`

**Console output**
`
> Connected on port 2121, sending welcome message...
> 220-FileZilla Server 0.9.60 beta
> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
> 220 Please visit https://filezilla-project.org/
> USER admin
> 331 Password required for admin
> PASS *******
> 230 Logged on
> TYPE I
> 200 Type set to I
> STRU F
> 200 Using file structure 'File'
> OPTS UTF8 ON
> 202 UTF8 mode is always enabled. No need to send this command.
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
> 200 MLST OPTS type;size;modify;
> CWD /d_obmen_ssd/app
> 250 CWD successful. "/d_obmen_ssd/app" is current directory.
> PASV
> 227 Entering Passive Mode (192,168,88,150,249,2)
> 421 Connection timed out.
`

**Which version of Node.js are you using?**
e.g. Node 12.15.0

**Comment by bossi4ek** [comment]
Tanks for you quickly answer :)
I am not person who configured FTP server.
If I try to connect using FileZilla all works fine.

**Comment by patrickjuchli** [comment]
Is `421 Connection timed out` coming immediately after `227 Entering Passive Mode (192,168,88,150,249,2)`?
