### ISSUE TITLE
feat: connection listener

### ISSUE THREAD

**Issue by xnerhu** [patrickjuchli/basic-ftp#150]
Hello!

It would be nice to have a way to detect when connection is closed. Unfortunatly `client.ftp.socket.on('close')` doesn't work in the most cases.

API could look like `client.trackProgress`:

```ts
client.trackConnection(listener?: (connected: boolean) => void)
```

**Comment by patrickjuchli** [comment]
This is a topic that has been discussed here: #43 .

The basic question is: Why do you want to know that when you're not actually doing anything? As soon as you're interacting with the Client – doing something – you'll know by receiving an exception. And this exception you have to expect in your code anyway. Exceptions are the way that this library uses to report a problem. And if you're not currently doing anything, you'll receive the exception as soon as you try to do something again.

Offering listeners introduces a second way to report errors. It's a basic design principle of this library keep error reporting to a single path.

I also don't believe that FTP client users are ever interested in this either. They want to upload stuff, do things. If the connection was lost then the program (your program using this library) should simply reconnect. And it should do so as soon as the user actually wants to do something again, not before. It's mostly developers who think that showing the connection state is important.

**Comment by patrickjuchli** [comment]
On the other hand, I am interested in your use-case, sorry for stomping all over you. How would you use such functionality?

**Comment by xnerhu** [comment]
I get that this library needs to be as simple as possible, but I think there must be an option to listen for connection status.

Let's say you have an UI that displays connection status or you use a logger so that you know when exactly connection was closed.

**Comment by patrickjuchli** [comment]
I won't be adding that functionality, sorry.
