### ISSUE TITLE
Promise not returning after download completes for larger files

### ISSUE THREAD

**Issue by psr1410** [patrickjuchli/basic-ftp#156]
**Describe the bug**
The download stream working fine as expected for smaller files. But when I am downloading the larger files all the stream downloading completing but the downloadTo is not returning any promise and nothing is happening.

**Example code**
`filePath = "some file path"
var fileWriteStream = new stream.Transform();
fileWriteStream._write = async function (fileChunk, encoding, done) {
	//uploading the chunk to Azure storage
	//await uploadEachBlockToBlobStorage(fileChunk)
      done();
});

fileWriteStream.on('finish', function(){
	console.log('file download completed')
});

client.downloadTo(fileWriteStream, filePath).then( (response) => {
	if(response.code === 226){
		//comming all the blocks to Azure blob
	}else{
	//download failed
	}
}).catch( (er) => {
	//download error
});`

**Which version of Node.js are you using?**
node:12-alpine

**Additional context**
We are running in the Azure web app.  The file size is greater than 1GB. Initially, we got a control_socket timeout issue. It was resolved by setting `client.ftp.socket.setTimeout(0)`. But after that fix, we were not able to get any promise.

**Comment by patrickjuchli** [comment]
This is likely related to #170, reopen if you have any new insights.
