### ISSUE TITLE
Unexpected behaviour on 200 OK

### ISSUE THREAD

**Issue by MrBrocaster** [patrickjuchli/basic-ftp#157]
**Description**
When I'm trying to upload file, my FTP server provider software responds `250 Directory successfully changed.` on `PASV` and then only `227 Entering Passive Mode (92,53,68,202,39,116)`. At this moment PASV parses is getting confused, and throws an error. How can I fix? I have no really big experience with FTP for writing my own `prepareTransfer` function.

The code is simple calling:
```js
    await client.cd('project');
    await client.cd('usermedia');

    await client.uploadFrom(fileStream, name);
```

**Console output**
```
> CWD project
< 200 OK
> CWD usermedia
< 250 Directory successfully changed.
> PASV
< 250 Directory successfully changed.
Error: Can't parse response to 'PASV': 250 Directory successfully changed.
< 227 Entering Passive Mode (92,53,68,202,39,116)
```

**Comment by MrBrocaster** [comment]
Just noticed, that I'm getting `'200 OK'` on `CWD` and then `250 Directory successfully changed.` which is not expected as I see.

**Comment by patrickjuchli** [comment]
What's the FTP server? Usually there is some information in the output log just after connecting.

This looks like weird server behaviour to me. Can you paste all of your code including connecting to the server?

**Comment by MrBrocaster** [comment]
@patrickjuchli of course I am able to provide full log :) 
But this log was generated with my bugyfill as metioned above, so '200 OK' was ignored.
This is Selectel FTP interface, but is does not have English translation, maybe you could use Google Translate: https://kb.selectel.ru/docs/cloud-services/cloud-storage/ftp/how_to_use_ftp_interface/

```
2|backend  | Connected to 92.53.68.203:21 (No encryption)
2|backend  | < 220 Selectel FTP <-> Swift proxy.
2|backend  | > AUTH TLS
2|backend  | < 234 AUTH command ok. Expecting TLS Negotiation.
2|backend  | Control socket is using: TLSv1.2
2|backend  | Login security: TLSv1.2
2|backend  | > USER username
2|backend  | < 331 Please specify the password.
2|backend  | > PASS ###
2|backend  | < 230 Login successful.
2|backend  | > TYPE I
2|backend  | < 200 Switching to Binary mode.
2|backend  | > STRU F
2|backend  | < 500 Unknown command STRU
2|backend  | > OPTS UTF8 ON
2|backend  | < 200 UTF8 only
2|backend  | > OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
2|backend  | < 500 Unknown option
2|backend  | > PBSZ 0
2|backend  | < 200 UTF8 only
2|backend  | > PROT P
2|backend  | < 200 Whatever
2|backend  | > CWD project/usermedia
2|backend  | < 200 OK
2|backend  | < 250 Directory successfully changed.
2|backend  | > PASV
2|backend  | < 227 Entering Passive Mode (92,53,68,203,39,116)
2|backend  | > STOR 5170862252fbc490546138ce8fa73f84a8490ccf15f2f03da65f6ba0a89ec831.png
2|backend  | < 150 Using transfer connection
2|backend  | Uploading to 92.53.68.203:10100 (TLSv1.3)
2|backend  | < 226 Closing transfer connection
```

**Comment by patrickjuchli** [comment]
```
2|backend  | > CWD project/usermedia
2|backend  | < 200 OK
2|backend  | < 250 Directory successfully changed.
```

This is simply not a correct response from the server. Any 2xx response is positive and final. There is no second 2xx. Multi-line responses are possible but they look differently.

Seeing this...

```
2|backend  | > PROT P
2|backend  | < 200 Whatever
```

...doesn't instill a lot of confidence either, does it?

Sorry, I won't add a workaround for this. You can't just ignore "200 OK". I'm open to have another look if this behavior turns up to be more common.

**Comment by MrBrocaster** [comment]
So I can only tell, that clients like FileZilla does not havy any issues with this wrong response.

**Comment by MrBrocaster** [comment]
@patrickjuchli maybe you can help us with "workaround" idea?

**Comment by patrickjuchli** [comment]
Use another client or don't use FTP. I see your service offers S3 or simply REST, you could use those as well.
