### ISSUE TITLE
Getting Error: None of the available transfer strategies work

### ISSUE THREAD

**Issue by johnlaine1** [patrickjuchli/basic-ftp#160]
I am running a script on my local machine, trying to connect to a PLC that is on the same local network. I can connect to the PLC using FileZilla and it works fine. According to the PLC docs I am only able to use plain FTP (insecure)

Here is the relevant code:
```javascript
const FTPParams = {
  host: '192.168.0.201',
  user: 'XXXXX',
  password: 'XXXXX',
};
const localFilePath = 'work_orders.csv';
const remoteFilePath = '/SD1/Recipe/open_work_orders.csv';

const sendFileByFTP = async ({ localFilePath, remoteFilePath, FTPParams }) => {
  const client = new ftp.Client();
  client.ftp.verbose = true;

  try {
    await client.access(FTPParams);
    await client.uploadFrom(localFilePath, remoteFilePath);
  } catch (err) {
    console.log(err);
  }
  client.close();
};
```

**Console output**
![image](https://user-images.githubusercontent.com/1234575/90544094-7de98f00-e13b-11ea-8135-b2c386b8aa5f.png)

**Which version of Node.js are you using?**
Node 10.19.0

**Additional context**
I tried connecting to another remote server with ftp-basic and it worked fine. Any help is really appreciated.

**Comment by patrickjuchli** [comment]
Maybe your server doesn't support passive mode? It responds with "Invalid command" after both EPSV and PASV. FileZilla probably uses active mode automatically?

This library doesn't support active mode, sorry.

**Comment by johnlaine1** [comment]
Thanks for your response. I tried connecting with FileZilla with both passive and active mode and was able to connect to the PLC in both, so I don't think that's the problem.
Any other ideas or another library that I could try?

**Comment by patrickjuchli** [comment]
Sure, try https://github.com/mscdex/node-ftp, hasn't been updated in a while though.

**Comment by patrickjuchli** [comment]
Does Filezilla have a similar log history like the one above? If yes, that could be helpful to see what happened.

**Comment by johnlaine1** [comment]
This is what I'm getting from FileZilla:

![image](https://user-images.githubusercontent.com/1234575/90793006-098c2880-e2c0-11ea-8da7-93e3187fbf99.png)

The FTP server only allows 'plain FTP'

Here are my settings in FileZilla:

![image](https://user-images.githubusercontent.com/1234575/90793265-5f60d080-e2c0-11ea-9d18-4e32f0a6a00e.png)

I also tried both Active and Passive modes with FileZilla and it works either way
I tried node-ftp and jsftp and got a similar error message:

![image](https://user-images.githubusercontent.com/1234575/90793658-dac28200-e2c0-11ea-901a-8513756616b4.png)
