### ISSUE TITLE
Download Files from FTP, Process Them, and Upload Processed Files to FTP

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [patrickjuchli/basic-ftp#163]
**Describe the bug**
A clear and concise description of what the bug is. Did you rule out network issues? Do you encounter the same issue when using another FTP server?
I am making a system to use a cron job which repeats every minute to automatically download files from the FTP Input folder, process it, then upload it to the FTP Output folder. However, the processing step always runs AFTER the uploading step (according to the console.log). Is there any way I can make the processing step run BEFORE the uploading step?

**Example code**
```
async function readFromFTP() {
const client = new ftp.Client()
  client.ftp.verbose = true
  try {
    await client.access({
      host: ***, // FTP server
      port: ***,
      user: ***,
      password: ***,
      secure: false
    });
    console.log(await client.list());

    await client.ensureDir("remoteRoot\\IN");

    // Download from remote input folder to local input directory
    await client.downloadToDir("localRoot\\IN").then(() => { process() })

    // Upload from local to remote directory
    // Problem: "OUT" directory in the FTP server will be blank in the first run.
    // Evaluate Problem: might be because uploadFromDir runs before csvToXml()
    await client.ensureDir("..\\OUT");
    await client.uploadFromDir("localRoot\\OUT");
  }
  catch (err) {
    console.log(err)
  }
  client.close()
}

// cron job every minute
cron.schedule("* * * * *", function () {
  console.log("Running Cron Job");
  readFromFTP();
});
```

**Which version of Node.js are you using?**
e.g. Node v13.13.0

**Comment by patrickjuchli** [comment]
If your process doesn't also return a Promise and resolve it when it's really done, your async chain doesn't work.

I'm sorry but this tracker is for issues specific to the library, for example bugs. Sites like Stackoverflow are better suited to this kind of question.

Without this kind of focus, I'd be answering issues non-stop, I hope you understand.
