### ISSUE TITLE
get/set encoding is working as expected

### ISSUE THREAD

**Issue by katesun-roserocket** [patrickjuchli/basic-ftp#168]
I am trying to connect and perform a file listing with a customer's VAN's FTP server in which I need to change the encoding.

I followed the docs and set the encoding as follows:

```
const ftp = require('basic-ftp');

async function fileList(config) {
    const client = new ftp.Client();
    client.ftp.verbose = true;
    client.ftp.encoding = 'ascii';
    try {
        await client.access(config));
        const list = await client.list();
    } catch (e) {
        client.close();
        throw e;
    }
}
```

However, in the logging it doesn't appear to be setting the encoding and continues to execute `OPTS UTF8 ON`. Did some digging into the source code and saw that `Client` doesn't actually pass in the encoding option to `FTPContext`. The README appears to be incorrect since `client.ftp.encoding = 'ascii'` will not work. I'm not sure if I'm interpreting the docs incorrectly and if there is a way to set the encoding.

**Comment by patrickjuchli** [comment]
Setting `OPTS UTF8 ON` is not linked to the encoding setting, that is correct and should be addressed. 

However, I'm not sure what you mean by "[..] saw that Client doesn't actually pass in the encoding option to FTPContext." Setting `client.ftp.encoding` uses this code https://github.com/patrickjuchli/basic-ftp/blob/8ed3c24e56706a52653d862e61b57340dcbcb4e9/src/FtpContext.ts#L209-L214

The encoding is used for anything sent over the control socket, e.g. commands and when parsing a directory listing response, see https://github.com/patrickjuchli/basic-ftp/blob/8ed3c24e56706a52653d862e61b57340dcbcb4e9/src/Client.ts#L577

What is your exact problem? If you call `await this.sendIgnoringError("OPTS UTF8 OFF")` manually after connecting to the client, does it work?

**Comment by katesun-roserocket** [comment]
Oh thanks, I didn't notice `set encoding`. I saw that the `Client` constructor isn't passing in `encoding` to `this.ftp = new FTPContext(timeout)` and thought that was the issue.

The problem I'm running into is that the FTP server is throwing `451 LIST command invalid with TYPE binary` trying to do a file listing. I suspected it was due to encoding so I tried to set encoding to various types and unfortunately that didn't work.

This is the log:

```  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    Connected to xxxxx (No encryption)
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 220 CONNECT:Enterprise Gateway 2.0.02. 33 FTP Server ready...  11:21:15  11-25-2020
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    Login security: No encryption
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > USER xxxx
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 331 Password required for xxxxx.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > PASS ###
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 230 User xxxxx logged in. Session Id: 69840.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > TYPE I
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 200 TYPE Command okay.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > STRU F
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 200 STRU command accepted.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > OPTS UTF8 ON
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 500 OPTS command not understood.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 500 OPTS command not understood.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    Trying to find optimal transfer strategy...
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > EPSV
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 500 EPSV command not understood.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > PASV
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 227 PASV Entering passive mode (209,95,224,122,216,141).
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    Optimal transfer strategy found.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > MLSD
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 500 MLSD command not understood.
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > PASV
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 227 PASV Entering passive mode (209,95,224,122,216,148).
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    > LIST -a
  console.log node_modules/basic-ftp/dist/FtpContext.js:247
    < 451 LIST command invalid with TYPE binary.
```
I saw `OPTS UTF8 ON` continue to be executed and thought it was the encoding not being set but you've clarified that it's not related.

I tried `await this.sendIgnoringError("OPTS UTF8 OFF")` but that didn't work.

It's failing locally and on production however using the FTP CLI at pair.com which runs FreeBSD does succeed.

Using Node v14.11.0 on mac catalina locally, and on production using Node 10 on Docker running on 64bit Amazon Linux.

**Comment by patrickjuchli** [comment]
`451 LIST command invalid with TYPE binary` is something else, is this an older FTP server?

Try `await this.send("TYPE A")` after connecting, not sure if this library handles this correctly though. This is ASCII transfer mode which has a lot of quirks.

**Comment by patrickjuchli** [comment]
I'm closing this ticket due to inactivity. The original title is also not describing the situation here. Feel free to reopen if you have new insights.
