### ISSUE TITLE
Idle connection times out after 5 minutes 

### ISSUE THREAD

**Issue by devCronos** [patrickjuchli/basic-ftp#171]
I am having issues with the timeout while being idle. I am getting the "421 Timeout" from ftp.log if I don't execute any command for 5 minutes after connecting.

example code:
```
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
connection: FtpClient
const fileName = 'dummy.txt';
const file = createReadStream(fileName);
const remotePath = '/home/test';
await connection.ensureDir(remotePath);

await sleep(7 * 60 * 1000);
await connection.uploadFrom(file, `${remotePath}/${fileName}`);
```

This is the error thrown after 7 minutes in the console:
10:27:24 <<< Error: Client is closed
    at /Users/c/project/syndication/node_modules/basic-ftp/dist/FtpContext.js:227:29
    at new Promise (<anonymous>)
    at FTPContext.handle (/Users/c/project/syndication/node_modules/basic-ftp/dist/FtpContext.js:207:16)
    at FTPContext.request (/Users/c/project/syndication/node_modules/basic-ftp/dist/FtpContext.js:184:21)
    at Client.enterPassiveModeIPv6 [as prepareTransfer] (/Users/c/project/syndication/node_modules/basic-ftp/dist/transfer.js:11:27)
    at Client._uploadFromStream (/Users/c/project/syndication/node_modules/basic-ftp/dist/Client.js:381:24)
Closing reason: Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/Users/c/project/syndication/node_modules/basic-ftp/dist/FtpContext.js:125:56)
    at Socket.emit (events.js:208:15)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1161:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: '0'
}

And this is the log from ftp.log
12/17/2020, 10:20:23 -- Trying to find optimal transfer strategy... 

12/17/2020, 10:20:23 -- > EPSV 

12/17/2020, 10:20:23 -- < 229 Entering Extended Passive Mode (|||10383|)
 

12/17/2020, 10:20:23 -- Optimal transfer strategy found. 

12/17/2020, 10:20:23 -- > MLSD / 

12/17/2020, 10:20:23 -- < 500 Unknown command.
 

12/17/2020, 10:20:23 -- > EPSV 

12/17/2020, 10:20:23 -- < 229 Entering Extended Passive Mode (|||10505|)
 

12/17/2020, 10:20:23 -- > LIST -a / 

12/17/2020, 10:20:23 -- < 150 Here comes the directory listing.
 

12/17/2020, 10:20:23 -- Downloading from xxxxxx (No encryption) 

12/17/2020, 10:20:23 -- < 226 Directory send OK.
 

12/17/2020, 10:20:23 -- > CWD / 

12/17/2020, 10:20:24 -- < 250 Directory successfully changed.
 

12/17/2020, 10:20:24 -- > CWD home 

12/17/2020, 10:20:24 -- < 250 Directory successfully changed.
 

12/17/2020, 10:20:24 -- > CWD hindawi 

12/17/2020, 10:20:24 -- < 250 Directory successfully changed.
 

12/17/2020, 10:20:24 -- > CWD claudiu16 

12/17/2020, 10:20:24 -- < 250 Directory successfully changed.
 

12/17/2020, 10:20:24 -- > CWD test 

12/17/2020, 10:20:24 -- < 250 Directory successfully changed.
 

12/17/2020, 10:25:24 -- < 421 Timeout.
As you see it times out after 5 minutes

Also it seems like neither timeout nor ftp.socket.setKeepAlive do anything to solve this problem regardless of the values.

I am using v12.7.0, but I recall testing this on a couple more versions some months ago with the same result
        v10.19.0
        v12.2.0
->    v12.7.0
        v12.16.1
        v12.18.3

The thing that seems to solve this for me is adding a       
```
setInterval(async () => {
       await connection.cd('/');
      }, 4 * 60 * 1000);
```
but this is hacky and I was wondering if there's a better way.

**Comment by patrickjuchli** [comment]
Timeout settings refer to situations where you're actively doing something, not idle connections. Here, the FTP server is disconnecting you because you haven't been doing anything for five minutes. This is reasonable because why should you stay connected when you're not doing anything?

In general, you should connect, do some work, and disconnect. If you want to stay connected for whatever reason your application should handle any reconnect in case the server disconnected you. You can see a similar thing happening with FTP client applications – they tend to reconnect if necessary but only when you start doing something again.
