### ISSUE TITLE
Readable stream uploads but does not resolve

### ISSUE THREAD

**Issue by paulrobertlloyd** [patrickjuchli/basic-ftp#172]
**Describe the bug**

I am trying to upload a string of text. I have converted it into a readable stream, and am able to upload it to an FTP server, but the connection hangs, and the function does not resolve.

Possibly a duplicate of #8, but solution in thread wasn’t helpful – where would I `push(null)` to the `readableStream`?

**Example code**

```js
import ftp from 'basic-ftp';
import path from 'path';
import {Readable} from 'stream';

async createFile(filepath, content) {
  const {host, user, password} = this.options;
  const client = new ftp.Client();
  client.ftp.verbose = true;

  try {
    const dirname = path.dirname(filepath);
    const basename = path.basename(filepath);
    const readableStream = Readable.from(content, {
      encoding: 'utf-8'
    });

    await client.access({host, user, password, secure: true});
    await client.ensureDir(dirname);
    await client.uploadFrom(readableStream, basename);
  } catch (error) {
    throw new Error(error.message);
  }

  client.close();
}
```

**Console output**

```sh
Connected to ##.##.###.#:21 (No encryption)
< 220 (vsFTPd 3.0.3)

> AUTH TLS
< 234 Proceed with negotiation.

Control socket is using: TLSv1.3
Login security: TLSv1.3
> USER ###
< 331 Please specify the password.

> PASS ###
< 230 Login successful.

> TYPE I
< 200 Switching to Binary mode.

> STRU F
< 200 Structure set to F.

> OPTS UTF8 ON
< 200 Always in UTF8 mode.

> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 501 Option not understood.

> PBSZ 0
< 200 PBSZ set to 0.

> PROT P
< 200 PROT now Private.

> MKD www
< 550 Create directory operation failed.

> CWD www
< 250 Directory successfully changed.

> MKD test
< 550 Create directory operation failed.

> CWD test
< 250 Directory successfully changed.

> MKD _notes
< 257 "/home/username/www/test/_notes" created

> CWD _notes
< 250 Directory successfully changed.

Trying to find optimal transfer strategy...
> EPSV
< 229 Entering Extended Passive Mode (|||38221|)

Optimal transfer strategy found.
> STOR 2020-12-24-jeukk.md
< 150 Ok to send data.

Uploading to ##.##.###.#:38221 (TLSv1.3)
```

The connection then times out.

**Which version of Node.js are you using?**

Node v14.15.0

**Additional context**

Am I right in assuming the connection doesn't close because `basic-ftp` doesn’t know when the stream has ended/closed?

**Comment by patrickjuchli** [comment]
If I try `Readable.from("hello")` the upload works fine. If I use an empty string like `Readable.from("")` the upload gets stuck. Can you confirm this? Have you been uploading actual data?

**Comment by paulrobertlloyd** [comment]
Will investigate empty string, though content is saved to the server, so not sure if that’s it. However, I’m not using `downloadTo()` (I don’t need to save the file locally once it’s been uploaded); is that the only way to indicate an operation is complete?

**Comment by paulrobertlloyd** [comment]
A few things to note:

* Using `const readableStream = Readable.from('');` I get the following error:

  ```sh
  [Error: 4622093824:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:337:
   (control socket)] {
    library: 'SSL routines',
    function: 'ssl3_get_record',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
  ```

* Using `const readableStream = Readable.from('foo');` I get the error described in the original issue in that the connection times out:

  ```js
  Error: Timeout (control socket)
    at TLSSocket.<anonymous> (/Users/paulrobertlloyd/Sites/indiekit/packages/store-ftp/node_modules/basic-ftp/dist/FtpContext.js:316:58)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
  ```

  A file with content `foo` is uploaded, however. This is the content of that `readableStream`:

  ```js
  Readable {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _read: [Function: read],
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false
  }
  ```

* Adding `await client.downloadTo("bla.txt", "bla.txt")` after `uploadFrom` doesn’t stop the connection from hanging.

**Comment by patrickjuchli** [comment]
Any news here?

**Comment by paulrobertlloyd** [comment]
Just tested this again using v4.6.6, and still getting the same result:

```
Uploading to ##.##.###.#:54004 (TLSv1.3)
Error: Timeout (control socket)
    at TLSSocket.<anonymous> (/Users/paulrobertlloyd/Sites/indiekit/packages/store-ftp/node_modules/basic-ftp/dist/FtpContext.js:316:58)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

File uploads fine, but can’t seem to close the connection.

My code can be found here: https://github.com/getindiekit/indiekit/blob/3acda67e9144d5323f6e88ab2c807a6780a0153d/packages/store-ftp/index.js#L28-L53

**Comment by alexandr2134** [comment]
once you added your content into stream, try to add null value after. It did the trick for me.

```
const r = new Readable();
r._read = () => {};
r.push(buffer.toString('utf-8'), 'utf-8');
r.push(null);
```
after pushing null uploadFrom gets resolved

**Comment by paulrobertlloyd** [comment]
Oh, sounds like a potential means of solving this issue. Not quite sure how this fits in with my existing code, though:

https://github.com/getindiekit/indiekit/blob/3acda67e9144d5323f6e88ab2c807a6780a0153d/packages/store-ftp/index.js#L35-L53

Any clues?

**Comment by alexandr2134** [comment]
> @alexandr2134 Oh, sounds like a potential means of solving this issue. Not quite sure how this fits in with my existing code, though:
> 
> https://github.com/getindiekit/indiekit/blob/3acda67e9144d5323f6e88ab2c807a6780a0153d/packages/store-ftp/index.js#L35-L53
> 
> Any clues?

line 42.

try to replace it with this:
```
const readableStream = new Readable();
readableStream.push(content, 'utf-8');
readableStream.push(null);
```

OR just add following code at line 45:
`readableStream.push(null);`

the main idea is to have "falsy" value at the end of your readable stream.

**Comment by paulrobertlloyd** [comment]
So this worked, but I also needed to make my `content` string an array:

```js
const readableStream = Readable.from([content], { encoding: 'utf-8' });
readableStream.push(null);
```

So, that seems to work. But! I’m now getting [the error I was seeing when I was uploading an empty string](https://github.com/patrickjuchli/basic-ftp/issues/172#issuecomment-751307425):

```
[Error: 4622093824:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:337:
 (control socket)] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
```

🤪

**Comment by alexandr2134** [comment]
did you try this code ?

```
const readableStream = new Readable();
readableStream._read = () => {}; // redundant, but stream wants this function to be defined
readableStream.push(content, 'utf-8');
readableStream.push(null);
```

this exact code works fine for me. Can you try to simply copy/paste it (without modifying it) and check?
Replace your lines 42-44 with this.

**Comment by paulrobertlloyd** [comment]
@alexandr2134 Huh, weird. I thought I did try copying and pasting your code, but couldn’t get it to work. But trying again today, and it’s now working beautifully! Thanks for your help 👍
