### ISSUE TITLE
[Enchancement] File Created Date in list()

### ISSUE THREAD

**Issue by menix1337** [patrickjuchli/basic-ftp#174]
Hey there.

I noticed on recieving the File Information using client.list() it returns the following (left image).
![eNbfvMa](https://user-images.githubusercontent.com/17611705/105258891-9f372700-5b82-11eb-8339-57f2324b02c0.png)

As you noticed on the right, the file (Right image) seems to save a File creation date - however i am unsure if this is possible fetch this time through the list()

- If this isn't possible, is there a way to perserve original data from a file on transfer? (Ea, the creation/modification dates)

**Comment by patrickjuchli** [comment]
This is not supported with that kind of listing. Preserving is not possible either, you're downloading data into a new file on your computer.
