### ISSUE TITLE
Error: Server sent FIN packet unexpectedly, closing connection

### ISSUE THREAD

**Issue by focussing** [patrickjuchli/basic-ftp#175]
First of all, thank you for this great package!

**Describe the bug**
When I try to upload 6.491.986 bytes for 278 parts sometimes (about 4 of 10)  an error occurs:
`Error: Server sent FIN packet unexpectedly, closing connection`

```
......
Uploading to 37.97.129.155:30121 (No encryption)
5469808
5471562
< 226 Transfer complete

> EPSV
< 229 Entering Extended Passive Mode (|||30174|)

> STOR 22-create-mandate-subscription.php
< 150 Opening BINARY mode data connection for 22-create-mandate-subscription.php

Uploading to 37.97.129.155:30174 (No encryption)
5471562
5473407
< 226 Transfer complete

> EPSV
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/Users/raymond/stack/sites/simonebusscher/node_modules/basic-ftp/dist/FtpContext.js:125:56)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
**Example code**
```
const ftp = require("basic-ftp")
let config = {
    host: 'xxxxl',
    user: 'xxxxl',
    password: 'xxxxl',
    secure: false
};

uploadFiles();

async function uploadFiles() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        console.log('connecting to', config.host);
        await client.access(config);

        let remotePath = REMOTE_PATH + '/css';
        console.log('removing folder', remotePath);
        await client.ensureDir(remotePath);
        await client.clearWorkingDir();

        remotePath = REMOTE_PATH + '/js';
        console.log('removing folder', remotePath);
        await client.ensureDir(remotePath);
        await client.clearWorkingDir();

        console.log('uploading files from', LOCAL_PATH, 'to', REMOTE_PATH);
        client.trackProgress(info => console.log(info.bytesOverall));
        await client.uploadFromDir(LOCAL_PATH, REMOTE_PATH);
        client.trackProgress();
    }
    catch (err) {
        console.log(err)
    }
    client.close()
}
```

**Console output**
Use `client.ftp.verbose = true` to log every communication detail. Copy-paste the output of your console here. Make sure to redact IPs, URLs or passwords.

**Which version of Node.js are you using?**
v14.15.4

**Additional context**
When I use FileZilla to send over my /dist folder, it always works fine. No errors whatsoever.
The server runs on a shared hosting, Centos 7.

**Comment by patrickjuchli** [comment]
It's a bit difficult to compare this library to Filezilla. The latter does retry aborted transfers as far as I know while this library does not. So it's still possible that the same thing happened with Filezilla as well. Does Filezilla log these things somehow?

**Comment by focussing** [comment]
Good point!


Status:      	Mappenlijst van “xxx" ophalen...
Opdracht: 	TYPE I
Antwoord: 	200 Type set to I
Opdracht: 	PASV
Fout:         	Verbinding gesloten door server
Fout:         	Bestandsoverdracht mislukt
Status:      	Adres bepalen van xxx
Status:      	Verbinden met xx.xxx.xx.xxxx ...
Status:      	Verbinding gemaakt, welkomstbericht afwachten...
Status:      	Normale FTP is onveilig. Schakel over naar FTP via TLS.
Status:      	Ingelogd
Status:      	Upload xxx starten
Status:      	Mappenlijst van “xxx" ophalen...
Status:      	Bestandsoverdracht geslaagd: 217 bytes in 1 seconde overgedragen


Sorry it is in dutch...
So yes, it also happens with FZ.
Is there a way to incorporate such a behavior in the uploadFromDir command?

	await client.uploadFromDir(LOCAL_PATH, REMOTE_PATH);

Best regards, 
Mit freundlichen Grüßen,
Met vriendelijke groet,
Raymond Verbruggen

FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl <mailto:mail@focussing.nl> 
www.focussing.nl <http://www.focussing.nl/>

**Comment by patrickjuchli** [comment]
This is out of scope of the original intent of this library, see #124 .
