### ISSUE TITLE
Continue job when server fail

### ISSUE THREAD

**Issue by a-tonchev** [patrickjuchli/basic-ftp#178]
Sometimes I try to upload files with

`await client.uploadFromDir(sourcePath);`

But it might come some short connection error and disconnect. It would be nice if I could reconnect automatically and continue job there - where it stopped. Because right now 75% of the files are uploaded, and I need to create new connection and try again. 

I try it in FTP, not sftp.

Is there a such possibility?

Thanks a lot

**Comment by patrickjuchli** [comment]
Duplicate, see #124
