### ISSUE TITLE
Folder size is always 4096

### ISSUE THREAD

**Issue by jayanthsaikiran** [patrickjuchli/basic-ftp#181]
The folder size is always going to be 4096. 

I accessed the parent directory using  `await client.list()`. 
![code snippet](https://user-images.githubusercontent.com/46348137/108522999-6f9b4c00-72f3-11eb-85ab-a5b0855aad38.png)

Node 12.11.1

**Comment by patrickjuchli** [comment]
In FTP, `size` doesn't mean much when it comes to directories. You can't rely on this, every server will show slightly different behaviour because this is not part of any standard.
