### ISSUE TITLE
Request timeout error when deployed in heroku.

### ISSUE THREAD

**Issue by jayanthsaikiran** [patrickjuchli/basic-ftp#184]
It works like a charm when I am running the project in localhost. But when I deployed my project in Heroku it is showing a timeout error 503.

My code:

**FtpRoutes.js**

```
const Ftp = require('./ftpclient')

 router.get("/root",(req,res)=> {
    const rootclient = new Ftp("192.168.0.4", 2121, "ftp", "ftp");
    console.log('reached root method');
    rootclient.rootFolder().then((result) => {
        res.send(result);
    });
})
```

**ftpclient.js**

```
class FTPClient {
    constructor(host, port, username, password, secure = false) {
        this.client = new ftp.Client();
        this.path = '/'
        this.settings = {
            host: host,
            port: port,
            user: username,
            password: password,
            secure: secure
        };
    }

    // List operation
    async rootFolder() {
        let res = null
        try {
            res = await Lists.parentList(this.client, this.settings);
        }
        catch (err) {
            console.log(err);
        }
        return res;
    }
```

Heroku Log:

```
at=error code=H12 desc="Request timeout" method=GET path="/root" host=nowires.herokuapp.com request_id=5bbdc647-9f8e-4097-84a1-56e9612b8572 fwd="183.83.255.74" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

GET /root - - - - ms
 Error: Timeout (control socket)
 at Socket.<anonymous> (/app/node_modules/basic-ftp/dist/FtpContext.js:316:58)
 at Object.onceWrapper (events.js:421:28)
 at Socket.emit (events.js:315:20)
 at Socket._onTimeout (net.js:483:8)
 at listOnTimeout (internal/timers.js:554:17)
 at processTimers (internal/timers.js:497:7)
```

![image](https://user-images.githubusercontent.com/46348137/112136044-779d2300-8bf4-11eb-8dd4-c0053c86f963.png)

Note: It is working instantly when I am in localhost.

**Comment by mofux** [comment]
I'm pretty sure it's failing because the IP (192.168.0.4) won't be reachable from your Heroku host. The Heroku host is a public hosting and does not have access to your internal IP subnet.

**Comment by jayanthsaikiran** [comment]
> I'm pretty sure it's failing because the IP (192.168.0.4) won't be reachable from your Heroku host. The Heroku host is a public hosting and does not have access to your internal IP subnet.

Is there any solution to fix this issue ?

**Comment by mofux** [comment]
> Is there any solution to fix this issue ?

Your application's server must be able to communicate with the FTP server. If your application server is hosted on a network that has **no access** to the network of your FTP server then you either have to setup a VPN or Firewall rules to establish a communication between them.

Anyway, I think this is out of range for this bug tracker. You could look for community help on Stackoverflow or similar.

**Comment by jayanthsaikiran** [comment]
@mofux thanks, mate.

**Comment by jayanthsaikiran** [comment]
Please update, if you got any reference to solve this issue. Thanks

**Comment by patrickjuchli** [comment]
Don't use this issue tracker for problems unrelated to this library.

Your question seems to be why using "192.168.0.4" on a public server means something else than on your own computer. This is a question for e.g. Stackoverflow and I'm sure you'll get your answers there.
