### ISSUE TITLE
Uncaught (in promise) ReferenceError: Cannot access 'ftp' before initialization

### ISSUE THREAD

**Issue by p3im4n** [patrickjuchli/basic-ftp#185]
hi
I used basic-ftp to add ftp client feature to my web server I installed all my packages with ansible but at runtime I got some errors

my ansible playbook:

tasks:
  - name: Ensure the aPuppet installing on Ubuntu >= 16.04
    fail:
      msg: aPuppet need Ubuntu version 16.04 and later
    when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16)

  - name: Prepare Python 3
    import_tasks: tasks_python.yaml

  - name: Install required system packages
    apt:
      package:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - npm

      update_cache: yes
      state: latest

  - name: Install "basic-ftp" node.js package.
    community.general.npm:
     name: basic-ftp
     path: apuppet-server/web-admin/node_modules
     state: latest

  - name: Install "fs" node.js package
    community.general.npm:
     name: fs
     path: root/apuppet-server/web-admin/node_modules
     state: latest

  - name: Install "require" node.js package
    community.general.npm:
     name: require
     path: /root/apuppet-server/web-admin/node_modules
     state: latest
 

my usage in js file:

![js](https://user-images.githubusercontent.com/49278298/112259694-5a189980-8c86-11eb-900e-82b6daaaabbe.PNG)

 
my usage in html:
 
 
![html](https://user-images.githubusercontent.com/49278298/112259429-ed9d9a80-8c85-11eb-8ff8-15dd3cd23e6f.PNG)

but no connect happened(bases ftp log file )and in chrome I got this error:
Uncaught (in promise) ReferenceError: Cannot access 'ftp' before initialization

![chrome](https://user-images.githubusercontent.com/49278298/112258557-54ba4f80-8c84-11eb-99d7-b8057769b245.PNG)

**Comment by patrickjuchli** [comment]
And what does the editor say about the other error in that file, namely the first line?

I'm sorry but this tracker is for issues specific to the library, for example bugs. Sites like Stackoverflow are better suited to this kind of question.

Without this kind of focus, I'd be answering issues non-stop, I hope you understand.

**Comment by p3im4n** [comment]
hi Mr @patrickjuchli 
using basic-ftp is unrelative to this trucker???

> And what does the editor say about the other error in that file, namely the first line?
its not editor,its chrome browser!!!

> I'm sorry but this tracker is for issues specific to the library, for example bugs. Sites like Stackoverflow are better suited to this kind of question.

and may be its a bug too,the ansible.dock container,....I dont know....may be I should not use this library this way. I'll be appreciated if you help me.

best reagrds
