### ISSUE TITLE
Uncaught TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by jonhue** [patrickjuchli/basic-ftp#186]
**Describe the bug**

The following error is thrown upon importing `Client` from the library:

`Uncaught TypeError: The "original" argument must be of type Function`

**Example code**

The following code leads to the error:

```ts
import { Client } from 'basic-ftp'

const fn = async () => {
  const client = new Client()
  return client
}
```

The error is thrown immediately on load. So before `fn` is being called. In fact, I suspect the error would also occur if `fn` wasn't there at all but TS optimizes away the import of `Client` when it's unused or only used as a type.

The problem is resolved if I delete the following lines from `Client.ts`: https://github.com/patrickjuchli/basic-ftp/blob/master/src/Client.ts#L16-L22

**Which version of Node.js are you using?**
Node 15.8.0

**Comment by patrickjuchli** [comment]
I can't reproduce this, see https://replit.com/join/acgmujbg-patju

**Comment by patrickjuchli** [comment]
Can you explain why deleting the selected lines makes things work for you?

**Comment by jonhue** [comment]
Thinking a little more about it, I'm just realizing that it's because I tried running this in the browser 😅 Sorry for bugging you with this issue!

**Comment by p3im4n** [comment]
> Thinking a little more about it, I'm just realizing that it's because I tried running this in the browser 😅 Sorry for bugging you with this issue!

hi Mr @jonhue 
I have same issue 
how suppose to being use "basic-ftp" in web server?
