### ISSUE TITLE
 None of the available transfer strategies work

### ISSUE THREAD

**Issue by DanAmel** [patrickjuchli/basic-ftp#188]
**Describe the bug**
I got this error   **None of the available transfer strategies work**  when i try to get file list. 

Notice that my app and the ftp server are in the same server (i use docker's container). When i try the same code  in another server it's work.

**Example code**
async connectFTP(){
    var client = null
    try{
      client = new FTP.Client(999999)
      client.ftp.verbose = true
      await client.access({
        host: Env.get('FTP_HOST'),
        user: Env.get('FTP_USER'),
        password: Env.get('FTP_PASSWORD'),
        port: 21,
        secure: false
      })
    }catch (error){
      console.log(error)
    }

    return client
  }

async getListFiles(path) {
    const client = await this.connectFTP()
        try{
          files = await this.listFTP(client, path)
        }
        catch (e) {
          console.log('error', e) // None of the available transfer strategies work
        }
    await this.closeFTP(client)
}

```
Connected to 161.xx.xx.xx:21 (No encryption)
< 220 (vsFTPd 3.0.2)

Login security: No encryption
> USER ftp_xxx
< 331 Please specify the password.

> PASS ###
< 230 Login successful.

> TYPE I
< 200 Switching to Binary mode.

> STRU F
< 200 Structure set to F.

> OPTS UTF8 ON
< 200 Always in UTF8 mode.

> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 501 Option not understood.

Trying to find optimal transfer strategy...
> EPSV
< 229 Entering Extended Passive Mode (|||21107|).

^[[1;2C> PASV
< 227 Entering Passive Mode (161,xx,xx,xx,82,117).

error Error: None of the available transfer strategies work.
```

**Which version of Node.js are you using?**
 Node 14

**Additional context**
My server (vsFTPd 3.0.2)

**Comment by patrickjuchli** [comment]
Could you paste the log output again and use triple backticks at the beginning and at the end? Like in the first example here https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

This will help me see the true log output because this looks like a very curious problem.

**Comment by DanAmel** [comment]
Ok i update the previous message

**Comment by patrickjuchli** [comment]
So this only fails in your own setup, it usually works with other servers? Not sure I can help here.

I've published a new version 4.6.6 which logs a bit more details why the transfer strategies fail. Could you try that and post the log again?

**Comment by DanAmel** [comment]
The same code works well when the app and the ftp server are not in the same server.

```
Connected to 161.xx.xx.xx:21 (No encryption)
< 220 (vsFTPd 3.0.2)

Login security: No encryption
> USER ftp_xx
< 331 Please specify the password.

> PASS ###
< 230 Login successful.

> FEAT
< 211-Features:
 EPRT
 EPSV
 MDTM

<  PASV
 REST STREAM
 SIZE
 TVFS
 UTF8
211 End

> TYPE I
< 200 Switching to Binary mode.

> STRU F
< 200 Structure set to F.

> OPTS UTF8 ON
< 200 Always in UTF8 mode.

Trying to find optimal transfer mode...
> EPSV
< 229 Entering Extended Passive Mode (|||21100|).

Transfer mode failed: "Can't open data connection in passive mode: connect ETIMEDOUT 161.xx.xx.xx:21100", will try next.
> PASV
< 227 Entering Passive Mode (161,xx,xx,xx,82,112).

Transfer mode failed: "Can't open data connection in passive mode: connect ETIMEDOUT 161.xx.xx.xx:21104", will try next.
error Error: None of the available transfer modes work.
    at Client.prepareTransfer (/app/node_modules/basic-ftp/dist/Client.js:701:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.list (/app/node_modules/basic-ftp/dist/Client.js:485:13)

```

**Comment by patrickjuchli** [comment]
Ok, great. Socket connection can't be established, there is a timeout. This looks like the FTP server is not configured properly or ports required for PASV (passive mode) are not available. Sorry, but I don't know enough about that to help you here. Doesn't look like an issue with the library.

**Comment by DanAmel** [comment]
Thanks for your help.
**I open the ports  (with ufw) and its works.** The app and the ftp server are located in the same server.

But I don't understand why for the same  ftp server  it's work without open ports  when my app is located in another server.

**Comment by patrickjuchli** [comment]
No idea, sorry. But this ticket can be closed then, right?

**Comment by DanAmel** [comment]
yes  👍
