### ISSUE TITLE
Directory listing does not close the connection

### ISSUE THREAD

**Issue by mitxp** [patrickjuchli/basic-ftp#190]
**Describe the bug**
When calling
await ftp.list()
a directory listing is returned correctly, but after that, my FTP server has an open connection that is not closed by the FTP client. The FTP server is a vsftpd running on Linux (CentOS 8) and netstat will show me for each directory listing I made on the server a connection in "TIME_WAIT" state meaning that the server closed the transfer connection but is waiting for the client to acknowledge this.

**Example code**
await ftp.access({host: 'myhost', user: 'ftp', password: 'ftp', secure: false});
await ftp.cd('/pub');
await ftp.list();
ftp.close();

**Console output**
```
Connected to 192.168.1.1:21 (No encryption)
< 220 (vsFTPd 3.0.3)
Login security: No encryption
> USER ftp
< 331 Please specify the password.
> PASS ###
< 230 Login successful.
> FEAT
< 211-Features:
 EPRT
 EPSV
 MDTM
 PASV
 REST STREAM
 SIZE
 TVFS
 UTF8
211 End
> TYPE I
< 200 Switching to Binary mode.
> STRU F
< 200 Structure set to F.
> OPTS UTF8 ON
< 200 Always in UTF8 mode.
> CWD /pub
< 250 Directory successfully changed.
Trying to find optimal transfer mode...
> EPSV
< 229 Entering Extended Passive Mode (|||54987|)
Optimal transfer mode found.
> LIST -a
< 150 Here comes the directory listing.
Downloading from 192.168.35.14:54987 (No encryption)
< 226 Directory send OK.
drwxrwxrwx    2 14       50           4096 Mar 30 08:49 .
drwxrwxrwx   20 14       50           4096 Mar 30 08:44 ..
-rw-rw-rw-    1 14       50           5635 Mar 30 09:15 4da102850412454595ad5ed6580b964f.png
-rw-rw-rw-    1 14       50           3996 Mar 30 09:15 6ba0c0448938492d82ef4b7829198a7d.png
-rw-rw-rw-    1 14       50           8410 Mar 30 09:15 e2b94626439f41419d1c0750bd4bec29.png
```
Note: this is the end. No log message about closing any connection.

**Which version of Node.js are you using?**
Node 10.19.0 and 11.15.0

**Additional context**
See above. Running on Windows and on Linux both has the same effect. Please note that the control connection is closed correctly. Tested with basic-ftp version 4.6.6 and 4.6.3.

**Comment by patrickjuchli** [comment]
Can't reproduce this with version >= 5.0.0, could you check on your side if the issue persists?

**Comment by mitxp** [comment]
Sorry, we migrated to a different package. But I am happy to hear the issue has been fixed.
