### ISSUE TITLE
Client times out after connecting

### ISSUE THREAD

**Issue by lfnovo** [patrickjuchli/basic-ftp#191]
**Describe the bug**
Client timesout after connecting

**Example code**

```
const client = new this.basicftp.Client();
    client.ftp.verbose = true;
    try {
      console.log(`Trying do access repo ... `);
      await client.access({
        host: 'xxxx',
        user: 'xxxx',
        password: 'xxxxx',
        port: 22,
        secure: true,
      });
      await client.ensureDir('/direct');
      console.log(`Trying to list directory`);
      console.log(await client.list());
      //   await client.uploadFrom('README.md', 'README_FTP.md');
      //   await client.downloadTo('README_COPY.md', 'README_FTP.md');
    } catch (err) {
      console.log(err);
    }
    client.close();
  }
```

**Console output**

Trying do access repo ... 
Connected to 35.207.14.44:22 (No encryption)
< SSH-2.0-OpenSSH_7.4

Error: Timeout (control socket)
    at Socket.<anonymous> (/Users/lfnovo/Documents/dev/nest-sync-users/node_modules/basic-ftp/dist/FtpContext.js:316:58)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Which version of Node.js are you using?**
e.g. Node 14.4.0

**Additional context**
I am using NestJS.

**Comment by mofux** [comment]
It looks like you are trying to connect to an SSH server via SFTP. This module only supports FTP and FTPS which is a completely different protocol (despite the names SFTP and FTPS sound somewhat similar). You can use the ssh2 package to interact with SFTP servers.
