### ISSUE TITLE
Downloading files over FTPS works locally but getting "None of the available transfer modes work" on Azure Function

### ISSUE THREAD

**Issue by pitawatn** [patrickjuchli/basic-ftp#194]
I deployed an Azure Function running Node 12 which tries to download a PDF file from FTPS server.

Everything works fine on my local dev laptop, files can be downloaded. But when triggering Azure Function, I got an error

`None of the available transfer modes work.at Client.prepareTransfer (D:\home\site\wwwroot\node_modules\basic-ftp\dist\Client.js:701:19)at processTicksAndRejections (internal/process/task_queues.js:97:5)`

I thought it was the connection issue, but I ran `client.size("example.pdf");` and it showed correct file size so this proves the connectivity is fine. However, I also tried `client.list();` and received the same error.

Thanks.

**Comment by patrickjuchli** [comment]
Transfering files and requesting directory listing require a second type of connection that is being setup. Reading this lets me conclude that this has something to do with your Azure function.

Issues submitted here should include at least a hint that there is something wrong with this library. Sites like Stackoverflow are better suited to this kind of question. Without this kind of focus, I'd be answering issues non-stop, I hope you understand.
