### ISSUE TITLE
[Feature request]: connect & login using full ftp url

### ISSUE THREAD

**Issue by jimmywarting** [patrickjuchli/basic-ftp#197]
It would have been nice to get rid of 4 variables and replace them with one url string

```js
client.connect_n_login('ftp://user_name:password@hostname:21')
// or 
client = new Client('ftp://user_name:password@hostname:21')
```

URL constructor could be used to parse the url...

**Comment by patrickjuchli** [comment]
Keeping API as simple and stable for now.
