### ISSUE TITLE
Differentiate client close reasons

### ISSUE THREAD

**Issue by iosc82** [patrickjuchli/basic-ftp#198]
Is there currently a way to distinguish between various reasons for which a client is closed through `client.close()`?

I'm implementing a pause function which halts an ongoing transfer. To actually shut down the transfer, I use `client.close()`.

There are other places where I call `client.close()`, for example when I'm hitting a "disk full" error.

As the transfer Promise rejects, I currently don't see a way to differentiate between the two close reasons. I could envision a parameter that can be passed to `client.close()` which is then returned from the rejected Promise.

**Comment by patrickjuchli** [comment]
You could use `client.ftp.closeWithError(err: Error)` and encapsulate your information there. If that's not enough you might have to wrap the client and hold that additional information in that wrapper.
