### ISSUE TITLE
index file not found error.

### ISSUE THREAD

**Issue by daytona16520** [patrickjuchli/basic-ftp#201]
**Environment**
basic-ftp version 4.6.6
Node.js version 14.16.1
Visual Studio Community 2019 version 16.11.2

**Symptom**
Under Error List in Visual Studio, I get the following error message;
Code: TS6053
File 'C:/Users/xxxx/xxx/xxxx/xxxx/node_modules/basic-ftp/dist/index' not found.  The file is in the program because: Root file specified for compilation.
The code appears to be working fine, despite the error message.

**Actions taken**
- Uninstall the package, restart Visual Studio and re-install.
- Rebuild the project.

If you can look into the resolution of this issue, I'd be much obliged.

**Comment by patrickjuchli** [comment]
Can't look into why things don't seem to work on your development setup, sorry. Please ask StackOverflow or similar platforms.
