### ISSUE TITLE
Using client.list on empty directory cause throw a parser error

### ISSUE THREAD

**Issue by slongiaru-rblab** [patrickjuchli/basic-ftp#206]
**Describe the bug**
Using client.list on an empty directory cause the throw of an Error retrieving the parser because the rawLine string provided includes always as first line the number of affected files.
Portion of code is situated in: parseList.js

```
/**
 * Parse raw directory listing.
 */
function parseList(rawList) {
    const lines = rawList
        .split(REGEX_NEWLINE)
        .filter(stringIsNotBlank);
    if (lines.length === 0) {
        return [];
    }
    const testLine = lines[lines.length - 1];
    const parser = firstCompatibleParser(testLine, availableParsers);
    if (!parser) {
        throw new Error("This library only supports MLSD, Unix- or DOS-style directory listing. Your FTP server seems to be using another format. You can see the transmitted listing when setting `client.ftp.verbose = true`. You can then provide a custom parser to `client.parseList`, see the documentation for details.");
    }
    const files = lines
        .map(parser.parseLine)
        .filter((info) => info !== undefined);
    return parser.transformList(files);
}
```

**Example code**
I suppose the code should always remove the first line before try to detect the parser.

```
/**
 * Parse raw directory listing.
 */
function parseList(rawList) {
    const lines = rawList
        .split(REGEX_NEWLINE)
        .filter(stringIsNotBlank);

    // remove the first line that contains "total N" where N is the number of affected files
    lines = lines.slice(1);

    if (lines.length === 0) {
        return [];
    }
    const testLine = lines[lines.length - 1];
    const parser = firstCompatibleParser(testLine, availableParsers);
    if (!parser) {
        throw new Error("This library only supports MLSD, Unix- or DOS-style directory listing. Your FTP server seems to be using another format. You can see the transmitted listing when setting `client.ftp.verbose = true`. You can then provide a custom parser to `client.parseList`, see the documentation for details.");
    }
    const files = lines
        .map(parser.parseLine)
        .filter((info) => info !== undefined);
    return parser.transformList(files);
}
```

**Console output**
Connected to *** (No encryption)
< 220 [IES-FTPD] FTP server (Ver. 1.2.35 Mar 28 Mar 2018) ready.

Login security: No encryption
> USER ***
< 331 Password required for ***.

> PASS ###
< 230 User *** authorized.

> FEAT
< 500 'FEAT': command not understood.

> TYPE I
< 200 Type set to I.

> STRU F
< 200 STRU F ok.

> OPTS UTF8 ON
< 500 'OPTS UTF8 ON': command not understood.

> CWD /***
< 250 CWD command successful (authorized).

Trying to find optimal transfer mode...
> EPSV
< 229 Entering Extended Passive Mode (|||28389|)

Optimal transfer mode found.
> LIST -a
< 150 Opening BINARY mode data connection for ls.

Downloading from *** (No encryption)
< 226 Transfer complete.

total 0

Error: This library only supports MLSD, Unix- or DOS-style directory listing. Your FTP server seems to be using another format. You can see the transmitted listing when setting `client.ftp.verbose = true`. You can then provide a custom parser to `client.parseList`, see the documentation for details.

**Which version of Node.js are you using?**
Node: 16.11.1
Basic FTP: 4.6.6

**Additional context**
The issue compare also using SFTP.

**Comment by patrickjuchli** [comment]
Fixed in 5.0.0
