### ISSUE TITLE
uploadFrom last Mod date is current rather than original file's last Mod Date

### ISSUE THREAD

**Issue by RecycleBen** [patrickjuchli/basic-ftp#211]
When running client.uploadFrom() it uploads a file with the current date / time rather than the file's last modified date.

This means that when I compare the files on the FTP compared to my local directory they have different dates and the newly uploaded file appears to be a more recent file when they are the same file.

When I use WinSCP to upload the file has the original changed date after upload.

Is it possible to have it upload with the original file changed date rather than applying a new one?

**Comment by patrickjuchli** [comment]
This is an additional feature that the clients you mention support. You can try using `client.send()` to send FTP commands directly using this list https://en.wikipedia.org/wiki/List_of_FTP_commands. 

This is not a feature that will be added to the client, I'm afraid.

**Comment by RecycleBen** [comment]
Thanks so much for looking into this even though you're not going to do anything.
Really appreciate it.
I'll look at the wiki and see if there's a send command that will work or do the exact commands the other client does to see if that fixes my problem. Otherwise, nice of you to keep this repo going!
