### ISSUE TITLE
R Extension in VS code 

### ISSUE THREAD

**Issue by bertinos98** [patrickjuchli/basic-ftp#217]
![image](https://user-images.githubusercontent.com/81575793/190933773-115c762f-8a5b-4aeb-8cb4-e4b1453ea279.png)

I've been trying to solve this problem for days but I couldn't. I can't save files with an .R extension, but with python files it works. I can't even create files from VS code. can someone help me, please?

**Comment by patrickjuchli** [comment]
Wrong repository?

**Comment by bertinos98** [comment]
i don't really know what does it mean

**Comment by patrickjuchli** [comment]
You have opened an issue for the library "basic-ftp" but your troubles seem to concern something entirely different (R, VS-Code). If they are indeed related to "basic-ftp", could you describe in what way?

**Comment by bertinos98** [comment]
my problem is simple. when I create files with a python extension, I manage to save them and also save them automatically. but when it comes to files with an R extension the system gives me an error.
