### ISSUE TITLE
Question: If the local file is deleted during FTP upload, why can the file continue to upload

### ISSUE THREAD

**Issue by ntscshen** [patrickjuchli/basic-ftp#226]
I am uploading the file, I delete the original file locally, why can it continue to upload.
This is my puzzle, this is not "basic-ftp" problem

**Comment by patrickjuchli** [comment]
The file's contents have probably been buffered in memory before you deleted the file and upload continues to use that buffer. I assume it's not a large file? Behaviour might be different with a very large file.

Not really an issue with basic-ftp, closing.

**Comment by ntscshen** [comment]
The file's contents have probably been buffered in memory , The file reading process uses node:stream, The main thing is to avoid large caches

I did a large file test of your little problem above

I have only 16GB of RAM, I just tested a 30.26GB file, After the upload task is enabled, I delete the local file, It successfully uploaded 28.18GB, On this node, the Error is caught: `Error: Timeout (control socket)`

I want to warn users of this foolishness

---------

This may be a file management issue with the operating system, but it's beyond my knowledge, and I may have to give up on the silly act of prompting the user for a while
