### ISSUE TITLE
SFTP Timeout (control socket)

### ISSUE THREAD

**Issue by guilhermealbino33** [patrickjuchli/basic-ftp#230]
I'm trying to connect to an SFTP Server, but I'm not able to do so:

Here's my code:

`   
      try {
      const client = new ftp.Client();
      client.ftp.verbose = true;

      await client.access(config);
      console.log('connected');
      // Never reaches here

      const filePath = path.join(__dirname, '..', '..', '..', '..', '..', 'tmp', `${fileName}`);
      const directory = '/accounts/';

      await client.uploadFrom(filePath, directory);
      client.close();
    } catch (err) {
      throw new Error(`Error: ${err}`);
    }`

My log:

`Connected to 52.70.237.138:22 (No encryption)
< SSH-2.0-OpenSSH_7.4

> QUIT
Error: Timeout (control socket)`

Is possible to connect to a SFTP server with this lib?

**Comment by patrickjuchli** [comment]
Duplicate #142
