### ISSUE TITLE
How can i check with IF clause when using uploadfrom

### ISSUE THREAD

**Issue by ChristanFarel** [patrickjuchli/basic-ftp#236]
I want to do something when i know , if the upload process is successful 

 if (await client.uploadFrom(filePath, `${filename}`)); --> Success ) {
then do something
}

can i possibly do that? and how? thank you

im still learning :D

**Comment by patrickjuchli** [comment]
If no exception is thrown, the upload was successful.

**Comment by ChristanFarel** [comment]
oww i see, thank you very much
