### ISSUE TITLE
Can't connect to same server subsequently - connection stuck, no timeout

### ISSUE THREAD

**Issue by Twisterking** [patrickjuchli/basic-ftp#24]
So for some reason I am somehow "stuck" with my first connection.
After starting up my nodejs server "fresh" and calling my function which connects to a remote FTP, downloads some files and `ftpClient.close()`s before returning, all is fine.
All the other code after downloading the files is executed and the parent function returns properly - all good!
After waiting a couple of seconds, I make the exactly same call again, the FTP should connection again, download the same files ... you get the idea.
BUT: my `console.log()` directly after the `await ftpClient.access()` is **never fired**. The FTPClient is just stuck there forever, no timeout no nothing, just stuck. I have to restart my whole server all over again to be able to call my function again - again only once, the second time the same thing happens all over again.

Version: `2.14.0`, nodeJS Version: `v8.11.4`

**Comment by patrickjuchli** [comment]
@Twisterking, I really need you to work more on this and to reduce your issue to a small code example. Otherwise it's really difficult to help you from afar. I feel your frustration – but not much more apart from that. (Did you not see the issue template? It's there for this exact reason.)

Maybe one thing: You say there is no timeout. Did you wait for the default 30 seconds or did you set the timeout to be shorter?

Bonus point: If a client causes your FTP server to get so stuck that you have to restart the server, you just found a vulnerability in your FTP server. Congratulations!

**Comment by Twisterking** [comment]
Sorry about that, I will provide you with a working small code example asap.
Until then, here is all the code which get's "stuck":

```js
export async function downloadRemoteFiles(localDirPath, connectorSettings) {
  let allfiles = null;
  try {
    await ftpClient.access(connectorSettings.ftpConnection);
    console.log('FTP Connection established ...');
    await ftpClient.cd(connectorSettings.remoteDir || 'pricat');
    allfiles = await ftpClient.list();
    for (const file of allfiles) {
      if(file.type == 0) { // 0 == file, 1 == folder
        const writeStream = fs.createWriteStream( path.join(localDirPath, file.name) );
        try {
          await ftpClient.download(writeStream, file.name);
        } catch(err) {
          console.error(err);
        }
      }
    }
  }
  catch(err) {
    console.error(err)
  }
  ftpClient.close();
  return allfiles;
}
```

console output:
**first run**:
```
Connected to 139.59.204.208
I20181002-18:59:20.493(2)? < 220 ProFTPD 1.3.5a Server (myhost.com) [::ffff:10.19.0.6]
I20181002-18:59:20.494(2)? Login security: No encryption
I20181002-18:59:20.495(2)? > USER ftptest
... all works :-)
...
FTP Connection established ...
```

**second run**:
```
I20181002-18:59:29.801(2)? Connected to 139.59.204.208
--> STUCK - no more output!
```

Timeout is set to `10000` - even waited like 2 mins, no change, no timeout - just stuck.

crashing server:
You misunderstood me: my FTP server is just fine, no crash, but I have to restart my nodeJS server to make my function above work again (once!).

**Comment by patrickjuchli** [comment]
When you access the second time, are you using a completely new instance of ftp.Client?

**Comment by Twisterking** [comment]
oh ... looks like I am an idiot! 😀 😢
Nope I am not ... this makes absolute sense that this is the reason for this behavior.
I thought due to the `client.close()` I should be able to reuse the same client instance but apparently not so - thanks a lot for your quick help! I will try this tomorrow asap and get back to you with feedback but I am 99% sure that this fixes my problem - no idea why I didn't think of that.

**Comment by patrickjuchli** [comment]
Great, I think I'll make a release soon that will show a clear error message when someone tries to reuse an instance. This is not at all self-explanatory, so thanks for the hint.

**Comment by patrickjuchli** [comment]
I have released a new version 2.14.2 where you can reconnect after closing a client. You don't have to create a new instance anymore.

**Comment by Twisterking** [comment]
just updated - works like a charm! Thanks for your very quick help!

**Comment by patrickjuchli** [comment]
Hi @Twisterking, there might be an update with a breaking change in the future regarding this issue. If it becomes reality, it will of course be reflected correctly by semantic versioning but I wanted to get your 5 cents on this:

Making it possible to reconnect the same client instance might be problematic. I'm thinking about reversing this change. If a client instance failed, you can't reuse it but have to instantiate a new one. This should not be a big thing to handle but how do you feel about this?

**Comment by Twisterking** [comment]
Sure shouldn't be a problem! Only important thing is, that the Readme/Docs have to properly reflect this change - so every user realizes he **has to use a new instance every time** - otherwise some people will make the same mistake I made.

**Comment by patrickjuchli** [comment]
Thanks for your feedback!
