### ISSUE TITLE
Immutable files on server

### ISSUE THREAD

**Issue by malee1975** [patrickjuchli/basic-ftp#240]
Hi,

Is there anyway the library can determine if  the file on the server is immutable or not.

For example in Linux I used the `chattr +i file-name.ext` command to make the file immutable.

regards

Matt

**Comment by patrickjuchli** [comment]
There is no standard way to do this.

You could use the SITE command to access server-specific functionality. Try `client.send("SITE chattr +i file-name.ext")`. But there is no guarantee that your FTP server supports this.
