### ISSUE TITLE
White space is file and folder names

### ISSUE THREAD

**Issue by malee1975** [patrickjuchli/basic-ftp#245]
Scenario is running the [core FTP](http://coreftp.com/) server on windows server 2022. The FTP server inserts white space before file and folder names. By the look of it a tab. This can be remediated when listing though applying a `trim()` to file and folder names.

However this might be impacting the libraries `removeDir` function which fails to remove directories that can be deleted using FTP clients such as FileZilla

**Comment by patrickjuchli** [comment]
I don't fully understand the issue, could you clarify?

Are you seeing white space before filenames and directory names when you use client.list() where there shouldn't be any? Could you paste the log output here? I'd like to see the exact server response to the list command.

**Comment by malee1975** [comment]
Hi Patrick,

This issues was researched a bit further.

It was discovered that by default core FTP has MLSD disabled [RFC-3659](https://www.ietf.org/rfc/rfc3659.txt)

It has to be enabled to serve the response in semi-colon delimited format.

Without this delimiting there is a space left in front of the first character of the filename. Leading to a response like the following image.

![image-20231117-102707](https://github.com/patrickjuchli/basic-ftp/assets/140089412/d21c9919-c5e1-4091-b611-8d264f04880e)

I have attached the server logs illustrating the difference between MLSD enabling and disabling.
[Server response.txt](https://github.com/patrickjuchli/basic-ftp/files/13674404/Server.response.txt)

**Comment by patrickjuchli** [comment]
Okay, thank you. I can't just trim the response because the whitespace might be intended and is supported by this library. I also don't see a TAB (or lots of SPACE) in the log before the entry "testfolder", so I'm not sure where this is coming from.

**Comment by patrickjuchli** [comment]
Okay, thanks! That looks very unfortunate. I can't just use trim() because the whitespace might be intended and part of the filename. This library supports whitespace. According to the log it doesn't seem to be a simple TAB but indeed many SPACE characters. Not quite sure what to do here.

**Comment by malee1975** [comment]
We patched as best as we could. It seems to be miscalculating the whitespace: as you said trimming is not possible as whitespace can be intended. That however is how FileZilla works. 

![Screenshot 2023-12-14 165248](https://github.com/patrickjuchli/basic-ftp/assets/140089412/996f6f5b-af78-4ffd-90ee-f59fe53bd21f)

You can see here how there are two files called remote.pdf, one of them has a blank character at the start.

On one level I am not sure if the core FTP server is working properly. 

On another the issue can be resolved by switching to MLSD within the server application. 

The issue only is with core FTP not FTP servers run through Docker or elsewhere.  

However I figure these are already to respond in MLST format.

**Comment by patrickjuchli** [comment]
Great screenshot, very insightful, thanks. So FileZilla has decided to trim – I can understand that decision, whitespace in names causes a lot of problems and is not intended usually. Unfortunately I can't reverse that without a breaking change. 

Directory listings are one of reasons to avoid FTP. Their format first wasn't actually specified, the server should just answer with its default listing, even if it is in Japanese. MLSD changed that, so if you can enable it, you should be using that one anyway. `basic-ftp` also only parses timestamps from MLSD by the way.

Should we close this issue?

**Comment by malee1975** [comment]
Hi Patrick,

Closing is no problem.

Thanks for the insight to the timestamps.

Have a great Christmas and New Year.

regards

Matt

**Comment by malee1975** [comment]
Thanks for your time :)

**Comment by patrickjuchli** [comment]
Likewise, happy holidays!
