### ISSUE TITLE
Download images from FTP

### ISSUE THREAD

**Issue by chinook07** [patrickjuchli/basic-ftp#248]
Help! I'm trying to make a server-side function that allows me to get images from an FTP drive, and then send them client-side to be used (visible) in my front-end.
I have this code server-side.

`const buffer = await client.downloadTo(fileName, fileLocation);`

When I console log buffer, I see it fetches the wanted image.
buffer {
  code: 226,
  message: '226-File successfully transferred\n' +       
    '226 0.101 seconds (measured here), 19.77 Mbytes per second'
}
Then I res.status it to my front-end, but all I get on the front-end is [object Object], and `GET data:image/jpg;base64,[object Object] net::ERR_INVALID_URL` in my console log.

I tried these:

- `res.set('Content-Type', 'image/jpg');` before res.status
- `<img src={`data:image/jpg;base64,${nameOfFileInFrontEnd}`} alt="" />` in my React component
- `buffer.toString('base64')`

Whatever I tried, the image is unreadable on the front-end. However, they are very well there in the /server folder of my project.
Any help is appreciated!

**Comment by patrickjuchli** [comment]
I'm afraid this issue tracker is for bugs or feature requests concerning the library specifically. Your question should be posted to something like Stackoverflow, you have a much better chance of finding an answer there.
