### ISSUE TITLE
How do I use active mode?

### ISSUE THREAD

**Issue by sjh836** [patrickjuchli/basic-ftp#25]
Hi, I am very fortunate to have found this open source. I learned a lot from the code.

I have one thing to ask. **How do I use active mode?**

Many companies' FTP servers have active mode and passive mode for different security reasons.

**Comment by patrickjuchli** [comment]
Active mode is not supported out-of-the-box. You should be able to provide this functionality by implementing it yourself using custom a transfer strategy, see https://github.com/patrickjuchli/basic-ftp#custom-strategies.

Adding support for active mode is currently not on the roadmap, I'm sorry. Out of interest, these companies would then also use secure FTPS in active mode?

**Comment by sjh836** [comment]
@patrickjuchli There are servers operating in active mode because of the policy on ports.
On a server that only supports active mode, the following error occurs.

```
> EPSV
< 550 Permission denied.
> PASV
< 550 Permission denied.
```

`Error: None of the available transfer strategies work.`

Is this correct to refer to https://github.com/patrickjuchli/basic-ftp#custom-strategies ?

Could you give me a hint about the implementation?

```
const ftp = require("basic-ftp");

const client = new ftp.Client();
client.prepareTransfer = enterAcitveModeIPv4;

async function enterAcitveModeIPv4(client) {
    const res = await client.send("???"); // If I do not send PASV, it seems to be in active mode. Is that correct?

    // Can you give me a hint that you need some more code?

    return res;
}
```

**Comment by patrickjuchli** [comment]
Yes, you are setting up the function correctly. 

The first thing you'll have to do is tell the server which port you want it to connect to using `PORT`. This site explains the difference between active and passive mode: http://slacksite.com/other/ftp.html.

**Comment by sjh836** [comment]
Thank you!

Another question, is there any module that supports active mode in npm module? Both node-ftp and jsftp do not seem to support active mode.

Does it generally affect the development of the library, not the development?

**Comment by patrickjuchli** [comment]
First, active mode is not supported simply because I try to keep this library simple. I don't have that much time. Second, the main focus of this library are explicit FTPS and IPv6. Both would have to be supported for active mode as well.

Supporting active mode is not much more difficult than passive mode. You'll have to offer a configurable port range that the library will then use for each transfer. Plus, things get a bit more involved with explicit FTPS. I haven't done a lot of research on active mode, though.

Passive mode is just a lot more popular. That's why there is not a lot of support for it.

**Comment by patrickjuchli** [comment]
That being said, let me know if you have an implementation for active mode and are interested in adding it to the library.

**Comment by Ioana222** [comment]
Hello @sjh836 
I am interested to see the implementation for enterAcitveModeIPv4 function. Could you share it, please?
