### ISSUE TITLE
"Closing connections" issue

### ISSUE THREAD

**Issue by davvvid1** [patrickjuchli/basic-ftp#26]
**Describe the bug**
I suspect a bug related to closing client connection. After successful file upload and close the connection I see infinitely repeated message `Closing connections.` in the console. I tried on two different FTP servers and it looks the same.

**Example code**
```
const ftp = require("basic-ftp");
const client = new ftp.Client();
client.ftp.verbose = true;
client.access({
    host: "ftp.drivehq.com",
    user: "davvvid1",
    password: "***",
    secure: true
}).then(() => {
    const Readable = require('stream').Readable;
    const stream = new Readable;
    stream.push('File content');
    stream.push(null);
    return client.upload(stream, 'file-name.txt');
}).then(() => {
    console.log('UPLOADED SUCCESSFULLY');
    return client.close();
}).catch((err) => {
    console.log('ERROR');
    console.log(err);
});

setInterval(() => {
    console.log('keep node active...');
}, 5000);
```

**Console output**
```
Connected to xx.xx.xx.xx
< 220 FTP HOSTING WELCOME MESSAGE;
> AUTH TLS
< 234 AUTH Command OK. Initializing TLS connection.
Control socket is using: TLSv1.2
Login security: TLSv1.2
> USER davvvid1
< 331 User name ok, need password.
> PASS ###
< 230 User davvvid1 logged on. Free service has restrictions and is slower.
> TYPE I
< 200 Type set to I
> STRU F
< 200 File structure set to file.
> PBSZ 0
< 200 PBSZ Command OK. Protection buffer size set to 0.
> PROT P
< 200 PROT Command OK.
Trying to find optimal transfer strategy...
> EPSV
< 501 Syntax error: Command not understood.
> PASV
< 227 Entering Passive Mode (66,220,9,50,17,140).
Optimal transfer strategy found.
> STOR file-name.txt
< 150 Connection accepted
Uploading (TLSv1.2)
< 226 Transfer complete
UPLOADED SUCCESSFULLY
Closing connections.
keep node active...
keep node active...
keep node active...
keep node active...
keep node active...
keep node active...
Closing connections.
keep node active...
keep node active...
keep node active...
keep node active...
keep node active...
keep node active...
Closing connections.
```

**Which version of Node.js are you using?**
Node 8.11.1

**Additional context**
`setInterval` in the code is only for keeping node process alive. Without it, process exits correctly. Maybe I create the stream in wrong way? But files are successfully uploaded and I see them on FTP servers. I tried on `ftp.drivehq.com`. Second FTP server is private and I even can't give you access to test but the issue is exactly the same so maybe the first example server would be enough.

**Comment by patrickjuchli** [comment]
What a nice find, thanks for the report!

When a client is closed, it creates a new socket instance for a possible future reconnection. Even though this socket is not connected to anything yet, timeouts are already applied. The default timeout is 30 seconds. That's why you see "keep node active" 6 times. After that, the socket throws a timeout which leads to the client being closed again. This in turn creates a new socket instance… and on and on.

**Comment by patrickjuchli** [comment]
Fixed in 2.14.4

**Comment by davvvid1** [comment]
I just tested it on the same code base using `2.14.4` version. The problem no longer occurs! Thank you so much for your immediate reaction!

**Comment by sjh836** [comment]
Hi. I think this patch has other side effects.

In version 2.14.3, when I tried `const client = new ftp.Client (3000);` and attempted to connect to a server blocked by FTP firewall, the response was about 3020ms.

In version 2.14.4, however, the response is about 21020ms regardless of the timeout setting.

**Comment by patrickjuchli** [comment]
Thanks a lot for the report, this issue will be tracked here: #27
