### ISSUE TITLE
[poor question] What would you like to do in this case

### ISSUE THREAD

**Issue by sjh836** [patrickjuchli/basic-ftp#28]
In my project, I connect to 100 FTP servers in 1 minute and receive files.
Below is a sample of the code.

```
const ftp = require("basic-ftp");

async function exec(other, timeout) {
    const client = new ftp.Client(timeout);
    /*
        connect
        list
        download
        etc..
    */
    client.close();
}
```

`exec()` is called periodically and has a `new ftp.Client`. Is this recommended?
Or do you recommend creating an object pool or a singleton to use only one object per FTP server?

**Comment by patrickjuchli** [comment]
I'd focus on writing simple, stable and easy to understand code first. So yes, create a client instance each time you want to connect to a server, do some work, close it right after and let garbage collection do its work.

Are you downloading from 100 FTP servers at the same time? Maybe that's where you can continue, maybe there you can add some queue that limits that somehow. But that would be a concern at a higher level, not at the level of this library.

**Comment by sjh836** [comment]
Okay. thank you~!
