### ISSUE TITLE
Will close connections because of error: { ftpSocket: 'control' }

### ISSUE THREAD

**Issue by france193** [patrickjuchli/basic-ftp#30]
I tested this module and basically it works but now I get an error and I don't know why...

**Describe the bug**
I'm trying to upload a file from a FTP server and I did this test with 2 different FTP server and I get the same error.

**Example code**

```
async function example() {
    const client = new ftp.Client();

    client.ftp.verbose = true;

    try {
        // ftp connect
        await client.access(options);

        // print current remote dir
        const string = await client.pwd();
        log.info(string);

        const fileName = 'test.txt';

        fs.stat(fileName, async function (err, stat) {
            try {
                if (err == null) {
                    log.info('--> File exists: ' + fileName);

                    const result = await client.upload(fs.createReadStream(fileName), fileName);

                    if (result === 226) {
                        log.info('--> Stored file: ' + fileName);

                        // remove file with a callback:
                        /*
                        fs_extra.remove(filePath + fileName, err => {
                            if (err) return console.error(err);
                            log.info('--> Deleted file: ' + filePath + fileName);
                        });
                        */
                    }
                } else if (err.code === 'ENOENT') {
                    log.info('--> Not found file: ' + fileName);
                } else {
                    log.info('Some other error: ', err.code);
                }
            } catch (e) {
                log.info("ERROR 1");
                log.info(e);
            }
        });
    } catch (err) {
        log.info(err);
    }

    client.close();
}
```

**Console output**
Connected to 192.168.0.116:211
< 220 ProFTPD 1.3.5b Server (Debian) [::ffff:192.168.0.116]
Login security: No encryption
> USER pi
< 331 Password required for pi
> PASS ###
< 230 User pi logged in
> TYPE I
< 200 Type set to I
> STRU F
< 200 Structure set to F
> PWD
< 257 "/home/pi" is the current directory
Closing connections.
2018-11-14 11:43:04 INFO  /home/pi
Trying to find optimal transfer strategy...
> EPSV
Will close connections because of error:
{ ftpSocket: 'control' }
Closing connections.

**Which version of Node.js are you using?**
v8.11.3

**Additional context**
I'm running my nodeJS application in a Raspberry Pi 3B+ but yesterday It worked.

**Comment by patrickjuchli** [comment]
It looks to me like the client is closed before the callback set for `fs.stat` is executed.

Don't mix async/await with callback-style API, it makes the code confusing to read. You probably expect client to still be connected when you reach the line with `client.upload` but it's not. 

Node 8 offers `util.promisify` that lets you wrap classic Node.js callback API. This library is doing the same thing, see here: https://github.com/patrickjuchli/basic-ftp/blob/dbfdc722825eeee1f32164e1af338bb5156e97e1/lib/ftp.js#L17

**Comment by france193** [comment]
I don't get the point, I have updated my code removing callback-style but I get the same error:

```
async function example() {
    const client = new ftp.Client();

    client.ftp.verbose = true;

    try {
        // ftp connect
        await client.access(options);

        // print current remote dir
        const string = await client.pwd();
        log.info(string);

        const fileName = 'test.txt';
        const fullPath = './' + fileName;

        const stats = await fsStat(fullPath);

        if (stats.isFile()) {
            await client.upload(fs.createReadStream(fullPath), fileName);
        }
    } catch (err) {
        log.info(err);
    }
    client.close();
}
```

**Comment by patrickjuchli** [comment]
Isn't this a different error now? Did you have a timeout error before as well?

About your first post: In the console output, you can see that the client is closing right after the answer to PWD. The callback for fs.stat gets called later. Add some console.log statements on your own to verify that. That's why I suggested to only use one single paradigm to handle asynchronous operations.

Now, the second post: To me, this looks like a different error. Could you post the whole log output and not just the error? I'd like to see what happens before.

**Comment by patrickjuchli** [comment]
Do you still need help?
