### ISSUE TITLE
Can't resolve 'fs' 'net' 'path' 'tls'

### ISSUE THREAD

**Issue by pilz97** [patrickjuchli/basic-ftp#31]
Hello,

i get some errors when i try to use the Plugin..
`
ERROR in ./node_modules/basic-ftp/lib/ftp.js
Module not found: Error: Can't resolve 'fs' in '..\node_modules\basic-ftp\lib'
Module not found: Error: Can't resolve 'fs' in '..\src\app'
ERROR in ./node_modules/basic-ftp/lib/ftp.js
Module not found: Error: Can't resolve 'net' in '..\node_modules\basic-ftp\lib'
ERROR in ./node_modules/basic-ftp/lib/FtpContext.js
Module not found: Error: Can't resolve 'net' in '..\node_modules\basic-ftp\lib'
ERROR in ./node_modules/basic-ftp/lib/ftp.js
Module not found: Error: Can't resolve 'path' in '..\node_modules\basic-ftp\lib'
ERROR in ./node_modules/basic-ftp/lib/ftp.js
Module not found: Error: Can't resolve 'tls' in '..\node_modules\basic-ftp\lib'`

This is what I'm doing at the moment:
`const ftp = require("basic-ftp")
    const fs = require("fs")`

What I'm doing wrong?

Thank you

**Comment by patrickjuchli** [comment]
The library can't find standard Node.js modules.

Are you sure this has anything to do with this library? It doesn't seem to. Do you have the same problem with other libraries provided on npm?

**Comment by pilz97** [comment]
Thanks for your answer! 

When I remove the require everything works fine..

**Comment by patrickjuchli** [comment]
@pilz97, I don't know how to help you. This sounds like a problem with they way your project is set up. You need to provide much more details, maybe a repository I can have a look at. Otherwise I'll have to close this issue.

**Comment by pilz97** [comment]
This is my package.json

`{
  "name": "style-test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "basic-ftp": "git+https://github.com/patrickjuchli/basic-ftp.git",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}
`

do i have to install any other package?

**Comment by patrickjuchli** [comment]
Aha, you are creating a web application for the browser and try to use basic-ftp in the browser? `basic-ftp` doesn't work in the browser, only in a Node.js environment.

**Comment by pilz97** [comment]
Oh ok thank you!
