### ISSUE TITLE
Use `debug` module instead of `client.ftp.verbose`? 

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#35]
The `debug` module is the de-facto standard for logging these days.  It would be nice to be able to leverage that, rather than relaying on the ad-hoc system you currently have.

**Comment by broofa** [comment]
Also, this would avoid unpleasantness like, `[object Object]` showing up in the logs (caused by https://github.com/patrickjuchli/basic-ftp/blob/master/lib/ftp.js#L610)

**Comment by patrickjuchli** [comment]
I don't want a dependency on a specific logging library. "These days" being the operative word, I'm also sure there are other people using other things.

What this library should do, though, is make it possible to use such a library without too much hassle. Let's look into improving things here.

**Comment by patrickjuchli** [comment]
The example you pointed out definitely needs to be fixed. A tiny bit related to #37, where I'll have a look at error handling in general.

**Comment by broofa** [comment]
> I don't want a dependency on a specific logging library.

Fair enough.  I actually really like the minimal-dependency principal. (It has informed/driven much of my approach to `uuid` and `mime`).

Many libs allow for injection of a logging dependency via a `log` or `logger` option of some sort.  That makes sense.  The one thing I like about `debug` is the ability to create per-client categories. E.g. Each client could have it's own `ftp:<client_id>` category,  which is logged with a unique color to the console, and also filterable to a specific client... which is occasionally useful.   But, as you point out, I've found `debug` doesn't always play nice with other logging schemes so... yeah, I see your point.
