### ISSUE TITLE
Ad hoc error objects are problematic

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#37]
It appears you're constructing ad-hoc error objects - vanilla objects with an `error` property - and then throwing those in handler functions.  (E.g. building one [here](https://github.com/patrickjuchli/basic-ftp/blob/master/lib/FtpContext.js#L92), then rejecting [here](https://github.com/patrickjuchli/basic-ftp/blob/master/lib/ftp.js#L783)  and [here](https://github.com/patrickjuchli/basic-ftp/blob/master/lib/ftp.js#L828) I believe?)

This is problematic for a variety of reasons (no stacktrace info, breaks 3rd party logging code like bugtrag, etc.)

I'd suggest creating bonafide `Error` instances, and doing `instanceof Error` checks, rather than looking for the `error` property.

(BTW, thanks for putting this module together!  I've been struggling to get the node-ftp module to work properly, and it no longer appears to be maintained.  I'm hoping to use this module as a replacement.  I like what I see, but 'still working through a few rough spots.  I hope you don't mind me throwing a few issues you at you.)

**Comment by patrickjuchli** [comment]
I agree, let's address this for the next release.

**Comment by patrickjuchli** [comment]
Will be released in 3.0.0
