### ISSUE TITLE
parseControlResponse() will error on multibyte UTF8 characters

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#38]
In [_onControlSocketData()](https://github.com/patrickjuchli/basic-ftp/blob/master/lib/FtpContext.js#L247), data chunks are converted to Strings before concatenation, while prepending `_partialResponse`  on the next chunk.  This will lead to errors and/or exceptions if a data boundary falls on a multi-byte unicode character, however.

Instead, data should be processed as a byte stream, only converting to `String` once a complete line has been detected.  See [newline-based stream parser example](https://github.com/substack/stream-handbook#consuming-a-readable-stream).  Bonus: the nifty `unshift()` trick for pushing the partial data back onto the stream.)

**Comment by patrickjuchli** [comment]
Nice one, thanks!

**Comment by patrickjuchli** [comment]
`socket.setEncoding` should do the trick, no? Nodejs should take care of this internally.
