### ISSUE TITLE
Upload creates empty files - No Errors

### ISSUE THREAD

**Issue by medokin** [patrickjuchli/basic-ftp#4]
All my file are created but empty. Do you have an idea why this happens?

Code:
```js
        const client = new ftp.Client();
        client.ftp.verbose = true;
        try {
            await client.connect(config.host, config.port);
            if(config.tls) {
              await client.useTLS();
            }
            await client.login(config.username, config.password);
            await client.useDefaultSettings();
            await client.uploadDir(config.localRoot);
        }
        catch(err) {
            console.log(err);
        }
        client.close();
```

Log:
```
Data socket uses TLSv1.2
> STOR webapp-fastboot-8e75705c056d7ebc3694d2513c93c176.js
< 125 Data connection already open; Transfer starting.
< 226 Transfer complete.
> CDUP
< 250 CDUP command successful.
> PASV
< 227 Entering Passive Mode (51,4,149,110,39,23).
```

Features:
```
  'LANG' => 'EN*',
  'UTF8' => '',
  'AUTH' => 'TLS;TLS-C;SSL;TLS-P;',
  'PBSZ' => '',
  'PROT' => 'C;P;',
  'CCC' => '',
  'HOST' => '',
  'SIZE' => '',
  'MDTM' => '',
  'REST' => 'STREAM' 
```

Notes:
- Remote Server is Azure AppService (Windows)
- Disc has enough space (Works with FileZilla)
- Tried ASCII and BINARY mode, no change
- Tried UTF-8 and latin1 encoding

**Comment by patrickjuchli** [comment]
Looks like a bug to me, will have look.

**Comment by patrickjuchli** [comment]
I could reproduce some issues related to TLS when using the FTPS server provided by Azure AppService. These issues have been fixed in 2.6.2.

I did see error messages, though… I'd be interested how 2.6.2 works for you @medokin.

**Comment by medokin** [comment]
Thanks for response, but unfortunately it crashes now on first upload:


Full log
```
< 220 Microsoft FTP Service
> AUTH TLS
< 234 AUTH command ok. Expecting TLS Negotiation.
Control socket is using TLSv1.2
> USER ###
< 331 Password required
> PASS ###
< 230 User logged in.
> cwd /site/wwwroot/dist
< 250 cwd command successful.
> TYPE I
< 200 Type set to I.
> STRU F
< 200 STRU F ok.
> PBSZ 0
< 200 PBSZ command successful.
> PROT P
< 200 PROT command successful.
> MKD assets
< 257 "assets" directory created.
> CWD assets
< 250 CWD command successful.
> PASV
< 227 Entering Passive Mode (51,4,151,214,39,55).
> STOR assetMap.json
< 125 Data connection already open; Transfer starting.
Uploading (TLSv1.2)
{ error: { Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } }
Closing sockets.
```

**Comment by patrickjuchli** [comment]
I'm pretty sure this is an issue with TLS, there shouldn't be any problem without it. Are you willing to give this a quick try on your end (disabling TLS)? It's okay if not.

Can I have some details about your setup? What version of Node are you using? You're using this with the FTP server provided for Azure AppServices, right?

**Comment by medokin** [comment]
Node: 8.9.4 (current LTS)
Yes I'm using Azure AppService.

Disabling TLS is not an option, Azure requires it:

```
< 220 Microsoft FTP Service
> USER ###
< 534 Policy requires SSL.
{ code: 534, message: '534 Policy requires SSL.' }
Closing sockets
```

I can provide a test server where you can test/reproduce the issue, just need your contact.

**Comment by patrickjuchli** [comment]
Yes, that'd be interesting because my Azure AppService FTP seems to behave quite a bit different. It's patrickjuchli [at] gmail. I can't make promises how soon I can have look though, hope you understand.

**Comment by medokin** [comment]
Thanks, I have sent you an email. No hurry,

**Comment by patrickjuchli** [comment]
I couldn't resist. There is a new version 2.7.1 which "works on my machine (Mac)" for your server. I did some stress tests with lots of uploads and the fix make sense so I'm hopeful it's correct. Fingers crossed.

**Comment by medokin** [comment]
You did it! All files were uploaded correctly. Thank you for this library and the quick fix. 🎉

**Comment by jayaraut** [comment]
Hi, Can you explain the fix if it worked for me? I am having issue uploading to my FTP server . I can see the files have data but it is going as csv.empty instead csv file  on server (I am accessing server using FileZilla) and this is happening sometimes and only on prod server not in staging.
