### ISSUE TITLE
Better mechanism for handling control socket errors when no active task

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#43]
Managing the lifecycle of a client is a bit cumbersome at the moment.  The problem is that errors on the control socket are routed through the current `task.handler`.  (This is how data socket connections are handled as well, but isn't as big an issue there since data sockets are always created in the context of an upload or download task, so there's always a handler available to report the error through.)

Control sockets, unlike data sockets, are long-lived and can/do span multiple tasks.  As a result, a client may go for extended periods with no active task, during which time [socket errors get dropped on the floor](https://github.com/patrickjuchli/basic-ftp/blob/master/lib/FtpContext.js#L266-L268).  Leaving no documented way to know if, for example, there's a network disconnect or the remote server kills the connection.

I've worked around this for the moment by adding listeners to `client.ftp.socket` directly, but that feels a bit hacky, like I'm reaching into the internals of objects I'm not sure I should be touching.  It's not clear if this is expected or might change in the future.  This also requires adding the listeners if/when the socket is rebuilt.  (I've opted for just creating a new client each time, though, to avoid possible issues with unexpected client state hanging around.)

I'm not sure what the right solution is here, but something more intuitive/better documented would be helpful.  One possibility would be to have FtpContext inherit from EventEmitter, and forward socket events to its listeners, but I'm not sure how much I like that idea. It's adding complexity whereI feel like complexity should be getting removed.   (E.g. If the Ftp Client/context/control socket were all tied together as a single object/API, then it'd be easier to rationalize how error handling should work.)

**Comment by patrickjuchli** [comment]
Yes, your design observation is true. But I don't see yet how this makes the use cumbersome.

Assume you want to upload a whole directory. You'll have to handle errors during tasks anyway, e.g. reconnecting and resuming transfer if a connection fails. Between these tasks, it's possible that something happens as well, but you'll be notified of it by the following task failing. Your handling of the situation will be the same. You don't need an additional place handling errors in this case.

Should there be some additional error handling independent of tasks? I'm not 100% sure. I think it's interesting so say: Why should you handle an error of something you're not using? The answer to that might be to fix and prepare things so that the next task will work again. But why not let the following task fail and let its surrounding context handle the situation? That way you simplify the system considerably as you have only 1 place where you handle errors and it's close to the usage context.

In addition to this, I prefer short-lived lifecycles of everything unless absolutely necessary (e.g. performance) because it makes a system more stable – you instantiate things only when you need them. This library has been designed to connect, do some stuff and disconnect. I don't see a need in most cases to stay connected to an FTP server for longer periods of time without doing anything.

**Comment by broofa** [comment]
> Why should you handle an error of something you're not using?

The status of the connection is important, as it represents whether the server is available and ready to do work.  This is important not just from the perspective of our code, but also our UI.  We surface this to the user in a variety of ways both explicitly ("Robot is online") and more subtly (enabling/disabling certain UI features).

> you'll be notified of it by the following task failing

But by then you've lost the [important] root cause of the failure.  The task will error out with "can't write to closed socket", instead of "server closed connection" or "connection timed out".  The nature of that error may be important to the user ("Server offline" vs. "Network problems") or may inform the action needed to deal with it (retry immediately?  retry after delay?  halt the process?).  Regardless, at a minimum, it is certainly information that should be in the error log for diagnostic purposes.

> I don't see yet how this makes the use cumbersome

There are two code "smells" here for me:

1. Exceptions being silently discarded (in `_passToHandler`).  IMHO, this is *never* a good thing. When you catch an exception you either handle it gracefully, rethrow it, or throw a new error of some sort.  The one thing you don't do is drop it on the floor.  In the rare case where discarding an error makes sense, there should be really good comment block explaining the rational for it. 
2. Having to reach multiple levels "down" inside the `client` object to get at the socket object.  Because this isn't documented, there's no guarantee that path won't change, which means my code is now brittle. :-/

**Comment by broofa** [comment]
> I prefer short-lived lifecycles of everything

I would phrase this as "object lifecycles should mirror the lifecycles of what they represent".

This is probably getting a bit off topic, but I actually find it a little odd that `FtpContext` can reset it's socket connection.  By your own logic, shouldn't a context only survive as long as the connection it represents?  It would eliminate a lot of code for resetting state, removing socket listeners, etc.  :-)

> This library has been designed to connect, do some stuff and disconnect

I disagree.  If that were the case, you would close the control socket after each task, kind of how HTTP/1.0 worked before the introduction of `keep-alive`.  That it's possible to issue multiple tasks means connection errors in between tasks are a reality that needs to be dealt with.  Whether the timing between tasks is 10 msecs or 10 seconds or 10 minutes is just a matter of timing.

"Now we're just haggling over price", as they say. :-)

**Comment by patrickjuchli** [comment]
I agree that all of this is not nice and could be improved. I have to think about it.

But a connection doesn't tell you whether the server is reachable. Only timeout will tell, aka some kind of action like a ping.

**Comment by patrickjuchli** [comment]
I'd like to focus on your use-case to get a clearer picture of what you need.

Again, you can connect to an FTP server, disconnect your Wifi, reconnect it later and continue to interact with the server, no problem. The connection won't raise any error. If you actively want to track connectivity you have to try to send something at a short interval way below keep-alive to make this useful for a UI. In other words, you'll only notice it when doing something.

But it's of course possible that the server (or a router) closes the connection in which case you want to be notified independently of any task, is that correct? Do you see any other examples?

I assume that if a task *is* running and connection loss happens, you don't want to handle this error in 2 different places?

**Comment by patrickjuchli** [comment]
Here is a proposal:

Continue to follow the philosophy to let only tasks report errors because they are the only channel to report these for now. Breaking change: If an error occurs that closes the connection, *the client stays unusable (no reset) and remembers the reason*. The error could be logged immediately for debugging purposes. The next task will then fail with an exception and report something like: "Client is closed, the reason was X. Please instantiate a new context."

This would solve the issues you raised in this thread with minimal changes. It would also keep error handling in a single place that is close to the failing task.

**Comment by patrickjuchli** [comment]
As for reporting connectivity issues as soon as possible – this is really a thing the user has to solve by sending some simple command every few seconds as a probe.

**Comment by patrickjuchli** [comment]
Some more ideas:

Offer some kind of uncaught-exception-handler similar to Java that gets called if there is no active task. That way you won't get the same error reported in two places. This could be an "error" event emitted from `Client`.

**Comment by broofa** [comment]
> That's a surprising overstatement that late in our discussion. Is this library so infuriating?

No, not at all.  Quite the contrary, I really appreciate what you've put together here.  I apologize if that came across as critical - I made that comment before seeing your "Make FTPContext single use" commit.  (Like I said, I spent more time than I should have thinking about this, so didn't see it come in 🤷‍♂️.)

> If an error occurs outside of a task, the next task will receive it.

Yup, that makes sense.  The `_closingError` changes definitely help.

> Reconnecting is outside of the scope of this library

I'm still curious to get your thoughts on the `runTaskWithRetry()` code, above?  It's a little stale because of the recent commit, but it'd be helpful for me to understand what your solution to the reconnect+retry problem would look like.

**Comment by patrickjuchli** [comment]
Happy New Year @broofa – who would've thought we'd be writing about FTP in 2019. I sure haven't.

The line with `new Promise` looks too smart, I'm not sure I understand it completely. But in reality, would you really just retry single tasks? When thinking about retries, I find it helpful to start at the other end: At your specific use-case. What exactly will you retry if downloading the robot-files fails?

A first simple – and thus robust – solution would be to just try everything again once something fails. After that you may want to resume aborted transfers but I think that requires a bit more work (and complication and errors).

I'd just write that first solution down, as simple and stupid as possible.

**Comment by broofa** [comment]
Happy new year to you, too!  🎉

> who would've thought we'd be writing about FTP in 2019

Nothing ever dies on the internet I guess.  Unfortunately.  And, dear god, I didn't appreciate just how terrible the FTP protocol was prior to diving into this.  Thank god for HTTP and, more recently, HTTP2.  It's mind-boggling that it's taken this long for a protocol with well-thought out transaction framing over a single socket to gain traction.  Ah well... at least it's 2019 now.  😄 

> The line with new Promise looks too smart, I'm not sure I understand it completely

Yeah, sorry.  It's a little too "cute"... and, it occurs to me there's a simpler, non-recursive, async implementation that would be more readable.  I make take a stab at that t some point.

> But in reality, would you really just retry single tasks?

Yes.  If a download fails, all I want/need is to re-issue that same command.

> A first simple – and thus robust – solution would be to just try everything again once something fails

Yup, agreed.  To my mind each task should be treated as an atomic operation.  Either it succeeds or it fails.  There's no in-between condition (no "partial" downloads or uploads).  And if a task fails, then "retry" means, "start over from the beginning".

With this approach, retrying a task can be transparent to callers.  As long as the task resolves, the caller doesn't need to be concerned with whether it succeeded on the first try, or took three attempts.  The only need care whether it worked or didn't work.
