### ISSUE TITLE
client.download() should return Readable instead of being passed Writable

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#47]
Basically what the title says.   E.g. Typical usage should look like this:
```
client.download('some_file.path').pipe(some_writable_stream);
```

**Comment by patrickjuchli** [comment]
And change the way the whole rest of the API works with handling asynchronous tasks? Tasks return Promises, if they don't then what? `on("end")` again?

**Comment by broofa** [comment]
Sorry, I meant "resolve to", not "return".  So...
```
(await client.download('some_file.path')).pipe(some_writable_stream);
```

**Comment by broofa** [comment]
Ah... I think I see what you're getting at.  Your current approach allows for handling of dealing with partial transfers, right?  The promise may reject if there's a stream error, but the dataSocket is piped directly to the writableStream, so the partial data would be available there.

Whereas with what I'm proposing, things are a bit more problematic.  The logic for resolving/rejecting the promise is non-trivial, depending on the server control result value (among other things).  Basically you can't resolve until the transfer completes, which means the readable stream won't uncork until all the data has been received, which kind of defeats the purpose of having a stream.   And if there's an error, providing access to the partial data is a little more awkward, too.

Huh...  okay, so much for that idea.  😆
