### ISSUE TITLE
ftp.list returns wrong name if filename starts with a space

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#51]
**Describe the bug**
ftp.list trims spaces at the beginning of files. If a file is named `" test"`, basic-ftp will return `"test"` instead so not only the listing is broken, but any action on this file will fail.

FileZilla has no such problems.

**Which version of Node.js are you using?**
e.g. Node 11.9.0

**Additional context**
This is a Unix server with files that contain spaces at the beginning.

I think the bug is here:

https://github.com/patrickjuchli/basic-ftp/blob/92c9875609fb3c00b369475792fe41f2e5b1940c/src/parseListUnix.ts#L84

Replacing the call to `trim` with this should fix it (`trimEnd` cannot be used either since filenames can also have spaces at the end):

```js
const name = groups[21].replace(/[\t\n\r]*$/, '');
```

**Comment by patrickjuchli** [comment]
There shouldn't be CR or LF at the end of the line. Any reason you want to strip TAB? I'd just remove the `trim()` call.

**Comment by patrickjuchli** [comment]
I think there might be more issues with whitespace leading or trailing filenames in other methods. I will have a look.

**Comment by warpdesign** [comment]
No reason at all, removing the trim should be enough.

**Comment by patrickjuchli** [comment]
Just FYI: Leading and trailing whitespace is also one of the many weak points of the FTP protocol. I'm not sure all issues can be removed.

May I ask in what particular case you have whitespace trailing or leading a filename? I'm just asking out of interest as I've never encountered this at all.

**Comment by patrickjuchli** [comment]
Okay, as I suspected, pretty much all methods can't handle these files correctly. The only way to handle these in FTP is to always use the full, absolute path whenever they're specified. I will address this issue in another ticket because it involves quite a bit more work.

**Comment by patrickjuchli** [comment]
Just to show you the issues: You mention FileZilla. Can you delete a file that has leading white space? I can't.

**Comment by patrickjuchli** [comment]
I will move this discussion to #53
