### ISSUE TITLE
Question: sending another command why the previous one hasn't resolved yet

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#52]
I am working on an ftp client using a gui (see: https://github.com/warpdesign/react-ftp) and I need to be able to send ftp commands (for eg. to change/display a directory) while another one (for eg. a transfer) is already in progress.

Right now, sending a command while another is already in progress (for eg. calling client.list before a previous call to client.download resolves) throws an error. Which is logical since FTP doesn't allow multiple transfers at the same time.

What's the best way to use basic-ftp for my needs: do I need to instantiate a new client for each transfer? Or is there another way?

**Comment by patrickjuchli** [comment]
Yes, multiple clients is the way. FTP generally doesn't allow concurrent commands being sent at the same time, the protocol doesn't work like that. It's always request A, response A, request B, response B, maybe response B2.

**Comment by warpdesign** [comment]
Ok, thanks for the answer!
