### ISSUE TITLE
Support filenames with leading whitespace

### ISSUE THREAD

**Issue by patrickjuchli** [patrickjuchli/basic-ftp#53]
This library doesn't work with filenames that have leading or trailing whitespace. This is one of these typical FTP protocol shortcomings and many clients don't handle these correctly – at least not in all cases.

The way to address this is to always use the full, absolute path. For example, when getting the size of such a file, using `SIZE[SPACE][SPACE]test.txt` won't work. Quotes also won't work. You have to use `SIZE /absolute/path/to/ test.txt` or whatever the path is.

The problem with that is that people usually use relative paths. So we'd have to always get the path of the current working directory first.

**Comment by patrickjuchli** [comment]
I believe handling leading whitespace is possible. Not sure about trailing whitespace.

**Comment by patrickjuchli** [comment]
See FileZilla for example: It correctly shows leading spaces in file listings but you can't do anything with them. Deleting or renaming won't work.

Transit (by Panic) is sometimes doing a better job here. But it doesn't cover all cases as well.

**Comment by warpdesign** [comment]
I'd suggest to let size/delete/... as is and mention in the docs (maybe having a section specific to these spaces problems) these problems and the possibles solutions.

When writing my app I noticed that using relative spaces led to problems if (leading) spaces were used and decided to take care of always use absolute paths myself.

**Comment by patrickjuchli** [comment]
This topic is one of the reasons you shouldn't use FTP today. That's why I have an advisory section right at the beginning of the README. This is one of the few libraries that openly warns about its technology :) The reason this library does exist is because FTP still does exist out there and I needed something reliable to use it with.

I think we can tackle the _leading_ whitespace thing but I can't give you a timeframe.

**Comment by patrickjuchli** [comment]
In 3.3.0
