### ISSUE TITLE
EISCONN error after failed authentication (Error 530)

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#55]
After a failed login attempt when calling `access` (wrong credentials for example), basic-ftp will throw an `FTPError 530`.

Any subsequent attempt to login with the correct credentials using `access` will throw an `EISCONN` Error.

So it appears that a new `Client` has to be created in order to login after an error 530 has been thrown?
Is it right?

**Comment by warpdesign** [comment]
Looking at the source code it seems that the access method does three things:
 - connect
 - useTLS
 - login
 - useDefaultSettings
My guess is that when login fails, the login method throws an error, so any subsequent calls to access will attempt to connect again and it has already been done.

**Comment by patrickjuchli** [comment]
Interesting. Yes, right now you should close the current client and instantiate a new one. Or you can call these methods by yourself and handle the login error – these are also public API.

**Comment by patrickjuchli** [comment]
I guess `access` should fail completely if any of its parts fail. So in your case, it should automatically disconnect again without closing the client.

**Comment by warpdesign** [comment]
That's what I did: I now call login/useDefaultSettings when an error 530 has been received.

Note: I guess these APIs should be added to the readme if they are public. I thought it was private.
