### ISSUE TITLE
Suggestion: Pre compile to javascript

### ISSUE THREAD

**Issue by elpeleq42** [patrickjuchli/basic-ftp#57]
Please distribute this module as javascript aswell as typescript. I simply HATE dealing with typescript in every way.

Adding a folder with code already in javascript within src would be really helpful

**Comment by patrickjuchli** [comment]
The module is already delivered/compiled to Javascript.

When you `npm install basic-ftp`, your `node_modules`  will contain the directory `basic-ftp` which in turn only holds a single directory `dist`. In there, you'll find Javascript files and type definitions. No Typescript source is delivered. The dist folder looks something like:

```
Client.d.ts
Client.js
FileInfo.d.ts
FileInfo.js
...
```

In your project, you can then use Javascript or Typescript, anything works. So in a Javascript project you simply use:

```
const { Client } = require("basic-ftp")
const c = new Client()
...
```

**Comment by patrickjuchli** [comment]
Nothing changes at all for consumers of this library. That is why the switch to Typescript hasn't been marked by a major version change.

**Comment by elpeleq42** [comment]
I knwo that but since I can't make node.js' "npm install" command work for some reason(Tried everything already), it is a problem for me...

**Comment by patrickjuchli** [comment]
In `package.json` you can see the package scripts. Use `npm run buildOnly` to compile the source to Javascript, the result will be in a directory called `dist`.

**Comment by patrickjuchli** [comment]
What the status on this?

This source repository won't hold the compiled Javascript files as well. Please try to fix your development environment, having `npm install` work correctly is a basic requirement of this library.
