### ISSUE TITLE
Question about download/upload API

### ISSUE THREAD

**Issue by warpdesign** [patrickjuchli/basic-ftp#58]
I am porting my ftp client so that it's now using basic-ftp instead of [node-ftp](https://github.com/mscdex/node-ftp).

Everything is working ok so far but it seems the download API differs in that node-ftp has a get API that's basically:

```js
client.get(remotePath, callback(err, readableStream))
```

So I'm getting a `readableStream` that I can pipe through a `writetableStream` I create myself.

The good thing about that is that I can even download something from an FTP server and directly pass it through to the put method of another FTP client with the put API:

```js
client.get(remotePath, (err, readableStream) => {
  if (!err) {
    client2.put(readableStream, remotePath);
   }
});
```

With basic-ftp, the download API needs a `writableStream` instead of a `readableStream` so this isn't possible anymore.

I briefly looked at the source code but couldn't find an easy to get a `readableStream` when downloading something. Is it possible without much work?

**Comment by warpdesign** [comment]
After some tests, it seems it's as easy as using ftp.dataSocket as a readable stream.

Any chance of having an API for downloading that doesn't require a writeStream (that doesn't call ftp.dataSocket.pipe(destination) and resolves with `ftp.dataSocket`?

**Comment by patrickjuchli** [comment]
The central use-case for this library is to download data to a file. For that, you use "fs.createWriteStream()", hence the need for a writable stream. Alternatively you can also provide stdout. When getting a directory listing, data is written into a string for example.

If you want to read again from the stream, you just provide a duplex or transform stream. 

Be careful with piping data yourself from dataSocket – I'm not sure how reliable that actually is. Isn't it possible that you'll start piping too late and miss some data? Not sure. Outside of the scope of this library, I can't provide support for this as it reaches into internals.

**Comment by patrickjuchli** [comment]
So downloading a file looks like this:

```js
const dest = fs.createWriteStream("myLocalFile");
const response = await client.download(dest, "myRemoteFile");

or logging to console:
const response = await client.download(process.stdout, "myRemoteFile");
```

**Comment by warpdesign** [comment]
I think passing a readStream would allow both use cases:
 - you may pipe it to a writeStream created using fs.createWriteStream() in order to write it to a file
 - or pass it to another function that expects a readStream as a source

As it is now, I'm stuck if I want to call a method that expects a readStream.

**Comment by warpdesign** [comment]
> So downloading a file looks like this:
> 
> ```js
> const dest = fs.createWriteStream("myLocalFile");
> const response = await client.download(dest, "myRemoteFile");
> 
> // or logging to console:
> const response = await client.download(process.stdout, "myRemoteFile");
> ```

What if I want to send the client.download() stream and pass it to client2.upload()?

**Comment by patrickjuchli** [comment]
You are definitely not stuck. Again, you need to pass a writable stream that is also readable. Here is an example with Transform stream from "streams".

```js
const transform = new Transform({
  transform(chunk, encoding, callback) {
    // Do anything here
    callback(null, chunk);
  }
});
await client.download(transform, "bla.json")
transform.pipe(process.stdout)
```

Passing a readable stream won't work because the download function needs to write to it, not read from it. You probably want the download function to **return** a readable stream. But it doesn't do that because it returns the Promise when the whole operation is done. And this doesn't just depend on whether the data transfer is done but also if the server confirmed it.

**Comment by patrickjuchli** [comment]
Here is a complete example that downloads from one client, compresses on the fly and uploads to another:

```
const ftp = require("../dist/index");
const zlib = require('zlib');

example();

async function example() {
    const c1 = new ftp.Client();
    const c2 = new ftp.Client();
    try {
        await c1.access({
            host: "somewhere",
            user: "someone",
            password: "ohno",
            secure: true,
        });
        await c2.access({
            host: "somewhere",
            user: "someone",
            password: "ohno",
            secure: true,
        });

        const zipper = zlib.createGzip();
        const p1 = c1.download(zipper, "bla.json")
        const p2 = c2.upload(zipper, "bla.zip")
        await Promise.all([p1, p2])
    }
    catch(err) {
        console.dir(err);
    }
    c1.close();
    c2.close();
}
```

**Comment by warpdesign** [comment]
Oh, thanks, I hadn't thought about transforms!

That said, I definitely cannot wait for the download to be over:

```js
const transform = new Transform({
  transform(chunk, encoding, callback) {
    // Do anything here
    callback(null, chunk);
  }
});
// don't wait for the download to be over before passing it
client.download(transform, "bla.json")
transform.pipe(process.stdout)
```

Otherwise both transfers won't happen in parallel.

**Comment by patrickjuchli** [comment]
Yep, but the complete example above is parallel.

**Comment by alemens** [comment]
This code below it works, but I commented `client.close();` to avoid the error `(node:42413) UnhandledPromiseRejectionWarning: Error: Client is closed` 

and if I use `await` server give time out @warpdesign 

So I do not know where to use `client.close();`

@patrickjuchli could you help here?

```javascript
const ftp = require("basic-ftp");
const { Transform } = require('stream');
const fs = require("fs");

downloadFtp()

async function downloadFtp() {
  const client = new ftp.Client();
  client.ftp.verbose = true;

  try {
    await client.access({
      host: "host",
      user: "user",
      password: "password",
      secure: false
    });
    await client.ensureDir("OUT");
    const listOut = await client.list("OUT");
    var lastRemoteOut = listOut.pop().name;

    const lowCaseTransform = await new Transform({
      transform(chunk, encoding, callback) {
        this.push(chunk.toString().toLowerCase());
        callback();
      }
    });

    client.download(lowCaseTransform, lastRemoteOut);
    lowCaseTransform.pipe(fs.createWriteStream("./public/OUT.txt"));
  }
  catch (err) {
    console.log(err);
  }
  // client.close();
}

exports.downloadFtp = downloadFtp;
```

###### Thank you!


> Oh, thanks, I hadn't thought about transforms!
> 
> That said, I definitely cannot wait for the download to be over:
> 
> ```js
> const transform = new Transform({
>   transform(chunk, encoding, callback) {
>     // Do anything here
>     callback(null, chunk);
>   }
> });
> // don't wait for the download to be over before using transform.pipe()
> client.download(transform, "bla.json")
> transform.pipe(process.stdout)
> ```
> 
> Otherwise both transfers won't happen in parallel.

**Comment by alemens** [comment]
# Solved!
```
const ftp = require("basic-ftp");
const { Transform } = require('stream');
const fs = require("fs");

downloadFtp()

async function downloadFtp() {
  const client = new ftp.Client();
  client.ftp.verbose = true;

  try {
    await client.access({
      host: "host",
      user: "user",
      password: "password",
      secure: false
    });
    await client.ensureDir("OUT");
    const listOut = await client.list("OUT");
    var lastRemoteOut = listOut.pop().name;

    const lowCaseTransform = await new Transform({
      transform(chunk, encoding, callback) {
        this.push(chunk.toString().toLowerCase());
        callback();
      }
    });

    lowCaseTransform.pipe(fs.createWriteStream("./public/OUT.txt"));
    await client.download(lowCaseTransform, lastRemoteOut);
  }
  catch (err) {
    console.log(err);
  }
  client.close();
}

exports.downloadFtp = downloadFtp;
```

**Comment by aurelien0intent** [comment]
Hi @patrickjuchli, does Transform stream work with downloadTo API ?

When I try to use it, transfer never trigger the "onDataDone" function. But when I use Writable stream, it's work.
