### ISSUE TITLE
list returning wrong data

### ISSUE THREAD

**Issue by yuriolive** [patrickjuchli/basic-ftp#61]
**Describe the bug**
I'm trying to get a list of files from my ftp server. The ftp server is running on a EC2 instance Ubuntu 18.04.1 with vsftpd version 3.0.3 (ami-0ac019f4fcb7cb7e6). My code runs in a Ubuntu 18.04.2 machine. The list seems to be wrong, I used other ftp server to test (https://dlptest.com/ftp-test/) and worked fine but I really don't know why the ftp I just created is getting wrong info.

**Example code**
`const list = await client.list();`

**Console output**

	[  
	   {  
	      "name":"1001         4096 Feb 25 19:03 .",
	      "type":1,
	      "size":1001,
	      "permissions":{  
	         "user":0,
	         "group":0,
	         "world":0
	      },
	      "hardLinkCount":0,
	      "link":"",
	      "group":"",
	      "user":"",
	      "date":"drwxr-xr-x 2"
	   },
	   {  
	      "name":"65534        4096 Feb 25 18:55 ..",
	      "type":1,
	      "size":65534,
	      "permissions":{  
	         "user":0,
	         "group":0,
	         "world":0
	      },
	      "hardLinkCount":0,
	      "link":"",
	      "group":"",
	      "user":"",
	      "date":"dr-xr-xr-x 3"
	   },
	   {  
	      "name":"1001          487 Feb 25 19:03 package.json",
	      "type":1,
	      "size":1001,
	      "permissions":{  
	         "user":0,
	         "group":0,
	         "world":0
	      },
	      "hardLinkCount":0,
	      "link":"",
	      "group":"",
	      "user":"",
	      "date":"-rw------- 1"
	   }
	]

**Which version of Node.js are you using?**
Node 8.10.0

**Comment by yuriolive** [comment]
I detected that the library is wrong detecting that I'm using DOS-style directory listing, that's why is parsing wrong. If I change:

	const availableParsers = [
	    dosParser,
	    unixParser
	];

to:

	const availableParsers = [
	    unixParser,
	    dosParser
	];

everything works fine.

**Comment by patrickjuchli** [comment]
Looks like a bug to me, thanks for reporting.

Could you post the original list data? If you use `client.ftp.verbose` it should appear right before the console output you posted above. I can then use that list data to fix the style-detection.

**Comment by yuriolive** [comment]
Connected to 18.212.15.63:21
	< 220 (vsFTPd 3.0.3)
	> AUTH TLS
	< 234 Proceed with negotiation.
	Control socket is using: TLSv1.2
	Login security: TLSv1.2
	> USER test
	< 331 Please specify the password.
	> PASS ###
	< 230 Login successful.
	> TYPE I
	< 200 Switching to Binary mode.
	> STRU F
	< 200 Structure set to F.
	> PBSZ 0
	< 200 PBSZ set to 0.
	> PROT P
	< 200 PROT now Private.
	> CWD uploads
	< 250 Directory successfully changed.
	Trying to find optimal transfer strategy...
	> EPSV
	< 229 Entering Extended Passive Mode (|||9453|)
	Optimal transfer strategy found.
	> LIST -a
	< 150 Here comes the directory listing.
	Downloading from 18.212.15.63:9453 (TLSv1.2)
	< 226 Directory send OK.
	drwxr-xr-x    2 1001     1001         4096 Feb 25 19:03 .
	dr-xr-xr-x    3 1001     1001         4096 Feb 25 18:55 ..
	-rw-------    1 1001     1001          487 Feb 25 19:03 package.json

**Comment by patrickjuchli** [comment]
Fixed in 3.4.2
