### ISSUE TITLE
`parseControlResponse` does not handle tokens without a message correctly

### ISSUE THREAD

**Issue by trs** [patrickjuchli/basic-ftp#62]
**Describe the bug**
The `parseControlResponse` expects a token as either `nnn ` or `nnn-`. This falls apart when the server sends just the code without a message `nnn ` since it is trimmed and would become `nnn`.

The `connect` message is never resolved since the `handle` callback is never called.

**Example code**
```ts
async function doAThing() {
  await ftpClient.connect();
}
```

**Console output**
```
    < 220-
    220-This is an example message

    < 220-
    < 220-You better not use this ftp server for evil
    220-
    220-OR ELSE!
    220-
    220 // <--- NO MESSAGE

// Hangs
```

**Which version of Node.js are you using?**
```
$ node -v
v11.9.0
```

**Comment by trs** [comment]
This may be caused from the closing token not having a message associated with it, so `220` does not match `220 `.

**Comment by trs** [comment]
I can confirm, this was caused by a closing token without a message (`220`).

Here's a PR that fixes that: https://github.com/patrickjuchli/basic-ftp/pull/63

**Comment by patrickjuchli** [comment]
In 3.4.3
