### ISSUE TITLE
"Can't open data connection in passive mode: " error should throw Error, not String

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#65]
https://github.com/patrickjuchli/basic-ftp/blob/master/src/Client.ts#L693 is passing `reject()` a string.  It should be an Error instance.

**Comment by broofa** [comment]
Too bad tslint's `no-string-throw` rule didn't catch this.

**Comment by patrickjuchli** [comment]
In 3.4.4

**Comment by broofa** [comment]
Awesome, thank you!
