### ISSUE TITLE
Add documentation of `FileInfo`

### ISSUE THREAD

**Issue by gilles-crealp** [patrickjuchli/basic-ftp#67]
It could be useful to have in the documentation that `FileInfo` dispose of `isFile`, `isDirectory` & `isSymbolicLink`.

**Comment by patrickjuchli** [comment]
What do you mean by "dispose of", are these not working for you?

**Comment by gilles-crealp** [comment]
Sorry, I'm not an english native speaker.

Yes, it's working. But I had to dig in the code to find these properties: they are not in the documentation.

**Comment by gilles-crealp** [comment]
> What do you mean by "dispose of"

Now that I've used Google Translate, the use of "dispose of" was absolutely not correct. I mean that "`FileInfo` **have** `isFile`, `isDirectory` & `isSymbolicLink`".

**Comment by patrickjuchli** [comment]
Ah, no problem. Yes, documentation would be good.

**Comment by patrickjuchli** [comment]
Linking to the the file at least, good enough for now.
