### ISSUE TITLE
Added basic-ftp for webpack

### ISSUE THREAD

**Issue by scarletsky** [patrickjuchli/basic-ftp#70]
Hello, thanks for your great library. It helps me a lot to upload files to my ftp server.
I create a webpack plugin for your library:

https://github.com/scarletsky/webpack-basic-ftp-plugin

When using this plugin, it will automatically upload directory to target ftp server in the `done` hooks.

Hopes it will help someone.

**Comment by patrickjuchli** [comment]
Great! 

Small hint: Move `client.close` after the `try-catch` clause. The exception might be an FTPError that doesn't close the client automatically. In your current code, the client will then stay connected.

**Comment by scarletsky** [comment]
Thanks for your tips.
What happen if I call `client.close` when `client.access` failed ?

**Comment by scarletsky** [comment]
https://github.com/scarletsky/webpack-basic-ftp-plugin/commit/d6dc921424a987e61b13fac69626dbb6fa26dc97

Fixed. Thanks for your tips!
