### ISSUE TITLE
Upload Function

### ISSUE THREAD

**Issue by oniej** [patrickjuchli/basic-ftp#71]
Hi, there code that I've been working on, and have a problem with using the upload.
the standard code is
`await client.upload(fs.createReadStream("README.md"), "README.md")`
the `fs.createReadStream("README.md")` is the file that is already at the directory

but on the code that I'm working on is generated on the javascript like this:
` const os = require('os');`
`const output = []`
`const data = [{subject:'Math', grade: 85},{subject:'Art', grade: 80},..]`
 ` data.forEach((d) => {`
       ` output.push(`
         `   d.subject+ "\t"`
       `     + d.grade+ "\n");`
`    });`
`var dataTXT = output.join(os.EOL);`
`await client.upload(dataTXT , "filename.txt")`

the problem is, the file that is sent was empty.

is there another way of implementing it, or I have to use `fs.createReadStream`
but there is no file/data that that is can provide because is still on the code.
And I can't do `fs.writeFile` because of this code will be launch of a server later on.

**Comment by oniej** [comment]
And I'm getting an error:
` source.pipe(dataSocket).once("finish", () => {
                       ^
TypeError: source.pipe is not a function`

**Comment by oniej** [comment]
I found a way,

it's possible to use fs.writeFile then fs.createReadStream like this:

`fs.writeFile("filename.txt", dataTXT, function (err) {
                if (err) {
                    console.log('error writing file', err);
                } else {
                    console.log('writing file succeeded');
                }
            })`

`await client.upload(fs.createReadStream('filename.txt'), 'filename.txt');`

this is working...

**Comment by patrickjuchli** [comment]
There is another way, let me show you.

The upload function accepts any readable stream, see the documentation of the [Client API](https://github.com/patrickjuchli/basic-ftp#client-api). Node.js uses streams a lot, see here some examples of [what a readable stream is](https://nodejs.org/api/stream.html#stream_readable_streams).

Now, in your case you have string. So you need to make the content of this string available through a readable stream. Here is how you'd do that yourself:

```js
const { Readable } = require("stream")
const myStream = new Readable()
myStream.push("this is my string,")
myStream.push("and there's even more,")
myStream.push("that's how streams work.")
myStream.push(null)  // Indicates the end of this stream.
```

As always, there is also an existing library for this, see [string-to-stream](https://www.npmjs.com/package/string-to-stream). Its source code is 23 lines, you should [read it](https://github.com/feross/string-to-stream/blob/master/index.js).

Hope that helps, happy streaming.
