### ISSUE TITLE
TLS certificates

### ISSUE THREAD

**Issue by xnerhu** [patrickjuchli/basic-ftp#72]
Hello. I want to support TLS/SSL certificates. I am aware of the secureOptions in ```client.access()```. I get client certificate by `client.ftp.socket.getPeerCertificate(true)`. I have raw property, which is client certificate in DEM format and pubkey. But what can I do with these to make TLS work properly.

**Comment by patrickjuchli** [comment]
I don't quite understand your question.

TLS is already working properly. Do you mean you want to do certificate pinning with a custom certificate that has not been issued by an official certificate authority but e.g. yourself? If yes, google "certificate pinning" for socket clients.

**Comment by patrickjuchli** [comment]
You don't have to do anything to "support TLS certificates" when connecting using TLS to an endpoint that has a certificate issued by an official certificate authority.

**Comment by patrickjuchli** [comment]
@xnerhu, let me know if this is resolved.

**Comment by xnerhu** [comment]
Thank you for your response. It's not resolved yet, but I am on good way.
