### ISSUE TITLE
Project compilation fails after adding basic-ftp at node_modules/basic-ftp/dist/ProgressTracker.d.ts(22,37)

### ISSUE THREAD

**Issue by dbykadorov** [patrickjuchli/basic-ftp#74]
**Describe the bug**

Project compilation fails after adding basic-ftp:

> node_modules/basic-ftp/dist/ProgressTracker.d.ts(22,37): error TS1039: Initializers are not allowed in ambient contexts.

Typescript version 2.8.3, basic-ftp version 3.5.0

**Comment by patrickjuchli** [comment]
Did you try compiling with a newer version of Typescript?

**Comment by dbykadorov** [comment]
@patrickjuchli do you mean any certain version or the latest one?

**Comment by patrickjuchli** [comment]
Let’s start with the latest version of Typescript, 3.5.1.

**Comment by patrickjuchli** [comment]
Resolved?

**Comment by dbykadorov** [comment]
@patrickjuchli thank you for consultation. I have another issues with TS3.5 in my code.
