### ISSUE TITLE
Is it possible to use this library with a proxy?

### ISSUE THREAD

**Issue by lukewlms** [patrickjuchli/basic-ftp#76]
I need to make an FTP call with a fixed IP, so I'm using [Fixie Socks](https://elements.heroku.com/addons/fixie-socks).

I evidently have the proxy socket opening with socksv5, but when trying to access the FTP site I get:

`Error: connect ECONNREFUSED 127.0.0.1:21`

Here's the code:

```typescript
        SocksV5.connect(socksV5ConnectArgs, async (socket: any) => {
          try {
            const ftpOptions = {
                secureOptions: { socket },
                user: FTP_USERNAME,
                password: FTP_PASSWORD,
              }

            const ftpClient = new PromiseFtp();

            // Next line fails
            const ftpPromiseResult = await ftpClient.access(ftpOptions);

            const listResult = await ftpClient.list();
            console.log(listResult);
          } catch (err) {
            console.log(err);
          }
        });
```

I've tried a number of other combinations to try and get this to work, but there's no indication if I am or am not passing the socket correctly along with the username/password combo, and I don't know what exactly is failing because the error message is vague.  Is there a way to make this work?  Thank you!

**Comment by patrickjuchli** [comment]
There is no explicit support for proxies yet, especially not Socks5 with possibly additional authentication. There are no plans to add support. If you have a suggestion via pull request I'll be happy to have a look.
