### ISSUE TITLE
PASV mode

### ISSUE THREAD

**Issue by Ethan-Yao** [patrickjuchli/basic-ftp#77]
Hello, I use the version 3.6.0. 
When download or upload, it default EPSV mode. 
The firewall is not allow the other port. So I will receive the timeout.
How can I checkout to PASV mode ? ` ipFamily ` can be work?

Now, I am using the version 2.11.0, it work!

Thank you!

**Comment by Ethan-Yao** [comment]
I am using the version 2.11.0, it work!

**Comment by patrickjuchli** [comment]
You want to disable EPSV and force the client to use PASV, am I understanding you correctly? You can't do this at the moment but I'll look into it.

**Comment by Ethan-Yao** [comment]
Yes.  Thank you very much. 
I will wait for the new version.

**Comment by patrickjuchli** [comment]
This is still a bit semi-official but with 3.7.0 you can now do this to force PASV and ignore EPSV:

```js
const client = new ftp.Client(2000);
client.prepareTransfer = ftp.enterPassiveModeIPv4
```

**Comment by wavded** [comment]
Also just ran into this issue, thanks for the fix!
