### ISSUE TITLE
cli.upload transfers file but does not resolve

### ISSUE THREAD

**Issue by GigiSan** [patrickjuchli/basic-ftp#8]
Hello there,

I have a webapp which needs to upload some excel files to a remote plain FTP server.

Everything seems to work fine, except for the fact that using `client.upload` as a promise transfers the file correctly (which I can then see on the server) but does not resolve after that and just hangs there until  the timeout time is eventually reached.

This is the code I'm using:
```javascript
// cli, stream_wb_translate, remoteFilename are defined in a higher scope
cli = new FTP.Client(30000);
cli.ftp.verbose = true;
return cli.access({
  host: ...,
  user: ...,
  password: ...,
  secure: false
})
.then((response) => {
  return cli.cd(path)
  .then((response) => {
    return cli.upload(stream_wb_translate, remoteFilename); // this hangs until timeout but the file is transferred
  })
  .then((response) => {
    // never reached
    return yetSomeOtherPromiseStuff();
  })
  .catch((e) => {
    throw e;
  });
})
.then(() => {
  // all good, never reached
})
.catch((message) => {
  // always reached
  return reject({
    msg: 'Send failed', 
    detail: errorUtils.parseFromPromise(message)
  });
})
.finally(() => {
  if (cli) {
    cli.close();
  }
});
```

Most probably I'm doing something wrong, but despite step-debugging I can't see it.

Thanks in advance for your attention. Have a nice day! ☺

**Comment by patrickjuchli** [comment]
The nested promises make reading a bit difficult, you can write this also as follows:

```
cli.access({ ... }}
.then(() => cli.cd(path))
.then(() => cli.upload( ... ))
.then(() => console.log("done"))
```

**Comment by patrickjuchli** [comment]
`cli.ftp.verbose` is set to true – what's the output?

**Comment by patrickjuchli** [comment]
This code below works on my end. Does this accurately represent your case? What version of Node.js do you have? The next step would be to reproduce this with Filezilla Server but I can't do this right now.

```js
const { Readable } = require('stream')

const buffer = Buffer.from("hello", 'utf-8')
const readable = new Readable()
readable._read = () => {}
readable.push(buffer)
readable.push(null)
        
client.access({ ... })
.then(() => client.upload(readable, "test.txt"))
.then(() => client.close())
```

**Comment by GigiSan** [comment]
My Node.js version is `v8.10.0`, my npm version is `v5.8.0`

The code you posted represents my case, the only difference could be that I usually return the methods inside the `.then` blocks, like this:

```
const client = new ftp.Client();
client.access({ ... })
.then((response) => return client.upload(readable, "test.txt"))
.then((response) => return client.close())
```

**Comment by patrickjuchli** [comment]
I have run my example code above on Windows 10 with the latest FileZilla FTP Server (0.9.60 beta), using Node 8.11.1. Everything works fine. Did you run the exact same code I posted above? Could you upgrade to the latest LTS 8.11.1 as well? Can you try another FTP Server to see if the problem is related to FileZilla?

**Comment by GigiSan** [comment]
I found the issue. My problem was I didn't `push(null)` to the end of the readable stream. 

By doing so everything works fine. Although I wonder why is that needed? 

I apologize for the issue, obviously not your fault.
Thanks for the patience. Have a nice day! ☺

**Comment by patrickjuchli** [comment]
Ah, I suspected this to be the case. With `push(null)` you signal the end of the stream. Otherwise the upload function continues to wait for more data.
