### ISSUE TITLE
Question: Do you have any tips for debugging the initial connection? 

### ISSUE THREAD

**Issue by k1rked** [patrickjuchli/basic-ftp#80]
Do you have any tips on debugging a timeout on the initial connection, during `client.access`?

I'm using `client.ftp.verbose = true;`, but the only feedback I get:

```
Connected to [REDACTED]
Error: Timeout (control socket)
    at Socket.socket.once ([REDACTED]\node_modules\basic-ftp\dist\FtpContext.js:269:58)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

I'm new to the library (great work, btw) and have used it successfully for a server I control, but I've been struggling to connect to another not in my control. I'm not doing much yet, just:

```
    try {
        await client.access(options);
        console.log(await client.list());
    } catch (err) {
        console.log(err);
        client.close();
    }
    client.close();
```

**Comment by patrickjuchli** [comment]
It's connected but you're not even receiving a welcome message from the FTP server? No idea, sorry. Try accessing it from a different network, try another FTP server, difficult to say.

**Comment by k1rked** [comment]
OK. Thanks. Using other tools I've been able to find that the issue is that the remote server has a self signed certificate. I tried checking it with the call back in secureOptions, but it doesn't ever get that far in this scenario (it does in good certificate scenarios obviously). 

```
...
   port: 990,
   secure: true, //also tried false here
   secureOptions: {
      checkServerIdentity(servername, cert) {
             console.log('does not log');
        },
     },
...
```
