### ISSUE TITLE
how to restart a download task using startAt?

### ISSUE THREAD

**Issue by chary1n** [patrickjuchli/basic-ftp#82]
my code:
```
if (fs.existsSync(pathStr)){
   start_at_size = fs.statSync(pathStr).size;
 }
let fileStream = fs.createWriteStream(pathStr, {start: start_at_size});
await this.ftpClient.download(fileStream, remote_path, start_at_size);
```
after that `trackProgress` doesn`t work and never get promise resolve back. 
maybe i understood in a wrong way, 
could you please give a demo code about the feature? thanks anyway

**Comment by patrickjuchli** [comment]
Interesting, I tried the following code which is running correctly:

```js
// Upload a local file called "continue.txt" that contains "Hello world".
await client.upload(fs.createReadStream("continue.txt"), "continue.txt")
// Download the uploaded file again to another file "continue_test.txt"
const localFilename = "continue_test.txt"
await client.download(fs.createWriteStream(localFilename), "continue.txt")
// Now, append to the existing file the content of "continue.txt" again but starting at position 6
const startAt = fs.statSync(localFilename).size;
await client.download(fs.createWriteStream(localFilename, { start: startAt, flags: "r+" }), "continue.txt", 6)

// The file "continue_test.txt" should contain "Hello WorldWorld"
```

Does this work on your end as well? The only difference to your example is `flags: "r+"` but that shouldn't affect resolution of Promises.

**Comment by patrickjuchli** [comment]
If this still doesn't work, could you enable logging `client.ftp.verbose = true` and post the whole log text here (without specific host)?

**Comment by chary1n** [comment]
wow. the flags: "r+" is the point!!! without "r+",i can't open my file after download finish.it overwrites.
thanks a lot.Now i need to study on how to upload file using startAt.I believed that i can implement it reference download function. It`s an awesome library, thanks again.

**Comment by patrickjuchli** [comment]
Uploading doesn't offer an offset. FTP knows about appending data to a file using the FTP command `APPEND`. This library doesn't offer that yet.

**Comment by patrickjuchli** [comment]
See #83

**Comment by patrickjuchli** [comment]
With 4.3.0:

```js
const startAt = fs.statSync(localFilePath).size
await client.downloadTo(localFilePath, remoteFilePath, startAt)
```
