### ISSUE TITLE
Resume upload

### ISSUE THREAD

**Issue by straussCS** [patrickjuchli/basic-ftp#84]
Is it possible to resume an previously cancelled upload using APPEND? If not, are you planning to add such feature?

**Comment by patrickjuchli** [comment]
The latest version has `client.append()`, see the [README.md](https://github.com/patrickjuchli/basic-ftp/blob/master/README.md#client-api)

**Comment by patrickjuchli** [comment]
With 4.3.0:

```js
const uploadedBytes = await client.size(remoteFilePath)
await client.appendFrom(localFilePath, remoteFilePath, { localStart: uploadedBytes })
```
