### ISSUE TITLE
Support Buffer ulpoad

### ISSUE THREAD

**Issue by sunptech** [patrickjuchli/basic-ftp#85]
Please add support for Buffer upload. 

```
let data = Buffer.from('uploaded random text', 'utf8');

await client.upload(data, "foot.txt)
 ```

**Comment by patrickjuchli** [comment]
There are many tutorials on how to create a stream based on a Buffer. Here is one https://www.google.de/amp/derpturkey.com/buffer-to-stream-in-node/amp/. The API of this library will stick to streams.
