### ISSUE TITLE
Code doesn't execute after connected to FTP server

### ISSUE THREAD

**Issue by Adrian-Samuel** [patrickjuchli/basic-ftp#88]
I connect successfully to the FTP server using the client library and more or less copy and paste example provided in the documentation. 
The code immediately after never gets executes and my code simply waits until it has a timeout

Here is my example code

```
const ftp = require("basic-ftp")
const fs = require("fs")

example()
async function example() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    
    try {

        await client.access({
            host: host,
            user: username,
            password: password,
            secure: true
        });

 console.log("This code never gets executed")


        await client.upload(fs.createReadStream("file.txt"), "file.txt")
    } catch (err) {
        console.log(err)
    }
           await client.close()
        console.log(" connection closed")
}

```
**Console output**
Connected to XX.XXX.XXX.XXX.XX
Error: Timeout (control socket)
    at Socket.<anonymous> (/Users/adrian/Documents/SFTP/node_modules/basic-ftp/dist/FtpContext.js:290:58)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at Socket._onTimeout (net.js:432:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

Node Version: v12.4.0

FTP server I'm connecting to: net2ftp

Does anyone have any insight into this?

**Comment by patrickjuchli** [comment]
Please use `client.ftp.verbose = true` and paste the output here. To me it looks like the connection attempt itself has a timeout, you're not really even connected yet. This would then be a network or server issue.

**Comment by patrickjuchli** [comment]
Oh, is this above already the console output? Then it looks like the socket connects but the FTP server itself doesn't answer at all.

**Comment by patrickjuchli** [comment]
By the way, when searching for net2ftp I can only find a **client**, not a server. Can you point me to a site describing the site?

**Comment by Adrian-Samuel** [comment]
hey @patrickjuchli, thank you for the quick reply!
It's strange because I get the string connected to "IP address"
And I've put the client.ftp.verbose=true just under the instantiation of the ft.client()

And yeah the output is what the console provides. Very very interesting...

My apologises, here is the actual site: https://data.shoppertrak.com/index.php

**Comment by patrickjuchli** [comment]
That the socket connected is really only the very first step. The next thing that should happen is a so-called welcome message from the server but there is none. Are you sure you're connecting to the FTP server? Host and port are correct?

I'm sorry but this does not look like a library issue. You're either not really connecting to an FTP server or there is some other problem. Did you try another FTP server?

**Comment by Adrian-Samuel** [comment]
Ahh okay...That's interesting! 

I haven't tried another FTP server in my troubleshooting steps.

From the details they've given me thus far, this is what I have. Thank you for your insight though, I'll follow up with them!

**Comment by patrickjuchli** [comment]
Will close this issue for now. Feel free to reopen if there does seem to be something wrong with the library.
