### ISSUE TITLE
uploading files with unstable connection 

### ISSUE THREAD

**Issue by kojaktaha** [patrickjuchli/basic-ftp#89]
I am using electron to develop a desktop that can upload files under **unstable** connections, I would like to be able to detect a timeout in the file upload and resume the file upload after the outage.

The code I used to upload and track the progress is

`
        // getting the files locations array 
        let temp = JSON.parse(localStorage.getItem('fileUploads'));

      if (temp.length > 0) {
        let flag = 0
        while (flag <= temp.length) 
        {
            client.ftp.verbose = true ; 
            try {
              await client.access({
              host: 'XXX.XX.XXX.XXX',
              user: 'XXXX@XXX.com',
              password: 'XXXXXXXX' , 
            })
          client.trackProgress(info => {
            console.log("File", info.name)
            console.log("Type", info.type)
            console.log("Transferred", info.bytes)
            console.log("Transferred Overall", info.bytesOverall)
            })

          await client.upload(fs.createReadStream(temp[flag].local_filepath),temp[flag].local_filename)
          client.trackProgress(info => console.log(info.bytesOverall))
          client.trackProgress()

          // AFTER THE FILE HAS BEEN UPLOADED I NEED TO MOVE IT TO ANOTHER DIRECTORY IN
          // THE SERVER
          let  response = await axios.post(baseURL1 + '/api/move-file', {
            file_path: temp[flag].local_filename,
            id: temp[flag]._id,
            field: temp[flag].field_name,
          });
        
          flag = flag + 1 ; 

      }
      catch(err) {
              flag = flag + 1 ; 
      }
      client.close() 

    }
  }
}`

**First**: if I upload a file larger than 2 MB I get an error saying 

`Error: Timeout (control socket)
    at Socket.socket.once (FtpContext.js?9ea5:290)
    at Object.onceWrapper (events.js:273)
    at Socket.emit (events.js:182)
    at Socket._onTimeout (net.js:445)
    at ontimeout (timers.js:427)
    at tryOnTimeout (timers.js:289)
    at listOnTimeout (timers.js:252)
    at Timer.processTimers (timers.js:212)`

**Second**: how do I resume a file that has been interrupted

**Comment by patrickjuchli** [comment]
I'm not sure I understand your first question. You're being notified of the timeout with the exception you got. That's how it works.

You would then catch that exception.  The client is closed after that and you'll have to use `access` again. For a uploader I'd then recommend to always check the file size of the uploaded file. If it differs from the local file size, continue the upload with `append` and set our `createReadStream` with a `startAt` using the size of the incomplete file.

There is one thing I'm interested in: Your timeout is being emitted by the control socket. I would have expected the data socket to timeout. Could you post the debug console output?

**Comment by kojaktaha** [comment]
do you mean this 

  * Send the current handler a response. This is usually a control socket response
     * or a socket event, like an error or timeout.
     * @protected
     */
    _passToHandler(response) {
        if (this._task) {
            this._task.responseHandler(response, this._task.resolver);
        }
        // Errors other than FTPError always close the client. If there isn't an active task to handle the error,
        // the next one submitted will receive it using `_closingError`.
        // There is only one edge-case: If there is an FTPError while no task is active, the error will be dropped.
        // But that means that the user sent an FTP command with no intention of handling the result. So why should the
        // error be handled? Maybe log it at least? Debug logging will already do that and the client stays useable after
        // FTPError. So maybe no need to do anything here.
    }
    /**
     * Setup all error handlers for a socket.
     * @protected
     */
    _setupErrorHandlers(socket, identifier) {
        socket.once("error", error => {
            error.message += ` (${identifier})`;
            this.closeWithError(error);
        });
        socket.once("close", hadError => {
            if (hadError) {
                this.closeWithError(new Error(`Socket closed due to transmission error (${identifier})`));
            }
        });
        socket.once("timeout", () => this.closeWithError(new Error(`Timeout (${identifier})`)));
    }
    /**
     * Close a socket.
     * @protected
     */

**Comment by patrickjuchli** [comment]
No, when using `client.ftp.verbose = true`, you'll get useful information on the console. Please copy-paste your console logs here and remove any specific IPs.

**Comment by patrickjuchli** [comment]
@kojaktaha, I'm not sure about the status of this issue. Did I answer your question about timeout behaviour?

**Comment by kojaktaha** [comment]
Sorry for the delay, this is the message 
```
Connected to xx.xx.xx.xx:21
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 10:12. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
 Login security: No encryption
USER xx@xx.com
331 User xx@xx.xx.com OK. Password required
PASS ###
230 OK. Current restricted directory is /
TYPE I
200 TYPE is now 8-bit binary
STRU F
 200 F OK
 Trying to find optimal transfer strategy...
 EPSV
```

**Comment by patrickjuchli** [comment]
The timeout happens after the line`EPSV`?

Try this right after instantiating the client: `client.prepareTransfer = ftp.enterPassiveModeIPv4`.

**Comment by patrickjuchli** [comment]
Reading through your first post again, I believe your questions have been answered. Is this correct? I will close this issue, please feel free to reopen if there is still an open issue specific to this library.
