### ISSUE TITLE
Linux file permissions

### ISSUE THREAD

**Issue by JoeMoov2** [patrickjuchli/basic-ftp#9]
Is there a way to set default linux file permissions, or take ones from the users umask? 

Currently everything is created as 744, however a way to specify this on a per file or per folder basis would be very helpful.

**Comment by patrickjuchli** [comment]
Setting file permissions depends on the operating system the FTP server is running on. FTP knows the SITE command for these site-specific features. For servers running on Unix, the subverb CHMOD is supported. You could use something like `client.send("SITE CHMOD 600 myfile.txt")`.

If this library were to provide a dedicated API for this, it would have to support different operating systems with their expected SITE subverbs. There are no plans to do this right now. 

But with the example provided above you should be able to do everything you need for your specific use case. Similar to how `client.downloadDir` is implemented you could also recursively apply permissions to all contents of a directory.

**Comment by JoeMoov2** [comment]
I did assume this might be outside the scope of the project, as the project README says, but that workaround should be more than enough!

**Comment by JoeMoov2** [comment]
In case anybody comes across this in future and wants a quick solution, here is what I ended up with, as Patrick suggested, it is based off of the `downloadDir` code very heavily.

```js
async function chmod(permission) {
    for (const file of await client.list()) {
        if (file.isDirectory) {
            await client.send("SITE CHMOD " + permission+ " " + file.name);
            await client.cd(file.name);
            await chmod(permission);
            await client.send("CDUP");
        }
        else {
            await client.send("SITE CHMOD " + permission+ " " + file.name);
        }
    }
}
```

**Comment by patrickjuchli** [comment]
Great you found something that works. Just keep in mind that setting permissions using FTP is non-standard functionality. It's possible that an FTP server implementation does not support SITE CHMOD even when running on Unix. Also keep in mind that this won't work for servers running on Windows.
