### ISSUE TITLE
Unknown command: STRU F (Speedport Hybrid)

### ISSUE THREAD

**Issue by Phoscur** [patrickjuchli/basic-ftp#92]
**Describe the bug**
Cannot connect properly to Speedport Hybrid (insecure) FTP storage:
`Unknown command: STRU F`
Connecting via WinSCP is working.

**Example code**
Default example code with secure option false
```javascript
await client.access({secure:false})
console.log(await client.list())
```

**Console output**
```
Connected to 192.168.2.1:21
< 220 bftpd %v at 192.168.2.1 ready.
Login security: No encryption
> USER picamera
< 331 Password please.
> PASS ###
< 230 User logged in.
> TYPE I
< 200 Transfer type changed to BINARY
> STRU F
< 500 Unknown command: "STRU F"
{ FTPError: 500 Unknown command: "STRU F"
    at FTPContext._onControlSocketData (C:\Users\phosc\Projects\phil-photo\node_modules\basic-ftp\dist\FtpContext.js:256:39)
    at Socket.socket.on.data (C:\Users\phosc\Projects\phil-photo\node_modules\basic-ftp\dist\FtpContext.js:115:44)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:273:13)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17) name: 'FTPError', code: 500 }
```
**Which version of Node.js are you using?**
Node 10.15.2

**Additional context**
Speedport Hybrid seems not to support SFTP although its settings make it look like it :/

**Comment by patrickjuchli** [comment]
That's surprising because `STRU F` is part of the [minimum implementation as specifed by RFC 959](https://tools.ietf.org/html/rfc959#section-5).

I can look into ignoring errors by this command but I'm not thrilled about it.

**Comment by Phoscur** [comment]
I am able to list the home directory with the promise-ftp package. Since this package is called "basic-ftp" I would expect it to allow connecting in the most basic way too :P

**Comment by patrickjuchli** [comment]
You can also connect in a more manual way. For your case that would be:

```js
const client = new ftp.Client()
await client.connect("localhost", 21)
await client.login("username", "password")
await client.send("TYPE I") // Binary transmission at least
```

**Comment by Phoscur** [comment]
Indeed that works, thanks!
