### ISSUE TITLE
[Feature Request] Using debug module for verbose debug output? 

### ISSUE THREAD

**Issue by KerimG** [patrickjuchli/basic-ftp#93]
Hi, 

is there interest in using the [debug ](https://www.npmjs.com/package/debug) module for the verbose output?

@patrickjuchli 
If you're okay with that, I would consider building it in.

**Comment by patrickjuchli** [comment]
I don't want to add a specific logging library as a dependency. See [Readme#Logging](https://github.com/patrickjuchli/basic-ftp#logging) how you can use custom logging libraries. 

In your case you'd have to add the following line in your code right after instantiating a client:

```js
myClient.ftp.log = debug
```

**Comment by KerimG** [comment]
Argh! I'm sorry, for some reason I must have missed it!
