### ISSUE TITLE
infinite loop in downloadDir() in version >=4

### ISSUE THREAD

**Issue by k2s** [patrickjuchli/basic-ftp#99]
**Describe the bug**
* in version <4, the function `list()` returns array of 152 files in my remote directory
* then using versions >=4 it returns 154 files
  * the two additional files are `.` and `..`
* this is causing function `downloadDir()` to be in infinite loop by listing data in `.` directory

**Comment by patrickjuchli** [comment]
That's very interesting because that should (of course) not happen.

Could you use `client.ftp.verbose` and show me the output when using `client.list()`? Usually, `.` and `..` should be denoted in a special way but apparently they're not.

**Comment by patrickjuchli** [comment]
You can also try a new update, 4.2.1, which should address that case.

**Comment by k2s** [comment]
thank you, this was fast. I confirm that 4.2.1 fixes this issue.

**Comment by patrickjuchli** [comment]
That's great to hear! 

I'd be happy to see the raw log of a listing. There's something different with your server and I want to make sure I have a good enough understanding. If you could just use `client.ftp.verbose = true`, do a simple `client.list()` and post the console log here that would be great.

**Comment by k2s** [comment]
will [this](https://pastebin.com/vmStJaEP) help ?

**Comment by patrickjuchli** [comment]
Fantastic, thanks.
